/**
 * ============================================
 *  English Translations Dictionary
 *  Language strings for RentGuard-360 frontend
 * ============================================
 * 
 * STRUCTURE:
 * - nav: Navigation and layout strings
 * - auth: Authentication screens and messages
 * - dashboard / landing: Application overviews
 * - contracts / upload / analysis: Core flow
 * - score / methodology: Scoring logic
 * - admin / settings: Administration tools
 * 
 * DEPENDENCIES:
 * - Used exclusively by LanguageContext
 * 
 * ============================================
 */
export const en = {
    "nav": {
        "home": "Home",
        "brand": "RentGuard 360",
        "openMenu": "Open menu",
        "closeMenu": "Close menu",
        "openProfile": "Open profile",
        "closeProfile": "Close profile",
        "dashboard": "Dashboard",
        "upload": "Upload",
        "contracts": "Contracts",
        "settings": "Settings",
        "contact": "Contact",
        "pricing": "Pricing",
        "logout": "Logout",
        "admin": "Admin",
        "dark": "Dark",
        "light": "Light",
        "backToDashboard": "Back to Dashboard",
        "backToPrevious": "Back to previous page",
        "scansLeft": "scans",
        "unlimited": "Unlimited"
    },
    "export": {
        "started": "Export started...",
        "success": "Export completed successfully!",
        "error": "Export failed. Please try again.",
        "defaultFilename": "RentGuard_Analysis_Report",
        "defaultContractFilename": "RentGuard_Edited_Contract"
    },
    "auth": {
        "login": "Login",
        "register": "Sign Up",
        "email": "Email",
        "password": "Password",
        "fullName": "Full Name",
        "passwordHint": "At least 8 characters, uppercase and number",
        "loginButton": "Login",
        "registerButton": "Create Account",
        "noAccount": "Don't have an account?",
        "hasAccount": "Already have an account?",
        "confirmTitle": "Email Verification",
        "confirmMessage": "We sent a code to",
        "confirmCode": "Verification Code",
        "confirmButton": "Verify",
        "verificationSuccess": "Verification Successful!",
        "verificationSuccessMessage": "Don't forget to verify your email to use the website",
        "continueToLogin": "Continue to Login",
        "forgotPassword": "Forgot password?",
        "forgotPasswordTitle": "Reset Password",
        "forgotPasswordMessage": "Enter your email address and we will send you a reset code",
        "sendCodeButton": "Send Code",
        "resetPasswordTitle": "Set New Password",
        "resetPasswordMessage": "We sent a reset code to",
        "newPassword": "New Password",
        "resetCodePlaceholder": "Reset Code",
        "resetPasswordButton": "Reset Password",
        "backToLogin": "Back to Login",
        "socialLoginCanceledOrFailed": "Social login was canceled or failed",
        "socialLoginFailed": "Social login failed",
        "fillAllFields": "Please fill in all fields",
        "logoutToRegister": "To register, please log out from the current account first",
        "nameLengthError": "Name must be 2-50 characters",
        "passwordsDoNotMatch": "Passwords do not match",
        "accountAlreadyExistsHint": "It looks like you already have an account!",
        "accountNeedsVerification": "Account exists but requires verification.",
        "socialAccountOnly": "This email is linked to a social account. Please sign in with Google.",
        "registerPasswordPolicyError": "Password must include at least 8 characters, uppercase, lowercase and a number",
        "invalidEmailAddress": "Invalid email address",
        "accountAlreadyExists": "An account with this email already exists",
        "registerFailedTryAgain": "Registration failed. Please try again.",
        "confirmCodeInvalid": "Invalid verification code",
        "confirmCodeExpiredResend": "The code has expired. Please request a new code.",
        "verificationFailedTryAgain": "Verification failed. Please try again.",
        "newCodeSent": "New code sent to your email",
        "resendCodeFailed": "Failed to resend code. Try again.",
        "enterEmailAddress": "Please enter email address",
        "signInWithGoogle": "Sign in with Google",
        "continueWithGoogle": "Continue with Google",
        "orWithEmail": "or with email",
        "orSignUpWithEmail": "or sign up with email",
        "confirmPassword": "Confirm Password",
        "forgotPasswordShort": "Forgot Password",
        "didntReceiveCode": "Didn't receive the code?",
        "resendCode": "Resend Code",
        "wrongEmail": "Wrong email?",
        "registerAgain": "Register again",
        "socialLoginTitle": "Sign in with Social Account",
        "socialLoginDescription": "This email is already linked to a social login. Continue with Google.",
        "errors": {
            "attemptLimitExceeded": "Attempt limit exceeded, please try after some time",
            "invalidVerificationCodeProvided": "Invalid verification code",
            "userDoesNotExist": "User does not exist",
            "incorrectUsernameOrPassword": "Incorrect username or password",
            "passwordDidNotConformWithPolicy": "Password does not meet policy requirements",
            "accountWithEmailAlreadyExists": "An account with this email already exists",
            "invalidPasswordFormat": "Invalid password format",
            "cannotResetPasswordNoVerifiedEmail": "Cannot reset password because there is no registered/verified email",
            "userIsDisabled": "User is disabled",
            "failedToSendResetCode": "Failed to send reset code",
            "failedToResetPassword": "Failed to reset password",
            "codeMismatch": "Code mismatch",
            "expiredCode": "Code expired"
        },
        "heroTitle": "AI-Powered Rental Contract Analysis",
        "heroSubtitle": "Upload your rental contract and get a detailed analysis of:",
        "heroBenefit1": "Problematic clauses and legal risks",
        "heroBenefit2": "Overall risk score (0-100)",
        "heroBenefit3": "Negotiation tips",
        "heroFeatures": "Full Hebrew Support 🇮🇱 | Analysis in 60 seconds ⚡ | Full Privacy 🔒",
        "benefitCloud": "AWS Cloud-Based",
        "benefitCloudDesc": "Enterprise-grade infrastructure with 99.99% availability. Your documents are processed securely in the cloud.",
        "benefitAI": "Advanced AI",
        "benefitAIDesc": "Powered by Amazon Bedrock - one of the most intelligent AI systems available today.",
        "benefitSecurity": "Bank-Level Security",
        "benefitSecurityDesc": "End-to-end encryption. Your personal data is automatically masked before AI analysis. Zero data retention.",
        "benefitFast": "Lightning-Fast AI Analysis",
        "benefitFastDesc": "Simple contracts? Under 60 seconds. Complex ones? Just a few minutes. Our advanced AI scans every clause for your protection.",
        "demoTitle": "How it Works",
        "demoStep1": "Upload PDF",
        "demoStep1Desc": "Upload your rental contract in PDF format. We support Hebrew and English.",
        "demoStep2": "AI Analysis",
        "demoStep2Desc": "Our AI scans for risks, unfair terms, and legal issues.",
        "demoStep3": "Get Results",
        "demoStep3Desc": "View risk score, issue explanations, and negotiation tips.",
        "featureAI": "🤖 AI Analysis",
        "featureAIDesc": "Powered by Amazon Bedrock for contract analysis like a legal expert",
        "featurePrivacy": "🔒 Privacy First",
        "featurePrivacyDesc": "Personal info (ID, phone, email) is automatically masked before analysis",
        "featureTips": "💡 Smart Tips",
        "featureTipsDesc": "Get specific negotiation advice for each problematic clause",
        "footerTagline": "Protecting your lease with cutting-edge AI",
        "footerSupport": "Need help? Drop us a line:",
        "footerEmail": "rentguard360@gmail.com",
        "footerResponse": "Response within 24 hours | Our team is as dedicated to helping you as we are to analyzing your contracts",
        "projectName": "💻 Cloud Computing Final Project"
    },
    "dashboard": {
        "welcomeSubtitle": "Welcome to RentGuard 360. Upload and analyze rental contracts with AI.",
        "quickActions": "Quick Actions",
        "greeting": {
            "morning": "Good morning",
            "afternoon": "Good afternoon",
            "evening": "Good evening",
            "night": "Good night"
        },
        "totalContracts": "Total Contracts",
        "analyzed": "Analyzed",
        "pending": "Pending",
        "highRisk": "High Risk",
        "uploadContract": "Upload Contract",
        "uploadDescription": "Upload a new rental contract for AI analysis",
        "uploadPDF": "Upload PDF",
        "viewContracts": "View Contracts",
        "viewDescription": "Review all your uploaded contracts",
        "viewAll": "View All",
        "newFeaturesTitle": "New Features",
        "newFeaturesDesc": "More contract management tools and features will appear here soon.",
        "howToStart": "How to Start",
        "step1Title": "Upload Contract",
        "step1Desc": "Drag and drop your rental contract in PDF format",
        "step2Title": "AI Analysis",
        "step2Desc": "Simple contracts? Under 60 seconds. Complex ones? Just a few minutes. Our advanced AI scans every clause for your protection.",
        "step3Title": "Get Insights",
        "step3Desc": "View risks and negotiation suggestions",
        "whyUs": "Why RentGuard 360?",
        "whyUsSubtitle": "Not just another chatbot - a professional system built specifically for rental contract analysis",
        "featurePrivacy": "Privacy Protection",
        "featurePrivacyDesc": "The system automatically detects and redacts personal information (ID, phone, address) before sending to AI. Your details stay private.",
        "featurePrompt": "Custom Professional Prompt",
        "featurePromptDesc": "Unlike sending to a regular chat, our system uses a specialized prompt that analyzes 70+ risk factors according to Israeli rental law.",
        "featureScore": "Data-Driven Risk Score",
        "featureScoreDesc": "Get an objective score 0-100 with breakdown by categories: financial terms, tenant rights, liability and repairs, and more.",
        "featureTips": "Negotiation Tips",
        "featureTipsDesc": "Not just identifying issues - get concrete suggestions for fixing problematic clauses that you can present to the landlord.",
        "featureAws": "Secure Cloud Infrastructure",
        "featureAwsDesc": "Runs on AWS with end-to-end encryption. Your contracts are not stored and are automatically deleted after analysis."
    },
    "landing": {
        "heroSubtitleLine": "Your Rental Contract Guardian",
        "heroDescription": "Smart AI-powered contract analysis. Simply drag your file and get a legal snapshot in seconds.",
        "startFreeAnalysis": "Start Free Analysis",
        "noCreditCardRequired": "No credit card required",
        "carouselPrevious": "Previous",
        "carouselNext": "Next",
        "benefitAdvancedAiTitle": "Advanced AI Analysis",
        "benefitAdvancedAiDesc": "Advanced AI identifies problematic clauses and highlights risks.",
        "benefitPrivacyTitle": "Full Privacy",
        "benefitPrivacyDesc": "Your personal info is automatically hidden before analysis and restored after.",
        "benefitResultsTitle": "Results in Seconds",
        "benefitResultsDesc": "Get full contract analysis in under a minute, no lawyer needed.",
        "liveDemoTitle": "See it in action",
        "liveDemoSubtitle": "Example of a user's contract portfolio analysis",
        "clausesTitle": "Identify Problematic Clauses",
        "clausesDescription": "The system automatically identifies clauses that may harm your rights and provides plain-language explanations.",
        "clausesFeatureLaw": "Based on 2017 Rental Law",
        "clausesFeatureFixSuggestions": "Instant fix suggestions",
        "clausesFeatureRiskPerCategory": "Risk score per category",
        "registerPromptTitle": "Registration Required",
        "registerPromptDescription": "To upload and analyze contracts, please register for free.",
        "registerPromptButton": "Register Free",
        "registerPromptNoCard": "No credit card required"
    },
    mockups: {
        dashboard: {
            navDashboard: 'Dashboard',
            navContracts: 'Contracts',
            uploadTitle: 'Upload Lease Contract',
            uploadHint: 'PDF format, up to 5MB',
            selectFile: 'Select File',
            recentContracts: 'Recent Contracts',
            fileNameApartment: 'apartment_tlv.pdf',
            fileNameOffice: 'office_contract.pdf',
            scoreApartment: '92',
            scoreOffice: '58'
        },
        contracts: {
            generatingShareLink: 'Generating secure link...',
            menuShareTitle: 'Share Contract',
            menuShareTrigger: 'View this contract analysis checked by RentGuard',
            linkCopied: 'Link copied successfully!',
            linkCopiedFallback: 'Link copied to clipboard successfully!',
            shareFailed: 'Failed to share the link.',
            shareFailedSpecific: 'Failed to generate link, please try again.',
            analyzedPrefix: 'Analyzed:',
            lowRisk: 'Low Risk',
            mediumRisk: 'Medium Risk',
            highRisk: 'High Risk',
            propertyAddressLabel: 'Property Address:',
            landlordNameLabel: 'Landlord Name:',
            viewAnalysis: 'View Analysis',
            fileNameSafe: 'rental_telaviv.pdf',
            fileNameRisky: 'unprotected_lease.pdf',
            fileNameMedium: 'renewal_2025.pdf',
            addressSafe: '100 Dizengoff, Tel Aviv',
            landlordSafe: 'Israel Israeli',
            addressRisky: '45 Herzl, Ramat Gan',
            landlordRisky: 'Moshe Cohen',
            addressMedium: '10 HaNassi, Haifa',
            landlordMedium: 'David Levi',
            dateSafe: '22.12.2025',
            dateRisky: '20.12.2025',
            dateMedium: '18.12.2025'
        },
        viewer: {
            mediumRisk: 'Medium Risk',
            contractTitle: 'Unprotected Lease Agreement',
            clauseRentalPeriod: 'Rental Period',
            okBadge: 'OK',
            highRisk: 'High Risk',
            clauseLatePaymentPenalty: 'Late Payment Penalty',
            originalClauseText: 'A delay of up to 7 days in rent payment will result in an immediate penalty of 500 NIS per day.',
            legalExplanation: 'Legal Explanation',
            penaltyExplanation: 'This penalty is exceptionally high and deviates from standard practice. Courts may invalidate it for being disproportionate.',
            suggestionLabel: 'Suggested Fix: ',
            suggestionText: 'Limit penalty to standard interest rates or cap at 10% of monthly rent.',
            clauseRentAmount: 'Rent Amount & Indexation'
        }
    },
    "contracts": {
        "generatingShareLink": "Generating secure link...",
        "menuShareTitle": "Share Contract",
        "menuShareTrigger": "Share Analysis",
        "linkCopied": "Link copied successfully!",
        "linkCopiedFallback": "Link copied to clipboard!",
        "shareFailedSpecific": "Share failed. Please check your network connection.",
        "shareFailed": "Failed to share.",
        "deleteSuccessTitle": "Contract Deleted",
        "deleteSuccess": "The contract was successfully deleted from the system.",

        "title": "My Contracts",
        "subtitle": "Manage and view all your rental contracts",
        "activeContracts": "active contracts",
        "refresh": "Refresh",
        "refreshing": "Refreshing...",
        "uploadContract": "Upload Contract",
        "searchPlaceholder": "Search by contract name, property, or party...",
        "filterAll": "All",
        "filterHighRisk": "Critical risk",
        "filterPending": "In analysis",
        "noContracts": "No contracts yet",
        "noContractsDesc": "Upload your first rental contract for analysis",
        "uploadFirst": "Upload First Contract",
        "noResults": "No results found",
        "noResultsDesc": "Try changing your search text or filters",
        "clearFilters": "Clear filters",
        "deleteTitle": "Delete Contract",
        "deleteConfirm": "Are you sure you want to delete this contract? This action cannot be undone.",
        "cancel": "Cancel",
        "delete": "Delete",
        "deleting": "Deleting...",
        "editTitle": "Edit Details",
        "fileName": "File Name",
        "defaultFileName": "Contract",
        "propertyAddress": "Property Address",
        "landlordName": "Landlord Name",
        "save": "Save",
        "saving": "Saving...",
        "editSaveSuccessTitle": "Details Updated",
        "editSaveSuccessMessage": "Contract details were saved successfully.",
        "editSaveFailedTitle": "Failed to Save Contract Details",
        "loading": "Loading contracts...",
        "lowRisk": "Low Risk",
        "lowMediumRisk": "Low-Medium Risk",
        "mediumRisk": "Medium Risk",
        "highRisk": "High Risk",
        "analyzed": "Completed",
        "pendingAnalysis": "Pending",
        "notSpecified": "Not specified",
        "exportWord": "Export Word",
        "viewAnalysis": "View Analysis",
        "sortBy": "Sort by:",
        "sortDate": "Date",
        "sortScore": "Risk",
        "sortNewest": "Newest first",
        "sortOldest": "Oldest first",
        "sortHighRiskFirst": "High risk first",
        "sortLowRiskFirst": "Low risk first",
        "uploadDate": "Uploaded on",
        "riskScore": "Risk score",
        "analysisFailed": "Analysis failed",
        "processingData": "Processing contract clauses...",
        "untitledContract": "Untitled Contract",
        "analyzedPrefix": "Analyzed:",
        "statusTimedOutRetry": "Timed Out - Retry",
        "statusAnalysisFailed": "Analysis Failed",
        "statusFailedShort": "Analysis Failed",
        "statusPendingShort": "Pending...",
        "menuExportTrigger": "Export",
        "menuExportTitle": "Export Analysis Report",
        "menuDownloadTitle": "Download",
        "menuExportWordTitle": "Export Analysis Report (Word)",
        "menuExportWordNote": ".docx editable, best Hebrew support",
        "menuShareTrigger": "Share",
        "menuShareTitle": "Share Analysis Report",
        "editButtonTitle": "Edit",
        "deleteButtonTitle": "Delete",
        "deleteFailed": "Delete failed",
        "saveFailed": "Save failed",
        "exportFailed": "Export failed",
        "shareFailed": "Share failed",
        "shareRequiresHttps": "Sharing is available only over HTTPS on this device.",
        "exportPdfStarted": "PDF download started (English summary)",
        "exportWordStarted": "Word (.docx) download started",
        "shareSheetOpened": "Share sheet opened for PDF",
        "fileNamePlaceholder": "File name",
        "propertyAddressPlaceholder": "Property address",
        "landlordNamePlaceholder": "Landlord",
        "pageOf": "Page {current} of {total}"
    },
    "upload": {
        "title": "Upload Contract",
        "subtitle": "Upload your rental contract for AI analysis",
        "dragDrop": "Drop PDF here",
        "or": "or click to select file",
        "selectFile": "Select Files",
        "scanWithCamera": "Scan With Camera",
        "cameraBlockedTitle": "Camera Blocked",
        "cameraAccessError": "No camera access. Please go to your phone settings and allow camera permissions for your browser.",
        "cameraBlockedDesc1": "Cannot access the camera. You may have accidentally blocked it.",
        "cameraBlockedDesc2": "Mobile browsers prevent automatic redirects to settings. You must manually go into your device settings to unblock the camera, then refresh the page.",
        "cameraErrorPrefix": "Camera Error:",
        "selectedFiles": "Selected Files",
        "maxSize": "Max size: 5MB | PDF only",
        "termsLabel": "I confirm that I have read and understood the ",
        "termsLinkTerms": "Terms of Use",
        "termsLinkAnd": " and ",
        "termsLinkPrivacy": "Privacy Policy",
        "uploadBtn": "Upload Contract for Analysis",
        "uploading": "Uploading...",
        "readyForAnalysis": "Ready for Analysis",
        "fileNameLabel": "File Name",
        "deleteFile": "Delete file",
        "fileSizeByte": "byte",
        "complete": "Complete!",
        "uploadSuccess": "Upload Successful!",
        "analyzing": "AI is analyzing your contract (up to 2 minutes)...",
        "uploadedToServer": "✓ Contract uploaded to server",
        "analysisStarted": "✓ Analysis started",
        "viewMyContracts": "View My Contracts",
        "uploadAnother": "Upload Another Contract",
        "uploadSuccessTitle": "Contract Uploaded Successfully!",
        "uploadSuccessMessage": "Your contract analysis results will be sent to your email",
        "goToContracts": "Go to My Contracts",
        "contractDetails": "Contract Details (Optional)",
        "propertyAddress": "Property Address",
        "addressPlaceholder": "123 Main Street, City",
        "landlordName": "Landlord Name",
        "landlordPlaceholder": "John Smith",
        "contractName": "Contract Name",
        "pdfOnly": "Only PDF files are allowed",
        "fileTooLarge": "File size must be less than 5MB",
        "fileTooSmall": "File is too small - may be empty or corrupted",
        "fileNameTooLong": "Filename is too long (max 100 characters)",
        "fileNameRequired": "Please enter a file name before uploading",
        "termsRequired": "You must accept the Terms of Use and Privacy Policy before uploading",
        "validationToastTitle": "Cannot start upload",
        "uploadFailed": "Upload failed. Please try again.",
        "serverTemporaryError": "The server is temporarily busy. We retried automatically but it didn't work. Please try again in a few seconds."
    },
    "analysis": {
        "shareExpiryDays": "Expires in {days} days",
        "shareExpiryDaysOne": "Expires in 1 day",
        "shareExpiryDaysMany": "Expires in {days} days",
        "untitledClause": "Untitled Clause",
        "noDetailedContent": "No detailed content provided",
        "title": "Contract Analysis",
        "backToContracts": "Back to Contracts",
        "summary": "Summary",
        "scoreBreakdown": "Score Breakdown",
        "aggregateIntelligence": "Aggregate Intelligence",
        "overallHealth": "Contract Score",
        "overallRiskScore": "Overall Risk Score",
        "refresh": "Refresh",
        "export": "Export",
        "quickActions": "Quick Actions",
        "actionRequired": "Action Required",
        "contractMetadata": "Contract Metadata",
        "deepAnalysisAndClauses": "Deep Analysis & Clauses",
        "theIssue": "The Issue",
        "negotiationStrategy": "Negotiation Strategy",
        "issues": "Issues Found",
        "noIssues": "No issues found in this contract",
        "original": "Original",
        "problem": "Problem",
        "recommendation": "Recommendation",
        "copyFix": "Copy Fix",
        "copied": "Copied!",
        "askAI": "Ask AI",
        "loading": "Loading analysis...",
        "analyzing": "Analyzing contract...",
        "notContract": "This document does not appear to be a rental contract",
        "shareButtonCreating": "Creating link...",
        "shareButtonHide": "Hide shared link",
        "shareButtonShow": "Show shared link",
        "shareButtonCreate": "Create share link",
        "toastSavingTitle": "Saving changes",
        "toastSavingMessage": "Your edits are being saved now.",
        "toastSavedTitle": "Edits saved",
        "toastSavedMessage": "Your edits were autosaved to the cloud.",
        "toastSaveFailedTitle": "Save failed",
        "toastSaveFailedMessage": "Could not save your edits. Please try again in a moment.",
        "defaultReportName": "Analysis_Report",
        "exportWordStarted": "Word (.docx) download started",
        "exportPdfStarted": "PDF file download started",
        "missingShareContractId": "Missing contract id for sharing",
        "sharePanelHidden": "Share panel hidden",
        "sharePanelShown": "Active share link is shown",
        "shareCreated": "Share link created. Copy or share it from the panel.",
        "shareCreateFailed": "Failed to create share link",
        "shareCopiedTitle": "Link copied successfully",
        "shareCopiedMessage": "You can now paste and share it anywhere.",
        "shareCopyFailed": "Failed to copy link",
        "shareNativeTitle": "Shared contract from RentGuard 360",
        "shareNativeText": "View the contract (read-only):",
        "shareFailed": "Failed to share link",
        "shareRevokedTitle": "Share link revoked",
        "shareRevokedMessage": "The old link is no longer active.",
        "shareRevokeFailed": "Failed to revoke share link",
        "errors": {
            "notReadyTitle": "Analysis Not Ready",
            "notReadyMessage": "Your contract is still being processed. Auto-checking...",
            "failedTitle": "Analysis Failed",
            "failedMessage": "There was an error analyzing your contract. Our team has been notified. Please try uploading again.",
            "timeoutTitle": "Analysis Timed Out",
            "timeoutMessage": "The analysis is taking longer than expected. Please check back in a few minutes.",
            "genericTitle": "Something Went Wrong",
            "genericMessage": "Failed to load analysis results. Please try again."
        },
        "shareExpiryDefault": "Valid for 7 days",
        "shareExpiryExpired": "Expired",
        "shareExpiryDaysOne": "Valid for 1 more day",
        "shareExpiryDaysMany": "Valid for {days} more days",
        "technicalDetails": "Technical Details",
        "tryAgain": "Try Again",
        "contractDocument": "Contract Document",
        "analysisComplete": "Analysis complete.",
        "exportMenuTitle": "Export Analysis Report",
        "exportMenuDownload": "Download",
        "exportMenuWordTitle": "Export Analysis Report (Word)",
        "exportMenuFullContractWordTitle": "Export Full Contract (Word)",
        "exportMenuWordNote": "(.docx editable, best Hebrew support)",
        "exportMenuPdfTitle": "Download PDF - Analysis Report",
        "exportMenuPdfNote": "(best for quick viewing/sharing, English only)",
        "exportMenuShare": "Share",
        "fullContractExportNotReady": "Full contract export is not ready yet. Please try again after opening the Full Contract tab.",
        "fullContractTab": "Full Contract",
        "points": "points",
        "legalBasis": "Legal Basis",
        "whyItMatters": "Why It Matters",
        "negotiationTip": "Negotiation Tip",
        "notRentalTitle": "Not a Rental Contract",
        "notRentalDescription": "The uploaded document does not appear to be a valid rental contract. Please upload a residential rental contract in PDF format.",
        "noIssuesDescription": "This contract appears to be in good standing with no significant red flags.",
        "notRentalContentDescription": "The uploaded document does not appear to be a valid rental contract. Cannot display contract content.",
        "originalClause": "Original Clause",
        "recommendedClause": "Recommended Wording",
        "exportEditedWord": "Export to Word (.docx)",
        "resetEditsTitle": "Reset all edited clauses",
        "resetEdits": "Reset edits",
        "secureShareLink": "Secure share link",
        "shareLinkAria": "Share link",
        "copyLink": "Copy link",
        "sharing": "Sharing...",
        "shareViaApps": "Share via apps",
        "openLink": "Open link",
        "revoking": "Revoking...",
        "revokeLink": "Revoke link"
    },
    "contractView": {
        "consultError": "Could not fetch explanation. Please try again.",
        "editedContractFileName": "Edited_Rental_Contract",
        "expand": "Expand",
        "collapse": "Collapse",
        "contractTitle": "Unprotected Rental Agreement",
        "contractSubtitle": "Prepared and signed on ________________",
        "ocrDisclaimerTitle": "Notice: this text is OCR-based",
        "ocrDisclaimerBody1": "The contract below was extracted automatically from your uploaded PDF. Scanned image documents, especially phone captures, may contain text corruption, abnormal spacing, or broken tables.",
        "ocrDisclaimerBody2": "Use inline editing to fix specific glitches and export a corrected DOCX version. Before legal decisions, always compare against the original source file.",
        "showOnlyProblemClauses": "Show only problematic clauses",
        "clausesCountSuffix": "clauses",
        "issuesCountSuffix": "issues",
        "editedCountSuffix": "edited",
        "noIssuesFound": "No issues found!",
        "noTextFound": "No text found.",
        "getClauseExplanation": "Get clause explanation",
        "edit": "Edit",
        "editedBadge": "Edited",
        "aiExplanation": "AI Explanation",
        "fixSuggestion": "Suggested fix",
        "signaturesTitle": "Signatures",
        "landlord": "Landlord",
        "tenant": "Tenant",
        "namePlaceholder": "Name: ________________",
        "idPlaceholder": "ID: ________________",
        "datePlaceholder": "Date: ________________",
        "scrollUp": "Scroll up",
        "scrollToSignatures": "Scroll to signatures",
        "up": "Up",
        "toSignatures": "To signatures",
        "editClause": "Edit Clause",
        "originalClauseLabel": "Original clause:",
        "aiFixSuggestionLabel": "AI fix suggestion",
        "applySuggestion": "Apply suggestion",
        "editLabel": "Edit:",
        "editPlaceholder": "Edit the clause here...",
        "finishEditing": "Finish editing",
        "revertToOriginal": "Revert to original",
        "cancel": "Cancel",
        "confirmRevertTitle": "Confirm revert",
        "confirmRevertMessage": "Are you sure you want to cancel this edit and restore the original text?",
        "confirmRevertYes": "Yes, revert edit",
        "confirmRevertNo": "No, keep it",
        "clearAllTitle": "Delete all edits",
        "clearAllMessage": "Are you sure you want to delete all edits you made in this contract?",
        "irreversibleWarning": "This action cannot be undone.",
        "clearAllYes": "Yes, delete all"
    },
    "score": {
        "lowRisk": "Low Risk",
        "lowMediumRisk": "Low-Medium Risk",
        "mediumRisk": "Medium Risk",
        "mediumHighRisk": "Medium-High Risk",
        "highRisk": "High Risk",
        "financialTerms": "Financial Terms",
        "tenantRights": "Tenant Rights",
        "terminationClauses": "Termination & Exit",
        "liabilityRepairs": "Liability & Repairs",
        "legalCompliance": "Legal Compliance"
    },
    "contact": {
        "title": "We are here for you",
        "subtitle": "Have questions about your rental management? The RentGuard professional team is available to assist you with any legal or technical issue.",
        "successTitle": "Message Sent Successfully!",
        "successMessage": "We'll get back to you as soon as possible.",
        "sendAnother": "Send Another Message",
        "fullName": "Full Name",
        "fullNamePlaceholder": "John Smith",
        "phone": "Phone",
        "phonePlaceholder": "054-7820346",
        "email": "Email",
        "emailPlaceholder": "name@company.com",
        "message": "Message",
        "messagePlaceholder": "How can we help you today?",
        "sending": "Sending...",
        "sendMessage": "Send Message",
        "contactDetails": "Contact Details",
        "address": "Address",
        "addressValue": "Rothschild Blvd 22, Tel Aviv, Law Office",
        "emailLabel": "Email",
        "emailValue": "rentguard360@gmail.com",
        "phoneLabel": "Phone",
        "phoneValue": "050-0000000",
        "mapPopupText": "RentGuard-360 TLV",
        "joinText": "Join thousands of property owners who choose peace of mind with RentGuard.",
        "defaultSubject": "New Contact Page Inquiry",
        "errorMessage": "Failed to send message. Please try again.",
        "secureCommunication": "Secure Communication",
        "fastResponse": "Response within 24 hours",
        "notCustomerYet": "Not a customer yet?",
        "registerNowFree": "Register now for free",
        "registerFreePlan": "Register to get the free plan",
        "orOption": "Or",
        "toStartAnalyzing": "to start analyzing contracts"
    },
    "methodology": {
        "title": "How is the score calculated?",
        "intro1": "The score is 5 categories x 20 pts each (total 100). Points are deducted by severity.",
        "intro2": "Cap rule: a category cannot drop below 0, so the maximum drop per category is 20 points (therefore total penalties can be higher than the actual score decrease).",
        "high": "High",
        "medium": "Medium",
        "low": "Low",
        "pts": "pts",
        "categoriesHeader": "5 categories x 20 points = 100",
        "catFinancial": "Financial Terms",
        "catFinancialDesc": "Deposit, late fees, insurance",
        "catRights": "Tenant Rights",
        "catRightsDesc": "Entry rights, sublet, privacy",
        "catTermination": "Contract Termination",
        "catTerminationDesc": "Notice period, early exit",
        "catLiability": "Liability & Repairs",
        "catLiabilityDesc": "Repairs, reasonable wear and tear",
        "catLegal": "Legal Compliance",
        "catLegalDesc": "Compliance with Israeli Rental Law (2017)",
        "legalSource": "Based on the Rental and Lending Law (2017 amendment), sections 25A-25O"
    },
    "footer": {
        "tagline": "AI-Powered Rental Contract Analysis Platform",
        "benefits": "Full Privacy | Fast & Secure Analysis | Negotiation Tips | Secure Cloud Infrastructure",
        "project": "Cloud Computing Final Project",
        "copyright": "© {year} RentGuard 360. All rights reserved.",
        "legalTagline": "Smart legal protection for every rental agreement.",
        "contactSectionTitle": "Contact Us",
        "quickLinksTitle": "Quick Links",
        "personalAreaTitle": "Personal Area",
        "legalSectionTitle": "Legal",
        "termsLink": "Terms of Service",
        "privacyLink": "Privacy Policy",
        "contactLink": "Contact Us",
        "builtBy": "Built by",
        "andSeparator": " & "
    },
    "chat": {
        "title": "RentGuard 360 Chat",
        "open": "Open contract chat",
        "close": "Close chat",
        "contractLabel": "Contract",
        "selectContract": "Select contract",
        "loadingContracts": "Loading contracts...",
        "emptySelectContract": "Choose a contract to start asking questions.",
        "emptyStart": "No messages yet. Ask your first question.",
        "scope": "Answers are based on the selected contract only. Not legal advice.",
        "quickPromptsLabel": "Quick prompt suggestions",
        "promptHighRisk": "What are the top 3 highest risks in this contract?",
        "promptPets": "Does this contract allow pets or a dog?",
        "promptTermination": "What are the termination terms and penalties?",
        "inputPlaceholder": "Ask about clauses, fees, pets, termination...",
        "send": "Send question",
        "clear": "Clear history",
        "clearShort": "Clear",
        "clearConfirm": "Clear all chat history for the selected contract? This action cannot be undone.",
        "clearSuccessTitle": "Chat history cleared",
        "clearSuccessMessage": "Removed {count} message(s) from history.",
        "clearSuccessMessageGeneric": "Chat history was cleared successfully.",
        "copy": "Copy",
        "copied": "Copied",
        "you": "You",
        "assistant": "AI Assistant",
        "sourceContract": "Based on contract text",
        "sourceGeneral": "General guidance (not direct quote)",
        "evidenceTitle": "Contract excerpts",
        "thinking": "AI is analyzing the contract",
        "tip": "Tip: Ask about clauses, fees, or termination.",
        "disclaimer": "AI can be wrong. Verify key contract details.",
        "showNotice": "Show info",
        "hideNotice": "Hide info",
        "noAnswer": "No answer generated.",
        "dismissHint": "Dismiss message",
        "hints": {
            "rateLimit": "You hit a temporary question limit due to load. Please wait about a minute and try again."
        },
        "rateLimitRetryIn": "Try again in {seconds}s.",
        "errors": {
            "loadContracts": "Failed to load contracts. Please retry.",
            "loadHistory": "Failed to load chat history. Please retry.",
            "selectContract": "Select a contract first.",
            "askFailed": "Could not get an answer. Please try again.",
            "clearFailed": "Failed to clear history. Please try again."
        }
    },
    "common": {
        "error": "Error",
        "success": "Success",
        "user": "User",
        "cancel": "Cancel",
        "confirm": "Confirm",
        "ok": "OK",
        "clearSelections": "Clear selections",
        "comingSoon": "Coming Soon"
    },
    "errorBoundary": {
        "title": "Something went wrong",
        "message": "Something went wrong. Please try refreshing the page.",
        "reload": "Reload Page",
        "details": "Error Details"
    },
    "languageToggle": {
        "switchToEnglish": "Switch to English",
        "switchToHebrew": "Switch to Hebrew",
        "heLabel": "HE",
        "enLabel": "EN"
    },
    "recommendationCard": {
        "defaultTitle": "Suggested fix",
        "applied": "Applied",
        "revertTitle": "Undo changes and restore original",
        "revert": "Revert",
        "applyFix": "Apply fix"
    },
    "notifications": {
        "bundleRequiredTitle": "Select a bundle first",
        "bundleRequiredMessage": "To continue, please choose a bundle from the pricing page.",
        "contactSentTitle": "Message sent",
        "contactSentMessage": "Your message was received. We will reply soon.",
        "contactFailedTitle": "Message failed to send",
        "contactFailedMessage": "We could not send your message right now. Please try again.",
        "uploadFailedTitle": "Upload failed",
        "analysisReadyTitle": "Analysis is ready",
        "analysisReadyMessage": "Your contract has been analyzed and results are available.",
        "adminUserEnabledTitle": "User enabled",
        "adminUserEnabledMessage": "User {user} was enabled successfully.",
        "adminUserEnableFailedTitle": "Enable user failed",
        "adminUserEnableFailedMessage": "Could not enable user {user}.",
        "adminUserDisabledTitle": "User disabled",
        "adminUserDisabledMessage": "User {user} was disabled.",
        "adminUserDisableFailedTitle": "Disable user failed",
        "adminUserDisableFailedMessage": "Could not disable user {user}.",
        "adminUserDeletedTitle": "User deleted",
        "adminUserDeletedMessage": "User {user} was deleted permanently.",
        "adminUserDeleteFailedTitle": "Delete user failed",
        "adminUserDeleteFailedMessage": "Could not delete user {user}."
    },
    "account": {
        "deleteAccount": "Delete Account",
        "deleteAccountDescription": "Permanently delete your account and all your contracts",
        "deleteConfirmTitle": "Are you sure?",
        "deleteConfirmMessage": "This action will permanently delete your account, including:",
        "deleteConfirmItem1": "• All your contracts",
        "deleteConfirmItem2": "• All your analyses",
        "deleteConfirmItem3": "• Your profile data",
        "deleteConfirmWarning": "This action cannot be undone!",
        "typeDeleteToConfirm": "Type DELETE to confirm:",
        "typeDeleteToConfirmError": "Please type DELETE to confirm",
        "deleteAccountSuccess": "Account deleted successfully",
        "deleteAccountError": "Error deleting account",
        "deletingAccount": "Deleting account...",
        "deletingContracts": "Deleting contracts..."
    },
    "settings": {
        "title": "Control Center",
        "subtitle": "Manage your profile, appearance, and security settings in one centralized hub.",
        "activeAccount": "Active Account",
        "profileFallbackUser": "User",
        "appearanceTitle": "Appearance",
        "appearanceDesc": "Toggle light/dark mode",
        "darkMode": "Dark Mode",
        "lightMode": "Light Mode",
        "languageTitle": "Language",
        "languageDesc": "Switch the interface language between English and Hebrew.",
        "languageEnglish": "English",
        "languageHebrew": "Hebrew",
        "manageBilling": "Manage Billing",
        "chatBehaviorTitle": "Chat Behavior",
        "chatBehaviorDesc": "Control whether the contract chat opens automatically when entering an analysis page.",
        "chatAutoOpenOn": "Auto-open: On",
        "chatAutoOpenOff": "Auto-open: Off",
        "mobileNavTitle": "Mobile Navigation",
        "mobileNavDesc": "Enable a compact top bar on mobile for a cleaner layout.",
        "mobileNavCompactOn": "Compact mobile nav: On",
        "mobileNavCompactOff": "Compact mobile nav: Off",
        "alertsTitle": "Alerts",
        "alertsDesc": "Updates are sent to your verified email address.",
        "alertsTip": "Check spam if email missing",
        "systemInfoTitle": "System Info",
        "versionLabel": "Version",
        "builtByLabel": "Built by",
        "devTeam": "Ron, Moty & Idan",
        "deleteAccountTitle": "Delete Account",
        "deleteAccountDesc": "This will permanently delete your account and all associated contracts. This cannot be undone."
    },
    "admin": {
        "loadMore": "Load More...",
        "loadMoreUsers": "Load more users..",
        "packageFree": "Free",
        "packageSingle": "Single",
        "packageBasic": "Basic",
        "packagePro": "Pro",
        "packageAdmin": "Admin",
        "packageNone": "No package",
        "packageExpired": "Expired package",
        "title": "Admin Dashboard",
        "accessDenied": "Access Denied",
        "noPermission": "You do not have admin permissions",
        "statsTab": "Statistics",
        "usersTab": "Users",
        "stripeTab": "Stripe Insights",
        "tryAgain": "Try Again",
        "contractsSection": "Contracts",
        "totalContracts": "Total Contracts",
        "analyzed": "Analyzed",
        "pending": "Pending",
        "failed": "Failed",
        "analysisSection": "Analysis",
        "avgRiskScore": "Avg Risk Score",
        "avgAnalysisTime": "Avg Analysis Time",
        "usersSection": "Users",
        "totalUsers": "Total Users",
        "activeUsers30": "Active (30 days)",
        "updatedAt": "Updated",
        "seconds": "seconds",
        "minutes": "minutes",
        "days": "days",
        "thisMonth": "This Month",
        "thisYear": "This Year",
        "analyzedOverTime": "Analyzed Contracts Over Time",
        "userRegistrations": "User Registrations Over Time",
        "allTime": "All Time",
        "noData": "No data to display",
        "searchPlaceholder": "Search by email or name...",
        "search": "Search",
        "email": "Email",
        "name": "Name",
        "userLabel": "User",
        "status": "Status",
        "joined": "Joined",
        "actions": "Actions",
        "noUsers": "No users found",
        "active": "Active",
        "pendingVerification": "Pending verification",
        "suspended": "Suspended",
        "disable": "Disable",
        "enable": "Enable",
        "delete": "Delete",
        "copyEmail": "Copy Email",
        "copied": "Copied",
        "copySuccessTitle": "Email copied",
        "copySuccessMessage": "Email address was copied to clipboard.",
        "copyFailed": "Unable to copy email. Please select and copy manually.",
        "advancedFilter": "Advanced Filter",
        "authProvider": "Provider",
        "package": "Package",
        "emailPassword": "Email",
        "allUsers": "All Users",
        "activeOnly": "Active Only",
        "disabledOnly": "Disabled Only",
        "none": "No package",
        "pending": "pending",
        "expired": "expired",
        "packageNone": "No package",
        "packageExpired": "Expired package",
        "showingUsers": "Showing {count} users",
        "showingUsersDetailed": "Showing {visible} of {total} registered users",
        "confirmDisable": "Are you sure you want to disable this user?",
        "confirmDisableTitle": "Disable User",
        "confirmDelete": "Are you sure you want to delete this user?",
        "confirmDeleteTitle": "Delete User",
        "confirmDeleteFinal": "This action cannot be undone! The user will be permanently deleted. Continue?",
        "confirmDeleteFinalTitle": "⚠️ Final Confirmation",
        "confirmDeleteBtn": "Yes, Delete Permanently",
        "selectYear": "Select Year",
        "userDeleted": "User deleted successfully",
        "dashboard": "Dashboard",
        "analytics": "Analytics",
        "settings": "Settings",
        "administrator": "Administrator",
        "analyticsDescription": "Detailed contract analysis and risk insights",
        "radarChart": "Risk Radar",
        "radarChartDesc": "5-axis risk analysis coming soon",
        "sparklines": "Trend Sparklines",
        "sparklinesDesc": "Mini trend charts coming soon",
        "riskBreakdown": "Risk Breakdown",
        "riskBreakdownDesc": "Detailed category analysis",
        "riskDistribution": "Risk Distribution",
        "commonIssues": "Common Issues in Contracts",
        "code": "Code",
        "issue": "Issue",
        "count": "Count",
        "noIssuesYet": "No issues found yet - upload contracts for analysis",
        "stripeInsightsTitle": "Stripe & Billing Insights",
        "stripeInsightsSubtitle": "A full view of charges, conversion quality, revenue, and bundle data",
        "generatedAt": "Updated at",
        "availableBalance": "Available Balance",
        "pendingBalance": "Pending Balance",
        "charges30Days": "Charges (30 days)",
        "disputes30Days": "Disputes (30d)",
        "intents30Days": "Payment Intents (30 days)",
        "successRate": "Success Rate",
        "refundedCharges": "Refunded Charges",
        "revenue": "Revenue",
        "avgOrderValue": "Average Order Value",
        "activeSubscribers": "Active Subscribers",
        "transactions": "Transactions",
        "bundleDistribution": "Bundle Distribution",
        "recentTransactions": "Recent Transactions",
        "bundle": "Bundle",
        "amount": "Amount",
        "currency": "Currency",
        "country": "Country",
        "stripeFeatures": "Stripe Features",
        "chargesEnabled": "Charges Enabled",
        "payoutsEnabled": "Payouts Enabled",
        "enabled": "ON",
        "disabled": "OFF",
        "refundAmount30Days": "Refund Amount (30d)",
        "intentToChargeConversion": "Intent to Charge Conversion",
        "paymentMethodMix": "Payment Method Mix",
        "noPaymentSignals": "No payment method data yet.",
        "failedCharges30Days": "Failed Charges (30d)",
        "disputeRate": "Dispute Rate",
        "refundRate": "Refund Rate",
        "chargesToIntents": "Charges / Intents",
        "topCurrencies": "Top Currencies",
        "noCurrencyAmounts": "No currency amounts found yet.",
        "stripeStatusError": "Unable to fetch Stripe runtime details right now",
        "settingsDescription": "System configuration and preferences",
        "notifications": "Notifications",
        "notificationsDesc": "Configure email and push notifications",
        "security": "Security",
        "securityDesc": "Authentication and access control",
        "dataRetention": "Data Retention",
        "dataRetentionDesc": "Contract storage and backup settings",
        "emailTemplates": "Email Templates",
        "emailTemplatesDesc": "Customize notification emails",
        "comingSoon": "Coming Soon"
    },
    "pricing": {
        "title": "Choose Your Bundle",
        "subtitle": "Select the bundle that best fits your needs and start analyzing rental contracts with AI",
        "currentPlan": "Current Bundle:",
        "scansLeft": "scans left",
        "unlimited": "Unlimited",
        "mostPopular": "Most Popular",
        "yourPlan": "Your Bundle",
        "currentPlanBtn": "Current Bundle",
        "getStarted": "Get Started Free",
        "subscribe": "Purchase",
        "buyMoreScans": "Buy more scans",
        "free": "Free",
        "single": "Single",
        "basic": "Basic",
        "pro": "Pro",
        "month": "month",
        "scans": "scans",
        "unlimitedScans": "15 scans",
        "freeDesc": "A quick first taste before upgrading",
        "singleDesc": "One-off scan for occasional users",
        "basicDesc": "The most popular and best-value bundle for most users",
        "proDesc": "The full package for heavy and professional users",
        "featuresFree": [
            "1 free contract scan",
            "Basic AI analysis (highlights and risk summary)",
            "Option to buy one additional scan for 10 ILS afterward (limited to 1 per month)"
        ],
        "featuresSingle": [
            "1 contract scan for 10 ILS",
            "Available once per month",
            "Basic AI analysis (highlights and risk summary)"
        ],
        "featuresBasic": [
            "5 contract scans",
            "Full contract view",
            "Full AI analysis + detailed risk score",
            "Contract Q&A chat (up to 3 questions per day)",
            "Shareable contract link",
            "Word export for editing",
            "Advanced negotiation guidance"
        ],
        "featuresPro": [
            "15 contract scans",
            "Everything in Basic",
            "Unlimited contract Q&A chat",
            "Priority processing during peak times",
            "Priority human/technical support"
        ]
    },
    "checkout": {
        "title": "Complete Purchase",
        "backToPricing": "Back to Bundles",
        "orderSummary": "Order Summary",
        "plan": "Bundle",
        "scans": "Scans",
        "total": "Total",
        "paymentMethod": "Payment Method",
        "cardDetails": "Card details",
        "pay": "Pay",
        "processing": "Processing...",
        "securedByStripe": "Secured by Stripe",
        "testMode": "Test mode — use card",
        "termsLabel": "I agree to the ",
        "termsLinkTerms": "Terms of Service",
        "termsJoin": " and ",
        "termsLinkPrivacy": "Privacy Policy",
        "termsLinkText": "Terms of Service and Privacy Policy",
        "termsDisclaimer": ". I understand this is a one-time purchase of a scan bundle and no recurring charges will apply.",
        "termsRequired": "You must agree to the Terms of Service to proceed"
    },
    "paymentSuccess": {
        "title": "Payment Successful",
        "freeActivated": "Your free bundle has been activated. You can start scanning contracts now.",
        "paymentCompleted": "Your payment was processed successfully and your bundle has been updated.",
        "plan": "Bundle",
        "amount": "Amount",
        "hint": "You can start scanning rental contracts right away.",
        "goToDashboard": "Go to Dashboard",
        "uploadContract": "Upload Contract"
    },
    "subscription": {
        "myPlan": "My Bundle",
        "scansRemaining": "scans remaining",
        "unlimited": "Unlimited",
        "noPlan": "No Bundle",
        "upgrade": "Upgrade",
        "choosePlan": "Choose a Bundle",
        "noActivePlan": "No Active Bundle",
        "noActivePlanMessage": "To upload and scan a contract, activate a bundle first.",
        "noScansLeft": "No Scans Remaining",
        "noScansMessage": "Upgrade your bundle to continue scanning contracts.",
        "upgradePlan": "Upgrade Bundle"
    },
    "billing": {
        "title": "Billing & Payments",
        "subtitle": "Manage your payment methods, view invoices and billing history in one secure place.",
        "currentPlan": "Current Plan",
        "scansRemaining": "scans remaining",
        "unlimited": "Unlimited",
        "noPlan": "No active plan",
        "upgradePlan": "Upgrade Plan",
        "portalTitle": "Manage Payment Methods & Invoices",
        "portalDesc": "Update your credit card, download PDF invoices and view your complete payment history.",
        "portalButton": "Manage Payment Methods & Billing History",
        "portalLoading": "Preparing secure link...",
        "portalError": "Could not open the billing portal. Please try again.",
        "feature1Title": "Update Payment Methods",
        "feature1Desc": "Add or replace your credit card securely.",
        "feature2Title": "Download Invoices",
        "feature2Desc": "Download detailed invoices in PDF format.",
        "feature3Title": "Payment History",
        "feature3Desc": "View all your transactions and payments.",
        "filterLast5": "Last 5 transactions",
        "filterAllTransactions": "All transactions",
        "filterPaid": "Paid",
        "filterFailed": "Failed",
        "notAvailable": "N/A",
        "historyTitle": "Billing History",
        "noTransactionsForFilter": "No transactions found for the selected filter.",
        "statusPaid": "Paid",
        "statusFailed": "Failed",
        "statusUnknown": "Unknown",
        "poweredByStripe": "Powered by Stripe",
        "securityNote": "All your data is encrypted and secured at industry level.",
        "backToSettings": "Back to Settings"
    },
    "sharedContract": {
        "invalidLink": "Invalid link",
        "loadFailed": "Unable to load the contract from this link.",
        "loadingTitle": "Loading shared contract...",
        "loadingSubtitle": "We are securely fetching the contract document. This will take a moment.",
        "errorTitle": "Error loading contract",
        "retryButton": "Try again",
        "viewTitle": "Shared Contract View",
        "viewSubtitle": "Read-only mode. You can review the content and export the updated document to Word.",
        "exportWord": "Export as docx (Word)",
        "notRentalTitle": "The document is not a rental contract",
        "notRentalDesc": "The document content cannot be displayed from this link."
    },
    "legal": {
        "legalDocument": "Legal Document",
        "quickNavigation": "Quick Navigation"
    },
    "terms": {
        "title": "Terms of Service",
        "updated": "Last updated: March 2026",
        "tocTitle": "Table of Contents",
        "contactPrefix": "For additional questions, reach us via the",
        "contactLinkText": "Contact page",
        "contactMiddle": "or email us at",
        "sections": [
            {
                "id": "acceptance",
                "title": "1. Acceptance of Terms",
                "content": "By using the RentGuard 360 website and services, you agree to these Terms of Service. If you do not agree, please refrain from using our services."
            },
            {
                "id": "service",
                "title": "2. Service Description",
                "content": "RentGuard 360 provides AI-powered rental contract analysis. The service includes:",
                "list": [
                    "Automated scanning of rental contracts in PDF format",
                    "Identification of problematic clauses and conflicts of interest",
                    "Detailed risk scoring for each clause",
                    "Recommendations and suggested amendments",
                    "Report export in PDF and Word formats"
                ]
            },
            {
                "id": "purchases",
                "title": "3. Purchases & Payments",
                "content": "All purchases on the site are one-time purchases of scan bundles. There is no recurring billing or auto-renewing subscriptions. Payments are processed through Stripe and are secured according to PCI DSS standards. RentGuard 360 does not store your credit card details — all sensitive information is handled directly by Stripe."
            },
            {
                "id": "refund",
                "title": "4. Refund Policy",
                "content": "Since the service provides instant analysis upon purchase, refunds are only issued in exceptional circumstances (e.g., a technical failure that prevented the system from completing the analysis). For refund requests, please contact us through the Contact page."
            },
            {
                "id": "data",
                "title": "5. Data Storage & Privacy",
                "content": "We are committed to protecting your privacy. Key points:",
                "list": [
                    "Uploaded contracts are stored encrypted on AWS servers",
                    "Information is used solely to provide the requested service",
                    "We do not sell or share personal data with third parties",
                    "You may request deletion of your data at any time",
                    "We use only essential cookies for site operation"
                ]
            },
            {
                "id": "security",
                "title": "6. Data Security",
                "content": "We implement advanced security measures to protect your information, including SSL/TLS encryption, encrypted storage, multi-factor authentication (MFA), and continuous security monitoring. Our servers are hosted on AWS and comply with international security standards."
            },
            {
                "id": "disclaimer",
                "title": "7. Limitation of Liability",
                "content": "The analysis provided by RentGuard 360 is for informational purposes only and does not constitute legal advice. It is strongly recommended to consult with a lawyer before signing any contract. RentGuard 360 is not liable for decisions made based solely on the analysis."
            },
            {
                "id": "ip",
                "title": "8. Intellectual Property",
                "content": "All rights in the service, including design, code, algorithms, and content, belong to RentGuard 360. No part of the service may be copied, distributed, or reproduced without written permission."
            },
            {
                "id": "changes",
                "title": "9. Changes to Terms",
                "content": "We reserve the right to update these terms from time to time. Material changes will be published on the site and/or sent by email. Continued use of the service after terms are updated constitutes acceptance of the updated terms."
            },
            {
                "id": "contact",
                "title": "10. Contact Us",
                "content": "For questions regarding these Terms of Service or any other matter, please contact us through the Contact page on the site or by email."
            }
        ]
    },
    "privacy": {
        "title": "Privacy Policy",
        "updated": "Last updated: March 2026",
        "tocTitle": "Table of Contents",
        "contactPrefix": "For privacy-related questions, reach us via the",
        "contactLinkText": "Contact page",
        "contactMiddle": "or email us at",
        "sections": [
            {
                "id": "general",
                "title": "1. General Overview",
                "content": "At RentGuard 360 (\"Company\", \"we\", or \"our\"), we respect your privacy and are committed to protecting it. This Privacy Policy outlines how we collect, use, and safeguard your personal information when you use our website and services."
            },
            {
                "id": "collection",
                "title": "2. Information Collection",
                "content": "We collect various types of information to provide our services:",
                "list": [
                    "Registration and contact details (email address, full name).",
                    "Financial information is processed securely by authorized third-party payment gateways (e.g., Stripe); we do not store your credit card information on our servers.",
                    "Agreements and documents you choose to upload (for analysis through our AI systems)."
                ]
            },
            {
                "id": "usage",
                "title": "3. Use of Information",
                "content": "The collected information is used solely for the following purposes:",
                "list": [
                    "Providing automated document analysis services and improving your user experience.",
                    "Managing user accounts and providing customer or technical support.",
                    "Sending service notifications (such as system updates or report completions) – no marketing content will be sent without explicit consent."
                ]
            },
            {
                "id": "sharing",
                "title": "4. Sharing Information with Third Parties",
                "content": "We do not sell, trade, or transfer Personally Identifiable Information to outside parties for marketing purposes. We may share information with trusted third-party service providers (e.g., AWS, payment processors) acting on our behalf, provided that they agree to keep this information confidential and comply with our stringent privacy standards."
            },
            {
                "id": "ai-processing",
                "title": "5. AI Data Processing",
                "content": "Agreements you upload to the system are processed by Large Language Models (LLMs). Before the analysis, we employ text extraction and data masking mechanisms designed to redact potentially sensitive personal data (such as national IDs or phone numbers), to better safeguard your privacy."
            },
            {
                "id": "data-retention",
                "title": "6. Data Retention and Deletion",
                "content": "The documents uploaded for scanning are securely encrypted and retained in your account. You can request the deletion of your documents or even delete your entire account through the settings dashboard or by contacting support. Once requested, your data will be permanently removed from our active servers in compliance with applicable laws."
            },
            {
                "id": "cookies",
                "title": "7. Cookies",
                "content": "We use cookies strictly for managing your authenticated sessions and ensuring the proper functioning of the site. While you may disable cookies in your browser settings, doing so will impact the functionality of areas requiring user login."
            },
            {
                "id": "contact",
                "title": "8. Contacting Us",
                "content": "If you have any questions regarding this Privacy Policy or wish to review, update, or remove your personal data, please reach out to us using the contact details provided on our site."
            }
        ]
    }
    ,
    "checkingYourPlan": "Checking your plan..."
};
