export const he = {
    "nav": {
        "home": "דף הבית",
        "brand": "RentGuard 360",
        "openMenu": "פתח תפריט",
        "closeMenu": "סגור תפריט",
        "openProfile": "פתח פרופיל",
        "closeProfile": "סגור פרופיל",
        "dashboard": "לוח בקרה",
        "upload": "העלאה",
        "contracts": "חוזים",
        "settings": "הגדרות",
        "contact": "צור קשר",
        "pricing": "תוכניות",
        "logout": "התנתקות",
        "admin": "ניהול",
        "dark": "כהה",
        "light": "בהיר",
        "backToDashboard": "חזרה לדף הבית",
        "backToPrevious": "חזרה לעמוד הקודם",
        "scansLeft": "סריקות",
        "unlimited": "ללא הגבלה"
    },
    "export": {
        "started": "הייצוא מתחיל...",
        "success": "הייצוא הושלם בהצלחה!",
        "error": "הייצוא נכשל. אנא נסו שוב.",
        "defaultFilename": "דוח_ניתוח_חוזה_RentGuard",
        "defaultContractFilename": "חוזה_ערוך_RentGuard"
    },
    "auth": {
        "login": "התחברות",
        "register": "הרשמה",
        "email": "אימייל",
        "password": "סיסמה",
        "fullName": "שם מלא",
        "passwordHint": "לפחות 8 תווים, אות גדולה ומספר",
        "loginButton": "התחברות",
        "registerButton": "יצירת חשבון",
        "noAccount": "אין לך חשבון?",
        "hasAccount": "יש לך כבר חשבון?",
        "confirmTitle": "אימות אימייל",
        "confirmMessage": "שלחנו קוד לכתובת",
        "confirmCode": "קוד אימות",
        "confirmButton": "אימות",
        "verificationSuccess": "אימות הצליח!",
        "verificationSuccessMessage": "אל תשכח לאמת את האימייל שלך כדי להשתמש באתר",
        "continueToLogin": "המשך להתחברות",
        "forgotPassword": "שכחת סיסמה?",
        "forgotPasswordTitle": "איפוס סיסמה",
        "forgotPasswordMessage": "הזן את כתובת האימייל שלך ונשלח לך קוד איפוס",
        "sendCodeButton": "שלח קוד",
        "resetPasswordTitle": "הגדרת סיסמה חדשה",
        "resetPasswordMessage": "שלחנו קוד איפוס לכתובת",
        "newPassword": "סיסמה חדשה",
        "resetCodePlaceholder": "קוד איפוס",
        "resetPasswordButton": "אפס סיסמה",
        "backToLogin": "חזרה להתחברות",
        "socialLoginCanceledOrFailed": "ההתחברות החברתית בוטלה או נכשלה",
        "socialLoginFailed": "ההתחברות נכשלה",
        "fillAllFields": "יש למלא את כל השדות",
        "logoutToRegister": "כדי להירשם, התנתק קודם מהחשבון הנוכחי",
        "nameLengthError": "שם חייב להיות בין 2-50 תווים",
        "passwordsDoNotMatch": "הסיסמאות לא תואמות",
        "accountAlreadyExistsHint": "נראה שכבר יש לך חשבון!",
        "accountNeedsVerification": "החשבון קיים אך דורש אימות.",
        "socialAccountOnly": "האימייל הזה מחובר לחשבון חברתי. יש להתחבר דרך Google או Facebook.",
        "registerPasswordPolicyError": "הסיסמה חייבת לכלול לפחות 8 תווים, אות גדולה, אות קטנה ומספר",
        "invalidEmailAddress": "כתובת אימייל לא תקינה",
        "accountAlreadyExists": "המשתמש כבר קיים במערכת",
        "registerFailedTryAgain": "ההרשמה נכשלה. נסה שוב.",
        "confirmCodeInvalid": "קוד אימות שגוי",
        "confirmCodeExpiredResend": "הקוד פג תוקף. לחץ על שלח קוד חדש",
        "verificationFailedTryAgain": "האימות נכשל. נסה שוב.",
        "newCodeSent": "קוד חדש נשלח לאימייל שלך",
        "resendCodeFailed": "שליחת הקוד נכשלה. נסה שוב.",
        "enterEmailAddress": "יש להזין כתובת אימייל",
        "signInWithGoogle": "התחברות עם Google",
        "signInWithFacebook": "התחברות עם Facebook",
        "continueWithGoogle": "הרשמה עם Google",
        "continueWithFacebook": "הרשמה עם Facebook",
        "orWithEmail": "או עם אימייל",
        "orSignUpWithEmail": "או הרשמה באימייל",
        "confirmPassword": "אימות סיסמה",
        "forgotPasswordShort": "שכחתי סיסמה",
        "didntReceiveCode": "לא קיבלת את הקוד?",
        "resendCode": "שלח קוד חדש",
        "wrongEmail": "טעית באימייל?",
        "registerAgain": "הירשם מחדש",
        "socialLoginTitle": "התחברות דרך רשת חברתית",
        "socialLoginDescription": "האימייל הזה כבר מקושר להתחברות חברתית. כדי להמשיך, התחבר דרך Google (או Facebook בהמשך).",
        "errors": {
            "attemptLimitExceeded": "חרגת ממספר הניסיונות המותר, נסה שוב מאוחר יותר",
            "invalidVerificationCodeProvided": "קוד אימות שגוי",
            "userDoesNotExist": "משתמש לא קיים",
            "incorrectUsernameOrPassword": "שם משתמש או סיסמה שגויים",
            "passwordDidNotConformWithPolicy": "הסיסמה לא עומדת בדרישות המערכת",
            "accountWithEmailAlreadyExists": "כתובת האימייל כבר קיימת במערכת",
            "invalidPasswordFormat": "פורמט סיסמה לא תקין",
            "cannotResetPasswordNoVerifiedEmail": "לא ניתן לאפס סיסמה - אין אימייל רשום",
            "userIsDisabled": "המשתמש מושבת",
            "failedToSendResetCode": "שליחת קוד איפוס נכשלה",
            "failedToResetPassword": "איפוס הסיסמה נכשל",
            "codeMismatch": "קוד שגוי",
            "expiredCode": "הקוד פג תוקף"
        },
        "heroTitle": "ניתוח חוזי שכירות בבינה מלאכותית",
        "heroSubtitle": "העלו את חוזה השכירות שלכם וקבלו ניתוח מפורט של:",
        "heroBenefit1": "סעיפים בעייתיים וסיכונים משפטיים",
        "heroBenefit2": "ציון סיכון כולל (0-100)",
        "heroBenefit3": "טיפים למשא ומתן",
        "heroFeatures": "עברית מלאה 🇮🇱 | ניתוח תוך 60 שניות ⚡ | פרטיות מלאה 🔒",
        "benefitCloud": "מבוסס ענן AWS",
        "benefitCloudDesc": "תשתית ברמה ארגונית עם זמינות של 99.99%. המסמכים שלך מעובדים בבטחה בענן.",
        "benefitAI": "בינה מלאכותית מתקדמת",
        "benefitAIDesc": "מופעל על ידי Amazon Bedrock - אחת ממערכות ה-AI החכמות ביותר הקיימות היום.",
        "benefitSecurity": "אבטחה ברמת בנק",
        "benefitSecurityDesc": "הצפנה מקצה לקצה. המידע האישי שלך מוסתר אוטומטית לפני ניתוח ה-AI. אפס שמירת מידע.",
        "benefitFast": "ניתוח AI מהיר",
        "benefitFastDesc": "חוזים פשוטים? תוך פחות מדקה. חוזים מורכבים? מספר דקות. הבינה המלאכותית שלנו סורקת כל סעיף לעומק.",
        "demoTitle": "איך זה עובד?",
        "demoStep1": "העלאת PDF",
        "demoStep1Desc": "העלו את חוזה השכירות שלכם בפורמט PDF. אנחנו תומכים בעברית ואנגלית.",
        "demoStep2": "ניתוח AI",
        "demoStep2Desc": "ה-AI שלנו סורק סיכונים, תנאים לא הוגנים ובעיות משפטיות.",
        "demoStep3": "קבלת תוצאות",
        "demoStep3Desc": "צפו בציון הסיכון, הסברים לבעיות וטיפים למשא ומתן.",
        "featureAI": "🤖 ניתוח AI",
        "featureAIDesc": "מופעל על ידי Amazon Bedrock לניתוח חוזים כמו מומחה משפטי",
        "featurePrivacy": "🔒 פרטיות במקום ראשון",
        "featurePrivacyDesc": "מידע אישי (ת.ז., טלפון, אימייל) מוסתר אוטומטית לפני הניתוח",
        "featureTips": "💡 טיפים חכמים",
        "featureTipsDesc": "קבלו עצות ספציפיות למשא ומתן על כל סעיף בעייתי",
        "footerTagline": "הגנה על החוזה שלך עם בינה מלאכותית מתקדמת",
        "footerSupport": "צריכים עזרה? שלחו לנו מייל:",
        "footerEmail": "rentguard360@gmail.com",
        "footerResponse": "תגובה תוך 24 שעות | הצוות שלנו מוכנים להגן עליכם כמו שאנחנו מגנים על החוזה שלכם",
        "projectName": "💻 פרויקט סיום מחשוב ענן"
    },
    "dashboard": {
        "welcomeSubtitle": "ברוכים הבאים ל-RentGuard 360. העלו ונתחו חוזי שכירות עם בינה מלאכותית.",
        "quickActions": "פעולות מהירות",
        "greeting": {
            "morning": "בוקר טוב",
            "afternoon": "צהריים טובים",
            "evening": "ערב טוב",
            "night": "לילה טוב"
        },
        "totalContracts": "סה\"כ חוזים",
        "analyzed": "נותחו",
        "pending": "ממתינים",
        "highRisk": "סיכון גבוה",
        "uploadContract": "העלאת חוזה",
        "uploadDescription": "העלו חוזה שכירות חדש לניתוח AI",
        "uploadPDF": "העלאת PDF",
        "viewContracts": "צפייה בחוזים",
        "viewDescription": "עיינו בכל החוזים שהעליתם",
        "viewAll": "צפייה בכולם",
        "newFeaturesTitle": "פיצ׳רים חדשים",
        "newFeaturesDesc": "כלים ויכולות נוספות לניהול חוזים יתווספו כאן בקרוב.",
        "howToStart": "איך מתחילים",
        "step1Title": "העלאת חוזה",
        "step1Desc": "גררו ושחררו את חוזה השכירות בפורמט PDF",
        "step2Title": "ניתוח AI",
        "step2Desc": "חוזים פשוטים? תוך פחות מדקה. חוזים מורכבים? מספר דקות. הבינה המלאכותית שלנו סורקת כל סעיף לעומק.",
        "step3Title": "קבלת תובנות",
        "step3Desc": "צפו בסיכונים והצעות למשא ומתן",
        "whyUs": "למה דווקא RentGuard 360?",
        "whyUsSubtitle": "לא סתם עוד צ'אט בוט - מערכת מקצועית שנבנתה במיוחד לניתוח חוזי שכירות",
        "featurePrivacy": "הגנה על הפרטיות",
        "featurePrivacyDesc": "המערכת מזהה ומצנזרת אוטומטית מידע אישי (ת.ז., טלפון, כתובת) לפני שליחה ל-AI. הפרטים שלכם נשארים פרטיים.",
        "featurePrompt": "פרומפט מקצועי מותאם",
        "featurePromptDesc": "בניגוד לשליחה לצ'אט רגיל, המערכת שלנו משתמשת בפרומפט מיוחד שמנתח 70+ גורמי סיכון על פי חוק השכירות הישראלי.",
        "featureScore": "ציון סיכון מבוסס נתונים",
        "featureScoreDesc": "מקבלים ציון אובייקטיבי 0-100 עם פירוט לפי קטגוריות: תנאים כספיים, זכויות הדייר, אחריות ותיקונים ועוד.",
        "featureTips": "טיפים למשא ומתן",
        "featureTipsDesc": "לא רק מזהים בעיות - מקבלים הצעות קונקרטיות לתיקון סעיפים בעייתיים שתוכלו להציג לבעל הדירה.",
        "featureAws": "תשתית ענן מאובטחת",
        "featureAwsDesc": "רץ על AWS עם הצפנה מקצה לקצה. החוזים שלכם לא נשמרים ונמחקים אוטומטית לאחר הניתוח."
    },
    "landing": {
        "heroSubtitleLine": "ההגנה שלך בחוזה השכירות",
        "heroDescription": "ניתוח חוזים חכם מבוסס AI. פשוט גרור את הקובץ וקבל תמונת מצב משפטית בשניות.",
        "startFreeAnalysis": "התחל ניתוח חינם",
        "noCreditCardRequired": "ללא צורך בכרטיס אשראי",
        "carouselPrevious": "הקודם",
        "carouselNext": "הבא",
        "benefitAdvancedAiTitle": "ניתוח AI מתקדם",
        "benefitAdvancedAiDesc": "בינה מלאכותית מתקדמת מזהה סעיפים בעייתיים ומצביעה על סיכונים.",
        "benefitPrivacyTitle": "פרטיות מלאה",
        "benefitPrivacyDesc": "המידע האישי שלך מוסתר אוטומטית לפני הניתוח ומוחזר אחריו.",
        "benefitResultsTitle": "תוצאות בשניות",
        "benefitResultsDesc": "קבל ניתוח מלא של החוזה תוך פחות מדקה, בלי צורך בעורך דין.",
        "liveDemoTitle": "ראה איך זה נראה במציאות",
        "liveDemoSubtitle": "דוגמה לניתוח תיק חוזים של משתמש",
        "clausesTitle": "זיהוי סעיפים בעייתיים",
        "clausesDescription": "המערכת מזהה אוטומטית סעיפים שעלולים לפגוע בזכויותיך ומספקת הסבר בשפה פשוטה.",
        "clausesFeatureLaw": "מבוסס על חוק השכירות 2017",
        "clausesFeatureFixSuggestions": "הצעות תיקון מידיות",
        "clausesFeatureRiskPerCategory": "ציון סיכון לכל קטגוריה",
        "registerPromptTitle": "הרשמה נדרשת",
        "registerPromptDescription": "כדי להעלות ולנתח חוזים, יש להירשם לאתר בחינם.",
        "registerPromptButton": "הרשמה חינם",
        "registerPromptNoCard": "ללא צורך בכרטיס אשראי"
    },
            mockups: {
            dashboard: {
                navDashboard: 'לוח בקרה',
                navContracts: 'חוזים',
                uploadTitle: 'העלאת חוזה שכירות',
                uploadHint: 'פורמט PDF, עד 10MB',
                selectFile: 'בחירת קובץ',
                recentContracts: 'פעילות חוזים אחרונה',
                fileNameApartment: 'חוזה_דירה_תל_אביב.pdf',
                fileNameOffice: 'חוזה_משרד.pdf',
                scoreApartment: '92',
                scoreOffice: '58'
            },
            contracts: {
                analyzedPrefix: 'נותח:',
                lowRisk: 'סיכון נמוך',
                mediumRisk: 'סיכון בינוני',
                highRisk: 'סיכון גבוה',
                propertyAddressLabel: 'כתובת הנכס:',
                landlordNameLabel: 'שם המשכיר:',
                viewAnalysis: 'צפה בניתוח',
                fileNameSafe: 'חוזה_שכירות_תל_אביב.pdf',
                fileNameRisky: 'חוזה_ללא_הגנה.pdf',
                fileNameMedium: 'חידוש_חוזה_2025.pdf',
                addressSafe: 'דיזנגוף 100, תל אביב',
                landlordSafe: 'ישראל ישראלי',
                addressRisky: 'הרצל 45, רמת גן',
                landlordRisky: 'משה כהן',
                addressMedium: 'הנשיא 10, חיפה',
                landlordMedium: 'דוד לוי',
                dateSafe: '22.12.2025',
                dateRisky: '20.12.2025',
                dateMedium: '18.12.2025'
            },
            viewer: {
                mediumRisk: 'סיכון בינוני',
                contractTitle: 'חוזה שכירות לא מוגן',
                clauseRentalPeriod: 'תקופת השכירות',
                okBadge: 'תקין',
                highRisk: 'סיכון גבוה',
                clauseLatePaymentPenalty: 'קנס איחור בתשלום',
                originalClauseText: 'איחור של עד 7 ימים בתשלום שכר הדירה יגרור קנס מיידי של 500 ש"ח לכל יום איחור.',
                legalExplanation: 'הסבר משפטי',
                penaltyExplanation: 'קנס זה גבוה במיוחד וחורג מהמקובל. בתי משפט עשויים לפסול אותו בגין חוסר מידתיות.',
                suggestionLabel: 'הצעה לתיקון: ',
                suggestionText: 'הגבל את הקנס לריבית פיגורים סטנדרטית מיום האיחור הראשון.',
                clauseRentAmount: 'דמי שכירות והצמדה'
            }
        },
    "contracts": {
        "title": "החוזים שלי",
        "subtitle": "ניהול וצפייה בכל חוזי השכירות שלך",
        "activeContracts": "חוזים פעילים",
        "refresh": "רענון",
        "refreshing": "מרענן...",
        "uploadContract": "העלאת חוזה",
        "searchPlaceholder": "חיפוש לפי שם חוזה, נכס או צד...",
        "filterAll": "הכל",
        "filterHighRisk": "בסיכון קריטי",
        "filterPending": "בתהליך ניתוח",
        "noContracts": "אין חוזים עדיין",
        "noContractsDesc": "העלו את חוזה השכירות הראשון שלכם לניתוח",
        "uploadFirst": "העלאת חוזה ראשון",
        "noResults": "לא נמצאו תוצאות",
        "noResultsDesc": "נסה לשנות את מילות החיפוש או הסינון",
        "clearFilters": "נקה סינונים",
        "deleteTitle": "מחיקת חוזה",
        "deleteConfirm": "האם אתה בטוח שברצונך למחוק חוזה זה? פעולה זו לא ניתנת לביטול.",
        "cancel": "ביטול",
        "delete": "מחיקה",
        "deleting": "מוחק...",
        "editTitle": "עריכת פרטים",
        "fileName": "שם קובץ",
        "defaultFileName": "חוזה",
        "propertyAddress": "כתובת הנכס",
        "landlordName": "שם המשכיר",
        "save": "שמירה",
        "saving": "שומר...",
        "loading": "טוען חוזים...",
        "lowRisk": "סיכון נמוך",
        "lowMediumRisk": "סיכון נמוך-בינוני",
        "mediumRisk": "סיכון בינוני",
        "highRisk": "סיכון גבוה",
        "analyzed": "הושלם",
        "pendingAnalysis": "ממתין",
        "notSpecified": "לא צוין",
        "exportWord": "ייצוא Word",
        "viewAnalysis": "צפייה בניתוח",
        "sortBy": "מיון לפי:",
        "sortDate": "תאריך",
        "sortScore": "סיכון",
        "sortNewest": "החדשים קודם",
        "sortOldest": "הישנים קודם",
        "sortHighRiskFirst": "סיכון גבוה קודם",
        "sortLowRiskFirst": "סיכון נמוך קודם",
        "uploadDate": "הועלה ב-",
        "riskScore": "מדד סיכון",
        "analysisFailed": "הניתוח נכשל",
        "processingData": "מעבד סעיפי התקשרות...",
        "untitledContract": "חוזה ללא שם",
        "analyzedPrefix": "נותח:",
        "statusTimedOutRetry": "תם הזמן - נסה שוב",
        "statusAnalysisFailed": "שגיאה בניתוח",
        "statusFailedShort": "ניתוח נכשל",
        "statusPendingShort": "ממתין...",
        "menuExportTrigger": "ייצוא",
        "menuExportTitle": "ייצוא דוח הניתוח",
        "menuDownloadTitle": "הורדה",
        "menuExportWordTitle": "ייצוא דוח ניתוח (Word)",
        "menuExportWordNote": "ייצוא כקובץ docx (Word), עריך ומומלץ לעברית",
        "menuShareTrigger": "שיתוף",
        "menuShareTitle": "שיתוף דוח הניתוח",
        "editButtonTitle": "עריכה",
        "deleteButtonTitle": "מחיקה",
        "deleteFailed": "מחיקה נכשלה",
        "saveFailed": "שמירה נכשלה",
        "exportFailed": "ייצוא נכשל",
        "shareFailed": "השיתוף נכשל",
        "exportPdfStarted": "קובץ PDF ירד למחשב (סיכום באנגלית)",
        "exportWordStarted": "קובץ docx (Word) ירד למחשב (עריך)",
        "shareSheetOpened": "חלון השיתוף נפתח עבור PDF",
        "fileNamePlaceholder": "שם הקובץ",
        "propertyAddressPlaceholder": "כתובת",
        "landlordNamePlaceholder": "משכיר",
        "pageOf": "עמוד {current} מתוך {total}"
    },
    "upload": {
        "title": "העלאת חוזה",
        "subtitle": "העלו את חוזה השכירות שלכם לניתוח AI",
        "dragDrop": "שחררו את ה-PDF כאן",
        "or": "או לחצו לבחירת קובץ",
        "selectFile": "בחירת קובץ",
        "scanWithCamera": "סריקה באמצעות מצלמה",
        "selectedFiles": "קובץ שנבחר",
        "maxSize": "גודל מקסימלי: 5MB | PDF בלבד",
        "termsLabel": "אני מאשר/ת שקראתי והבנתי את ",
        "termsLinkTerms": "תנאי השימוש",
        "termsLinkAnd": " ו",
        "termsLinkPrivacy": "מדיניות הפרטיות",
        "uploadBtn": "העלאת חוזה לניתוח",
        "uploading": "מעלה...",
        "readyForAnalysis": "מוכן לניתוח",
        "fileNameLabel": "שם הקובץ",
        "deleteFile": "מחיקת קובץ",
        "fileSizeByte": "בייט",
        "complete": "הושלם!",
        "uploadSuccess": "ההעלאה הצליחה!",
        "analyzing": "ה-AI מנתח את החוזה שלכם (עד 2 דקות)...",
        "uploadedToServer": "✓ החוזה הועלה לשרת",
        "analysisStarted": "✓ הניתוח התחיל",
        "viewMyContracts": "צפייה בחוזים שלי",
        "uploadAnother": "העלאת חוזה נוסף",
        "uploadSuccessTitle": "החוזה הועלה בהצלחה!",
        "uploadSuccessMessage": "תוצאות הניתוח של החוזה שלך ישלחו לאימייל שלך",
        "goToContracts": "עבור לחוזים שלי",
        "contractDetails": "פרטי החוזה (אופציונלי)",
        "propertyAddress": "כתובת הנכס",
        "addressPlaceholder": "רחוב ראשי 123, עיר",
        "landlordName": "שם המשכיר",
        "landlordPlaceholder": "ישראל ישראלי",
        "contractName": "שם החוזה",
        "pdfOnly": "רק קבצי PDF מותרים",
        "fileTooLarge": "גודל הקובץ חייב להיות פחות מ-5MB",
        "fileTooSmall": "הקובץ קטן מדי - ייתכן שהוא ריק או פגום",
        "fileNameTooLong": "שם הקובץ ארוך מדי (מקסימום 100 תווים)",
        "fileNameRequired": "יש להזין שם קובץ לפני ההעלאה",
        "termsRequired": "יש לאשר את תנאי השימוש ומדיניות הפרטיות לפני העלאה",
        "validationToastTitle": "לא ניתן להתחיל העלאה",
        "uploadFailed": "ההעלאה נכשלה. נסו שוב.",
        "serverTemporaryError": "השרת עמוס כרגע. המערכת ניסתה שוב אוטומטית ולא הצליחה. נסו שוב בעוד כמה שניות."
    },
    "analysis": {
        "title": "ניתוח חוזה",
        "backToContracts": "חזרה לחוזים",
        "summary": "סיכום",
        "scoreBreakdown": "פירוט הציון",
        "aggregateIntelligence": "אינטליגנציה משוקללת",
        "overallHealth": "דירוג החוזה",
        "overallRiskScore": "ציון סיכון כולל",
        "refresh": "רענון",
        "export": "ייצוא",
        "quickActions": "פעולות מהירות",
        "actionRequired": "דורש התייחסות",
        "contractMetadata": "פרטי החוזה",
        "deepAnalysisAndClauses": "ניתוח מעמיק וסעיפים",
        "theIssue": "הבעיה",
        "negotiationStrategy": "אסטרטגיית משא ומתן",
        "issues": "בעיות שזוהו",
        "noIssues": "לא נמצאו בעיות בחוזה זה",
        "original": "מקור",
        "problem": "הבעיה",
        "recommendation": "המלצה",
        "copyFix": "העתק תיקון",
        "copied": "הועתק!",
        "askAI": "שאל את ה-AI",
        "loading": "טוען ניתוח...",
        "analyzing": "מנתח את החוזה...",
        "notContract": "מסמך זה לא נראה כחוזה שכירות",
        "shareButtonCreating": "יוצר קישור...",
        "shareButtonHide": "הסתר קישור שיתוף",
        "shareButtonShow": "הצג קישור שיתוף פעיל",
        "shareButtonCreate": "יצירת לינק שיתוף",
        "toastSavingTitle": "שומר שינויים",
        "toastSavingMessage": "המערכת שומרת את העריכות שלך כעת.",
        "toastSavedTitle": "השינויים נשמרו",
        "toastSavedMessage": "השינויים נשמרו אוטומטית בענן.",
        "toastSaveFailedTitle": "שמירה נכשלה",
        "toastSaveFailedMessage": "לא הצלחנו לשמור את העריכות. נסה שוב בעוד רגע.",
        "defaultReportName": "דוח_ניתוח",
        "exportWordStarted": "קובץ docx (Word) ירד למחשב",
        "exportPdfStarted": "קובץ PDF ירד למחשב",
        "missingShareContractId": "לא נמצא מזהה חוזה לשיתוף",
        "sharePanelHidden": "פאנל השיתוף הוסתר",
        "sharePanelShown": "קישור שיתוף פעיל מוצג",
        "shareCreated": "קישור שיתוף נוצר. אפשר להעתיק או לשתף מהפאנל.",
        "shareCreateFailed": "שגיאה ביצירת קישור שיתוף",
        "shareCopiedTitle": "הקישור הועתק בהצלחה",
        "shareCopiedMessage": "אפשר להדביק ולשתף בכל אפליקציה.",
        "shareCopyFailed": "שגיאה בהעתקת הקישור",
        "shareNativeTitle": "חוזה משותף מ-RentGuard 360",
        "shareNativeText": "צפייה בחוזה (קריאה בלבד):",
        "shareFailed": "שגיאה בשיתוף הקישור",
        "shareRevokedTitle": "קישור השיתוף בוטל",
        "shareRevokedMessage": "הקישור הישן כבר לא פעיל.",
        "shareRevokeFailed": "שגיאה בביטול קישור שיתוף",
        "errors": {
            "notReadyTitle": "הניתוח עדיין לא מוכן",
            "notReadyMessage": "החוזה שלך עדיין בתהליך. בודקים שוב אוטומטית...",
            "failedTitle": "הניתוח נכשל",
            "failedMessage": "אירעה שגיאה בניתוח החוזה. הצוות עודכן. אפשר לנסות להעלות מחדש.",
            "timeoutTitle": "זמן הניתוח הסתיים",
            "timeoutMessage": "הניתוח לוקח יותר מהרגיל. נסו שוב בעוד כמה דקות.",
            "genericTitle": "משהו השתבש",
            "genericMessage": "לא הצלחנו לטעון את תוצאות הניתוח. נסו שוב."
        },
        "shareExpiryDefault": "בתוקף ל-7 ימים",
        "shareExpiryExpired": "פג תוקף",
        "shareExpiryDays": "בתוקף לעוד {days} ימים",
        "technicalDetails": "פרטים טכניים",
        "tryAgain": "נסה שוב",
        "contractDocument": "מסמך חוזה",
        "analysisComplete": "הניתוח הושלם.",
        "exportMenuTitle": "ייצוא דוח הניתוח",
        "exportMenuDownload": "הורדה",
        "exportMenuWordTitle": "ייצוא דוח ניתוח (Word)",
        "exportMenuFullContractWordTitle": "ייצוא חוזה מלא (Word)",
        "exportMenuWordNote": "(ייצוא כקובץ docx (Word), ניתן לעריכה מלאה)",
        "exportMenuPdfTitle": "הורדה PDF - דוח ניתוח",
        "exportMenuPdfNote": "(תצוגה ושיתוף מהיר, אנגלית בלבד)",
        "exportMenuShare": "שיתוף",
        "fullContractExportNotReady": "ייצוא חוזה מלא לא זמין כרגע. נסו שוב אחרי מעבר ללשונית החוזה המלא.",
        "fullContractTab": "החוזה המלא",
        "points": "נקודות",
        "legalBasis": "בסיס משפטי",
        "whyItMatters": "למה זה חשוב?",
        "negotiationTip": "טיפ למשא ומתן",
        "notRentalTitle": "זה לא חוזה שכירות",
        "notRentalDescription": "המסמך שהועלה אינו נראה כחוזה שכירות תקין. אנא העלו חוזה שכירות למגורים בפורמט PDF.",
        "noIssuesDescription": "חוזה זה נראה תקין ללא דגלים אדומים משמעותיים.",
        "notRentalContentDescription": "המסמך שהועלה אינו נראה כחוזה שכירות תקין. לא ניתן להציג את תוכן החוזה.",
        "originalClause": "הסעיף המקורי",
        "recommendedClause": "הנוסח המומלץ",
        "exportEditedWord": "ייצוא כקובץ docx (Word)",
        "resetEditsTitle": "איפוס כל העריכות שביצעת",
        "resetEdits": "איפוס עריכות",
        "secureShareLink": "קישור שיתוף מאובטח",
        "shareLinkAria": "קישור שיתוף",
        "copyLink": "העתק קישור",
        "sharing": "משתף...",
        "shareViaApps": "שתף באפליקציות",
        "openLink": "פתח קישור",
        "revoking": "מבטל קישור...",
        "revokeLink": "ביטול קישור"
    },
    "contractView": {
        "consultError": "שגיאה בקבלת הסבר. נסה שוב.",
        "editedContractFileName": "חוזה_שכירות_ערוך",
        "expand": "הרחב חוזה",
        "collapse": "כווץ מסמך",
        "contractTitle": "חוזה שכירות בלתי מוגנת",
        "contractSubtitle": "נערך ונחתם ביום ________________",
        "ocrDisclaimerTitle": "הבהרה: הטקסט מבוסס OCR",
        "ocrDisclaimerBody1": "החוזה המוצג חולץ אוטומטית מקובץ ה-PDF שהעלית. במסמכים סרוקים (במיוחד מצילום), עלולים להופיע שיבושי טקסט, רווחים חריגים או פירוק טבלאות.",
        "ocrDisclaimerBody2": "מומלץ לבצע תיקונים נקודתיים בעורך ולייצא לגרסת Word מתוקנת (DOCX). לפני החלטות משפטיות, יש להשוות תמיד מול המסמך המקורי.",
        "showOnlyProblemClauses": "הצג רק סעיפים בעייתיים",
        "clausesCountSuffix": "סעיפים",
        "issuesCountSuffix": "בעיות",
        "editedCountSuffix": "נערכו",
        "noIssuesFound": "לא נמצאו בעיות!",
        "noTextFound": "לא נמצא טקסט.",
        "getClauseExplanation": "קבל הסבר על הסעיף",
        "edit": "עריכה",
        "aiExplanation": "הסבר AI",
        "fixSuggestion": "הצעה לתיקון",
        "signaturesTitle": "חתימות",
        "landlord": "המשכיר",
        "tenant": "השוכר",
        "namePlaceholder": "שם: ________________",
        "idPlaceholder": "ת.ז.: ________________",
        "datePlaceholder": "תאריך: ________________",
        "scrollUp": "גלול למעלה",
        "scrollToSignatures": "גלול לחתימות",
        "up": "למעלה",
        "toSignatures": "לחתימות",
        "editClause": "עריכת סעיף",
        "originalClauseLabel": "סעיף מקורי:",
        "aiFixSuggestionLabel": "הצעת תיקון AI",
        "applySuggestion": "החל הצעה",
        "editLabel": "עריכה:",
        "editPlaceholder": "ערוך את הסעיף כאן...",
        "finishEditing": "סיום עריכה",
        "revertToOriginal": "חזור למקור",
        "cancel": "ביטול",
        "confirmRevertTitle": "אישור ביטול",
        "confirmRevertMessage": "האם אתה בטוח שברצונך לבטל את העריכה ולחזור לטקסט המקורי?",
        "confirmRevertYes": "כן, בטל עריכה",
        "confirmRevertNo": "לא, השאר",
        "clearAllTitle": "מחיקת כל העריכות",
        "clearAllMessage": "האם אתה בטוח שברצונך למחוק את כל העריכות שביצעת בחוזה זה?",
        "irreversibleWarning": "פעולה זו אינה הפיכה.",
        "clearAllYes": "כן, מחק הכל"
    },
    "score": {
        "lowRisk": "סיכון נמוך",
        "lowMediumRisk": "סיכון נמוך-בינוני",
        "mediumRisk": "סיכון בינוני",
        "mediumHighRisk": "סיכון בינוני-גבוה",
        "highRisk": "סיכון גבוה",
        "financialTerms": "תנאים כספיים",
        "tenantRights": "זכויות הדייר",
        "terminationClauses": "סיום ויציאה",
        "liabilityRepairs": "אחריות ותיקונים",
        "legalCompliance": "עמידה בחוק"
    },
    "contact": {
        "title": "אנחנו כאן בשבילך",
        "subtitle": "יש לך שאלות לגבי ניהול השכירות שלך? הצוות המקצועי של RentGuard זמין לסייע לך בכל נושא משפטי או טכני.",
        "successTitle": "ההודעה נשלחה בהצלחה!",
        "successMessage": "נחזור אליכם בהקדם האפשרי.",
        "sendAnother": "שליחת הודעה נוספת",
        "fullName": "שם מלא",
        "fullNamePlaceholder": "ישראל ישראלי",
        "phone": "טלפון",
        "phonePlaceholder": "054-7820346",
        "email": "אימייל",
        "emailPlaceholder": "name@company.com",
        "message": "הודעה",
        "messagePlaceholder": "איך נוכל לעזור לך היום?",
        "sending": "שולח...",
        "sendMessage": "שלח הודעה",
        "contactDetails": "פרטי התקשרות",
        "address": "כתובתנו",
        "addressValue": "רחוב רוטשילד 22, תל אביב, משרד עורכי דין",
        "emailLabel": "דואר אלקטרוני",
        "emailValue": "rentguard360@gmail.com",
        "phoneLabel": "טלפון",
        "phoneValue": "050-0000000",
        "mapPopupText": "RentGuard-360 תל אביב",
        "joinText": "הצטרפו לאלפי בעלי נכסים שבוחרים בשקט נפשי עם RentGuard.",
        "defaultSubject": "פנייה חדשה מדף צור קשר",
        "errorMessage": "שליחת ההודעה נכשלה. נסו שוב.",
        "secureCommunication": "תקשורת מאובטחת",
        "fastResponse": "מענה תוך 24 שעות",
        "notCustomerYet": "עדיין לא מנויים?",
        "registerNowFree": "הירשמו עכשיו בחינם",
        "registerFreePlan": "הרשמה לקבלת גרסה חינמית",
        "orOption": "או",
        "toStartAnalyzing": "כדי להתחיל לנתח חוזים"
    },
    "methodology": {
        "title": "איך מחושב הציון?",
        "intro1": "הציון הוא 5 קטגוריות × 20 נק׳ (סה״כ 100). מורידים נקודות לפי חומרה.",
        "intro2": "תקרה: קטגוריה לא יורדת מתחת ל-0 ⇒ מקסימום 20 נק׳ ירידה לכל קטגוריה (לכן סכום הקנסות יכול להיות גבוה יותר מהירידה בפועל בציון).",
        "high": "גבוה",
        "medium": "בינוני",
        "low": "נמוך",
        "pts": "נקודות",
        "categoriesHeader": "5 קטגוריות × 20 נקודות = 100",
        "catFinancial": "תנאים פיננסיים",
        "catFinancialDesc": "ערבות, קנסות איחור, ביטוח",
        "catRights": "זכויות השוכר",
        "catRightsDesc": "כניסה לדירה, סאבלט, פרטיות",
        "catTermination": "סיום חוזה",
        "catTerminationDesc": "תקופת הודעה, יציאה מוקדמת",
        "catLiability": "אחריות ותיקונים",
        "catLiabilityDesc": "תיקונים, בלאי סביר",
        "catLegal": "תאימות חוקית",
        "catLegalDesc": "התאמה לחוק השכירות 2017",
        "legalSource": "מבוסס על חוק השכירות והשאילה (תיקון 2017) - סעיפים 25א-25טו"
    },
    "footer": {
        "tagline": "פלטפורמת ניתוח חוזי שכירות מבוססת AI",
        "benefits": "פרטיות מלאה | ניתוח מהיר ומאובטח | טיפים למשא ומתן | תשתית ענן מאובטחת",
        "project": "פרויקט סיום מחשוב ענן",
        "copyright": "© RentGuard 360 {year} . כל הזכויות שמורות.",
        "legalTagline": "הגנה משפטית חכמה לכל חוזה שכירות.",
        "contactSectionTitle": "צור קשר",
        "quickLinksTitle": "ניווט מהיר",
        "personalAreaTitle": "אזור אישי",
        "legalSectionTitle": "משפטי",
        "termsLink": "תנאי שימוש",
        "privacyLink": "מדיניות פרטיות",
        "contactLink": "צור קשר",
        "builtBy": "נבנה ע\"י",
        "andSeparator": " ו"
    },
    "chat": {
        "title": "RentGuard 360 Chat",
        "open": "פתיחת צ׳אט חוזה",
        "close": "סגירת צ׳אט",
        "contractLabel": "חוזה",
        "selectContract": "בחרו חוזה",
        "loadingContracts": "טוען חוזים...",
        "emptySelectContract": "בחרו חוזה כדי להתחיל לשאול שאלות.",
        "emptyStart": "אין עדיין הודעות. שאלו את השאלה הראשונה.",
        "scope": "עונה לפי החוזה הנבחר בלבד. לא מהווה ייעוץ משפטי.",
        "quickPromptsLabel": "הצעות מהירות לשאלות",
        "promptHighRisk": "מה 3 הסיכונים הכי גבוהים בחוזה?",
        "promptPets": "האם מותר להכניס כלב או חיית מחמד?",
        "promptTermination": "מה תנאי סיום החוזה והאם יש קנסות?",
        "inputPlaceholder": "...שאלו על סעיפים, תשלומים, חיות מחמד, סיום חוזה",
        "send": "שלח שאלה",
        "clear": "נקה היסטוריה",
        "clearShort": "נקה",
        "clearConfirm": "למחוק את כל היסטוריית הצ׳אט של החוזה שנבחר? לא ניתן לשחזר את ההודעות.",
        "clearSuccessTitle": "היסטוריית הצ׳אט נוקתה",
        "clearSuccessMessage": "נמחקו {count} הודעות מההיסטוריה.",
        "clearSuccessMessageGeneric": "היסטוריית הצ׳אט נוקתה בהצלחה.",
        "copy": "העתק",
        "copied": "הועתק",
        "you": "אתם",
        "assistant": "עוזר AI",
        "sourceContract": "מבוסס על החוזה",
        "sourceGeneral": "הכוונה כללית (לא ציטוט ישיר)",
        "evidenceTitle": "ציטוטים מהחוזה",
        "thinking": "ה-AI מנתח את החוזה",
        "tip": "טיפ: שאלו על סעיפים, תשלומים או סיום חוזה.",
        "disclaimer": "ה-AI יכול לטעות. בדקו פרטים חשובים בחוזה.",
        "showNotice": "הצג מידע",
        "hideNotice": "הסתר מידע",
        "noAnswer": "לא נוצרה תשובה.",
        "dismissHint": "סגור הודעה",
        "hints": {
            "rateLimit": "הגעתם כרגע למגבלת שאלות זמנית בגלל עומס. חכו כדקה ונסו שוב."
        },
        "rateLimitRetryIn": "נסו שוב בעוד {seconds} שניות.",
        "errors": {
            "loadContracts": "טעינת החוזים נכשלה. נסו שוב.",
            "loadHistory": "טעינת היסטוריית הצ׳אט נכשלה. נסו שוב.",
            "selectContract": "בחרו חוזה לפני שליחת שאלה.",
            "askFailed": "לא הצלחתי לקבל תשובה כרגע. נסו שוב.",
            "clearFailed": "ניקוי ההיסטוריה נכשל. נסו שוב."
        }
    },
    "common": {
        "loading": "טוען...",
        "error": "שגיאה",
        "success": "הצלחה",
        "user": "משתמש",
        "cancel": "ביטול",
        "confirm": "אישור",
        "ok": "אישור",
        "clearSelections": "נקה בחירות",
        "comingSoon": "בקרוב"
    },
    "errorBoundary": {
        "title": "משהו השתבש",
        "message": "משהו השתבש. אנא נסו לרענן את העמוד.",
        "reload": "רענון העמוד",
        "details": "פרטי שגיאה"
    },
    "languageToggle": {
        "switchToEnglish": "Switch to English",
        "switchToHebrew": "עבור לעברית",
        "heLabel": "עב",
        "enLabel": "EN"
    },
    "recommendationCard": {
        "defaultTitle": "הצעה לתיקון",
        "applied": "הוחל",
        "revertTitle": "בטל שינויים וחזור למקור",
        "revert": "בטל",
        "applyFix": "החל תיקון"
    },
    "notifications": {
        "bundleRequiredTitle": "יש לבחור חבילה תחילה",
        "bundleRequiredMessage": "כדי להמשיך, בחרו חבילה בעמוד התוכניות.",
        "contactSentTitle": "ההודעה נשלחה",
        "contactSentMessage": "קיבלנו את פנייתכם ונחזור אליכם בקרוב.",
        "contactFailedTitle": "שליחת ההודעה נכשלה",
        "contactFailedMessage": "לא הצלחנו לשלוח את ההודעה כרגע. נסו שוב.",
        "uploadFailedTitle": "העלאת החוזה נכשלה",
        "analysisReadyTitle": "הניתוח הושלם",
        "analysisReadyMessage": "החוזה נותח בהצלחה ואפשר לצפות בתוצאות.",
        "adminUserEnabledTitle": "המשתמש הופעל",
        "adminUserEnabledMessage": "המשתמש {user} הופעל בהצלחה.",
        "adminUserEnableFailedTitle": "הפעלת משתמש נכשלה",
        "adminUserEnableFailedMessage": "לא הצלחנו להפעיל את המשתמש {user}.",
        "adminUserDisabledTitle": "המשתמש הושעה",
        "adminUserDisabledMessage": "המשתמש {user} הושעה.",
        "adminUserDisableFailedTitle": "השעיית משתמש נכשלה",
        "adminUserDisableFailedMessage": "לא הצלחנו להשעות את המשתמש {user}.",
        "adminUserDeletedTitle": "המשתמש נמחק",
        "adminUserDeletedMessage": "המשתמש {user} נמחק לצמיתות.",
        "adminUserDeleteFailedTitle": "מחיקת משתמש נכשלה",
        "adminUserDeleteFailedMessage": "לא הצלחנו למחוק את המשתמש {user}."
    },
    "account": {
        "deleteAccount": "מחק חשבון",
        "deleteAccountDescription": "מחיקת החשבון שלך לצמיתות כולל כל החוזים שלך",
        "deleteConfirmTitle": "האם אתה בטוח?",
        "deleteConfirmMessage": "פעולה זו תמחק את החשבון שלך לצמיתות, כולל:",
        "deleteConfirmItem1": "• כל החוזים שלך",
        "deleteConfirmItem2": "• כל הניתוחים שלך",
        "deleteConfirmItem3": "• נתוני הפרופיל שלך",
        "deleteConfirmWarning": "פעולה זו לא ניתנת לביטול!",
        "typeDeleteToConfirm": "הקלד DELETE כדי לאשר:",
        "typeDeleteToConfirmError": "יש להקליד DELETE כדי לאשר",
        "deleteAccountSuccess": "החשבון נמחק בהצלחה",
        "deleteAccountError": "שגיאה במחיקת החשבון",
        "deletingAccount": "מוחק חשבון...",
        "deletingContracts": "מוחק חוזים..."
    },
    "settings": {
        "title": "מרכז בקרה",
        "subtitle": "ניהול הפרופיל, הגדרות התצוגה והאבטחה של החשבון שלך במקום אחד מסודר.",
        "activeAccount": "חשבון פעיל",
        "profileFallbackUser": "משתמש/ת",
        "appearanceTitle": "תצוגה",
        "appearanceDesc": "החלפה בין בהיר לכהה",
        "darkMode": "מצב כהה",
        "lightMode": "מצב בהיר",
        "manageBilling": "ניהול חיובים",
        "chatBehaviorTitle": "התנהגות צ׳אט",
        "chatBehaviorDesc": "קובע אם צ׳אט החוזה ייפתח אוטומטית בעת כניסה לעמוד ניתוח חוזה.",
        "chatAutoOpenOn": "פתיחה אוטומטית: פעילה",
        "chatAutoOpenOff": "פתיחה אוטומטית: כבויה",
        "alertsTitle": "התראות",
        "alertsDesc": "עדכונים נשלחים לכתובת האימייל המאומתת שלך.",
        "alertsTip": "בדוק ספאם אם חסר מייל",
        "systemInfoTitle": "אודות המערכת",
        "versionLabel": "גרסה",
        "builtByLabel": "צוות פיתוח",
        "devTeam": "רון, מוטי ועידן",
        "deleteAccountTitle": "מחיקת חשבון",
        "deleteAccountDesc": "פעולה זו תמחק לצמיתות את החשבון שלך ואת כל החוזים המקושרים אליו. לא ניתן לבטל פעולה זו."
    },
    "admin": {
        "title": "לוח בקרה למנהל",
        "accessDenied": "גישה נדחתה",
        "noPermission": "אין לך הרשאות מנהל",
        "statsTab": "סטטיסטיקות",
        "usersTab": "משתמשים",
        "stripeTab": "תובנות Stripe",
        "tryAgain": "נסה שוב",
        "contractsSection": "חוזים",
        "totalContracts": "סה״כ חוזים",
        "analyzed": "נותחו",
        "pending": "ממתינים",
        "failed": "נכשלו",
        "analysisSection": "ניתוח",
        "avgRiskScore": "ציון סיכון ממוצע",
        "avgAnalysisTime": "זמן ניתוח ממוצע",
        "usersSection": "משתמשים",
        "totalUsers": "סה״כ משתמשים",
        "activeUsers30": "פעילים (30 יום)",
        "updatedAt": "עודכן",
        "seconds": "שניות",
        "minutes": "דקות",
        "days": "ימים",
        "thisMonth": "החודש",
        "thisYear": "השנה",
        "analyzedOverTime": "חוזים שנותחו לאורך זמן",
        "userRegistrations": "רישום משתמשים לאורך זמן",
        "allTime": "הכל",
        "noData": "אין נתונים להצגה",
        "searchPlaceholder": "חפש לפי אימייל או שם...",
        "search": "חפש",
        "email": "אימייל",
        "name": "שם",
        "userLabel": "משתמש",
        "status": "סטטוס",
        "joined": "הצטרף",
        "actions": "פעולות",
        "noUsers": "לא נמצאו משתמשים",
        "active": "פעיל",
        "pendingVerification": "ממתין לאימות",
        "suspended": "מושעה",
        "disable": "השעה",
        "enable": "הפעל",
        "delete": "מחק",
        "copyEmail": "העתק אימייל",
        "copied": "הועתק",
        "copySuccessTitle": "האימייל הועתק",
        "copySuccessMessage": "כתובת האימייל הועתקה ללוח.",
        "copyFailed": "לא ניתן להעתיק אימייל. אפשר לסמן ולהעתיק ידנית.",
        "advancedFilter": "פילטר מתקדם",
        "authProvider": "ספק התחברות",
        "package": "חבילה",
        "emailPassword": "אימייל",
        "allUsers": "כל המשתמשים",
        "activeOnly": "פעילים בלבד",
        "disabledOnly": "מושעים בלבד",
        "none": "ללא",
        "pending": "ממתין",
        "expired": "פג תוקף",
        "packageNone": "ללא חבילה",
        "packageExpired": "חבילה שפג תוקפה",
        "showingUsers": "מציג {count} משתמשים",
        "confirmDisable": "האם אתה בטוח שברצונך להשעות משתמש זה?",
        "confirmDisableTitle": "השעיית משתמש",
        "confirmDelete": "האם אתה בטוח שברצונך למחוק משתמש זה?",
        "confirmDeleteTitle": "מחיקת משתמש",
        "confirmDeleteFinal": "פעולה זו אינה ניתנת לביטול! המשתמש יימחק לצמיתות. האם להמשיך?",
        "confirmDeleteFinalTitle": "⚠️ אישור סופי",
        "confirmDeleteBtn": "כן, מחק לצמיתות",
        "selectYear": "בחר שנה",
        "userDeleted": "המשתמש נמחק בהצלחה",
        "dashboard": "לוח בקרה",
        "analytics": "אנליטיקות",
        "settings": "הגדרות",
        "administrator": "מנהל",
        "analyticsDescription": "ניתוח חוזים מפורט ותובנות סיכון",
        "radarChart": "רדאר סיכונים",
        "radarChartDesc": "ניתוח סיכונים ב-5 צירים בקרוב",
        "sparklines": "גרפי מגמות",
        "sparklinesDesc": "גרפי מגמות מיני בקרוב",
        "riskBreakdown": "פירוט סיכונים",
        "riskBreakdownDesc": "ניתוח קטגוריות מפורט",
        "riskDistribution": "התפלגות סיכונים",
        "commonIssues": "בעיות נפוצות בחוזים",
        "code": "קוד",
        "issue": "בעיה",
        "count": "כמות",
        "noIssuesYet": "עדיין לא נמצאו בעיות - העלה חוזים לניתוח",
        "stripeInsightsTitle": "תובנות Stripe וחיובים",
        "stripeInsightsSubtitle": "תמונה מלאה של חיובים, המרות, הכנסות ונתוני חבילות מהמערכת",
        "generatedAt": "עודכן בתאריך",
        "availableBalance": "יתרה זמינה",
        "pendingBalance": "יתרה בהמתנה",
        "charges30Days": "חיובים ב-30 יום",
        "disputes30Days": "מחלוקות (30 יום)",
        "intents30Days": "Payment Intents ב-30 יום",
        "successRate": "שיעור הצלחה",
        "refundedCharges": "חיובים שהוחזרו",
        "revenue": "הכנסות",
        "avgOrderValue": "ממוצע עסקה",
        "activeSubscribers": "מנויים פעילים",
        "transactions": "עסקאות",
        "bundleDistribution": "התפלגות חבילות",
        "recentTransactions": "עסקאות אחרונות",
        "bundle": "חבילה",
        "amount": "סכום",
        "currency": "מטבע",
        "country": "מדינה",
        "stripeFeatures": "יכולות Stripe",
        "chargesEnabled": "חיובים פעילים",
        "payoutsEnabled": "העברות פעילות",
        "enabled": "פעיל",
        "disabled": "כבוי",
        "refundAmount30Days": "סכום החזרים (30 יום)",
        "intentToChargeConversion": "יחס המרה מכוונה לחיוב",
        "paymentMethodMix": "פירוט אמצעי תשלום",
        "noPaymentSignals": "עדיין אין נתוני אמצעי תשלום.",
        "failedCharges30Days": "חיובים שנכשלו (30 יום)",
        "disputeRate": "שיעור מחלוקות",
        "refundRate": "שיעור החזרים",
        "chargesToIntents": "חיובים / כוונות חיוב",
        "topCurrencies": "מטבעות מובילים",
        "noCurrencyAmounts": "עדיין אין נתוני מטבעות.",
        "stripeStatusError": "לא ניתן למשוך נתוני Stripe כרגע",
        "settingsDescription": "הגדרות מערכת והעדפות",
        "notifications": "התראות",
        "notificationsDesc": "הגדרת התראות אימייל ופוש",
        "security": "אבטחה",
        "securityDesc": "אימות ובקרת גישה",
        "dataRetention": "שמירת מידע",
        "dataRetentionDesc": "הגדרות אחסון וגיבוי חוזים",
        "emailTemplates": "תבניות אימייל",
        "emailTemplatesDesc": "התאמה אישית של אימיילים",
        "comingSoon": "בקרוב"
    },
    "pricing": {
        "title": "בחרו את החבילה שלכם",
        "subtitle": "בחרו את החבילה המתאימה ביותר לצרכים שלכם והתחילו לנתח חוזי שכירות עם בינה מלאכותית",
        "currentPlan": "החבילה הנוכחית:",
        "scansLeft": "סריקות נותרו",
        "unlimited": "ללא הגבלה",
        "mostPopular": "הפופולרית ביותר",
        "yourPlan": "החבילה שלך",
        "currentPlanBtn": "החבילה הנוכחית",
        "getStarted": "התחילו בחינם",
        "subscribe": "רכישה",
        "buyMoreScans": "קנה עוד סריקות",
        "free": "חינם",
        "single": "חד פעמית",
        "basic": "בסיס",
        "pro": "פרו",
        "month": "חודש",
        "scans": "סריקות",
        "unlimitedScans": "15 סריקות",
        "freeDesc": "נסו את המערכת ללא התחייבות",
        "singleDesc": "בדקו חוזה בודד בצורה מעמיקה",
        "basicDesc": "מושלם לשימוש מזדמן",
        "proDesc": "המשתלמת ביותר למשתמשים קבועים",
        "featuresFree": [
            "סריקת חוזה אחת",
            "ניתוח AI מלא",
            "ציון סיכון מפורט",
            "ניסיון ללא התחייבות"
        ],
        "featuresSingle": [
            "סריקת חוזה אחת",
            "ניתוח AI מלא",
            "ציון סיכון מפורט",
            "ייצוא PDF ו-Word"
        ],
        "featuresBasic": [
            "5 סריקות חוזים",
            "ניתוח AI מלא",
            "ציון סיכון מפורט",
            "טיפים למשא ומתן",
            "ייצוא PDF ו-Word"
        ],
        "featuresPro": [
            "15 סריקות חוזים",
            "ניתוח AI מלא",
            "ציון סיכון מפורט",
            "טיפים למשא ומתן",
            "ייצוא PDF ו-Word",
            "תמיכה בעדיפות"
        ]
    },
    "checkout": {
        "title": "השלמת רכישה",
        "backToPricing": "חזרה לחבילות",
        "orderSummary": "סיכום הזמנה",
        "plan": "חבילה",
        "scans": "סריקות",
        "total": "סה״כ לתשלום",
        "paymentMethod": "אמצעי תשלום",
        "cardDetails": "פרטי כרטיס אשראי",
        "pay": "שלם",
        "processing": "מעבד תשלום...",
        "securedByStripe": "תשלום מאובטח באמצעות Stripe",
        "testMode": "מצב בדיקה — השתמש בכרטיס",
        "termsLabel": "אני מאשר/ת את ",
        "termsLinkTerms": "תנאי השירות",
        "termsJoin": " ו",
        "termsLinkPrivacy": "מדיניות הפרטיות",
        "termsLinkText": "תנאי השירות ומדיניות הפרטיות",
        "termsDisclaimer": ". אני מבין/ה שמדובר ברכישה חד-פעמית של חבילת סריקות ושלא יתבצע חיוב חוזר.",
        "termsRequired": "יש לאשר את תנאי השירות כדי להמשיך"
    },
    "paymentSuccess": {
        "title": "התשלום הושלם בהצלחה",
        "freeActivated": "החבילה החינמית שלך הופעלה. תוכלו להתחיל לסרוק חוזים עכשיו.",
        "paymentCompleted": "התשלום עבר בהצלחה והחבילה שלך עודכנה.",
        "plan": "חבילה",
        "amount": "סכום",
        "hint": "תוכלו להתחיל מיד לסרוק חוזי שכירות.",
        "goToDashboard": "לוח בקרה",
        "uploadContract": "העלאת חוזה"
    },
    "subscription": {
        "myPlan": "החבילה שלי",
        "scansRemaining": "סריקות נותרו",
        "unlimited": "ללא הגבלה",
        "noPlan": "אין חבילה",
        "upgrade": "שדרוג",
        "choosePlan": "בחרו חבילה",
        "noActivePlan": "אין חבילה פעילה",
        "noActivePlanMessage": "כדי להעלות ולסרוק חוזה, צריך להפעיל חבילה תחילה.",
        "noScansLeft": "אין סריקות נותרות",
        "noScansMessage": "שדרגו את החבילה שלכם כדי להמשיך לסרוק חוזים.",
        "upgradePlan": "שדרוג חבילה"
    },
    "billing": {
        "title": "ניהול חיובים ותשלומים",
        "subtitle": "נהלו את אמצעי התשלום, צפו בחשבוניות והיסטוריית חיובים במקום אחד מאובטח.",
        "currentPlan": "החבילה הנוכחית",
        "scansRemaining": "סריקות נותרו",
        "unlimited": "ללא הגבלה",
        "noPlan": "אין חבילה פעילה",
        "upgradePlan": "שדרוג חבילה",
        "portalTitle": "ניהול אמצעי תשלום וחשבוניות",
        "portalDesc": "עדכנו כרטיס אשראי, הורידו חשבוניות PDF וצפו בהיסטוריית התשלומים שלכם.",
        "portalButton": "ניהול אמצעי תשלום והיסטוריית חיובים",
        "portalLoading": "מכין קישור מאובטח...",
        "portalError": "לא הצלחנו לפתוח את פורטל התשלומים. נסו שוב.",
        "feature1Title": "עדכון אמצעי תשלום",
        "feature1Desc": "הוסיפו או החליפו כרטיס אשראי בצורה מאובטחת.",
        "feature2Title": "הורדת חשבוניות",
        "feature2Desc": "הורידו חשבוניות מפורטות בפורמט PDF.",
        "feature3Title": "היסטוריית תשלומים",
        "feature3Desc": "צפו בכל העסקאות והתשלומים שביצעתם.",
        "filterLast5": "5 עסקאות אחרונות",
        "filterAllTransactions": "כל העסקאות",
        "filterPaid": "שולם",
        "filterFailed": "נכשל",
        "notAvailable": "לא זמין",
        "historyTitle": "היסטוריית חיובים",
        "noTransactionsForFilter": "לא נמצאו עסקאות עבור הסינון שנבחר.",
        "statusPaid": "שולם",
        "statusFailed": "נכשל",
        "statusUnknown": "לא ידוע",
        "poweredByStripe": "מאובטח ע\"י Stripe",
        "securityNote": "כל הנתונים שלכם מוצפנים ומאובטחים ברמת התעשייה.",
        "backToSettings": "חזרה להגדרות"
    },
    "sharedContract": {
        "invalidLink": "קישור לא תקין",
        "loadFailed": "לא ניתן לטעון את החוזה מהקישור הזה.",
        "loadingTitle": "טוען חוזה משותף...",
        "loadingSubtitle": "אוספים את מסמך החוזה בצורה מאובטחת, זה ייקח רגע.",
        "errorTitle": "שגיאה בטעינת החוזה",
        "retryButton": "נסה שוב",
        "viewTitle": "צפייה בחוזה משותף",
        "viewSubtitle": "מצב צפייה בלבד. אפשר לעיין בתוכן ולהוריד את המסמך המעודכן ל-Word.",
        "exportWord": "ייצוא כקובץ docx (Word)",
        "notRentalTitle": "המסמך אינו חוזה שכירות",
        "notRentalDesc": "לא ניתן להציג את תוכן המסמך בקישור זה."
    },
    "legal": {
        "legalDocument": "מסמך משפטי",
        "quickNavigation": "ניווט מהיר בסעיפים"
    },
    "terms": {
        "title": "תנאי שירות",
        "updated": "עודכן לאחרונה: מרץ 2026",
        "tocTitle": "תוכן עניינים",
        "contactPrefix": "לשאלות נוספות, פנו אלינו דרך",
        "contactLinkText": "עמוד צור קשר",
        "contactMiddle": "או במייל ל-",
        "sections": [
            {
                "id": "acceptance",
                "title": "1. הסכמה לתנאים",
                "content": "בשימוש באתר ובשירותי RentGuard 360, אתה מסכים לתנאי שימוש אלה. אם אינך מסכים לתנאים, אנא הימנע משימוש בשירותים."
            },
            {
                "id": "service",
                "title": "2. תיאור השירות",
                "content": "RentGuard 360 מספקת שירות ניתוח חוזי שכירות באמצעות בינה מלאכותית. השירות כולל:",
                "list": [
                    "סריקה אוטומטית של חוזי שכירות בפורמט PDF",
                    "זיהוי סעיפים בעייתיים וניגודי אינטרסים",
                    "דירוג סיכון מפורט לכל סעיף",
                    "המלצות ותיקונים מוצעים",
                    "יצוא דוחות בפורמט PDF ו-Word"
                ]
            },
            {
                "id": "purchases",
                "title": "3. רכישות ותשלומים",
                "content": "כל הרכישות באתר הן רכישות חד-פעמיות של חבילות סריקה. לא מתבצע חיוב חוזר או מנוי מתחדש אוטומטית. התשלומים מעובדים באמצעות Stripe ומאובטחים בהתאם לתקני PCI DSS. RentGuard 360 אינה שומרת את פרטי כרטיס האשראי שלך — כל המידע הרגיש מנוהל ישירות על ידי Stripe."
            },
            {
                "id": "refund",
                "title": "4. מדיניות החזרים",
                "content": "מאחר שהשירות מספק ניתוח מיידי לאחר רכישה, החזרים יינתנו רק במקרים יוצאי דופן (למשל כשל טכני שמנע מהמערכת להשלים את הניתוח). לבקשות החזר, פנו אלינו דרך עמוד צור קשר."
            },
            {
                "id": "data",
                "title": "5. שמירת מידע ופרטיות",
                "content": "אנו מחויבים להגנה על פרטיותך. הנקודות העיקריות:",
                "list": [
                    "חוזים שהועלו מאוחסנים מוצפנים בשרתי AWS",
                    "המידע משמש אך ורק לצורך מתן השירות המבוקש",
                    "אנו לא מוכרים או משתפים מידע אישי עם צדדים שלישיים",
                    "תוכלו לבקש מחיקת המידע שלכם בכל עת",
                    "אנו משתמשים ב-cookies הכרחיים בלבד לתפעול האתר"
                ]
            },
            {
                "id": "security",
                "title": "6. אבטחת מידע",
                "content": "אנו מיישמים אמצעי אבטחה מתקדמים כדי להגן על המידע שלכם, כולל הצפנת SSL/TLS, אחסון מוצפן, אימות רב-שלבי (MFA) וניטור אבטחה שוטף. השרתים שלנו מתארחים ב-AWS ועומדים בתקני אבטחה בינלאומיים."
            },
            {
                "id": "disclaimer",
                "title": "7. הגבלת אחריות",
                "content": "הניתוח המסופק על ידי RentGuard 360 הוא בגדר מידע כללי בלבד ואינו מהווה ייעוץ משפטי. מומלץ בחום להתייעץ עם עורך דין לפני חתימה על כל חוזה. RentGuard 360 אינה אחראית להחלטות שהתקבלו על בסיס הניתוח בלבד."
            },
            {
                "id": "ip",
                "title": "8. קניין רוחני",
                "content": "כל הזכויות בשירות, כולל עיצוב, קוד, אלגוריתמים ותוכן, שייכות ל-RentGuard 360. אין להעתיק, להפיץ או לשכפל כל חלק מהשירות ללא אישור בכתב."
            },
            {
                "id": "changes",
                "title": "9. שינויים בתנאים",
                "content": "אנו שומרים לעצמנו את הזכות לעדכן תנאים אלה מעת לעת. שינויים מהותיים יפורסמו באתר ו/או ישלחו בדוא\"ל. המשך השימוש בשירות לאחר עדכון התנאים מהווה הסכמה לתנאים המעודכנים."
            },
            {
                "id": "contact",
                "title": "10. יצירת קשר",
                "content": "לשאלות בנוגע לתנאי שימוש אלה או לכל נושא אחר, ניתן לפנות אלינו דרך עמוד צור קשר באתר או במייל."
            }
        ]
    },
    "privacy": {
        "title": "מדיניות פרטיות",
        "updated": "עודכן לאחרונה: מרץ 2026",
        "tocTitle": "תוכן עניינים",
        "contactPrefix": "לשאלות נוספות בנושא פרטיות, פנו אלינו דרך",
        "contactLinkText": "עמוד צור קשר",
        "contactMiddle": "או במייל ל-",
        "sections": [
            {
                "id": "general",
                "title": "1. כללי",
                "content": "אנו ב-RentGuard 360 (\"החברה\", \"אנו\", \"שלנו\") מכבדים את פרטיותך ומחויבים להגן עליה. מדיניות פרטיות זו מתארת באילו אופנים אנו אוספים, משתמשים ומגנים על המידע האישי שלך בעת השימוש באתר ובשירותים שלנו."
            },
            {
                "id": "collection",
                "title": "2. איסוף מידע",
                "content": "אנו אוספים סוגי מידע שונים לשם אספקת השירות:",
                "list": [
                    "פרטי התקשרות והרשמה (כתובת דוא\"ל, שם מלא).",
                    "מידע פיננסי מעובד בצורה מאובטחת על ידי חברות סליקה צד שלישי המורשות לכך (Stripe); אנו לא שומרים את פרטי כרטיס האשראי שלך בשרתינו.",
                    "מסמכים והסכמי שכירות שאתה בוחר להעלות (לשם ניתוח באמצעות מערכות הבינה המלאכותית שלנו)."
                ]
            },
            {
                "id": "usage",
                "title": "3. שימוש במידע",
                "content": "שימוש במידע שנאסף נעשה אך ורק לשם המטרות הבאות:",
                "list": [
                    "מתן שירות ניתוח מסמכים (הממוחשב והאוטומטי) ושיפור חוויית המשתמש והשירות.",
                    "ניהול חשבונות המשתמשים שלנו ואספקת תמיכה טכנית.",
                    "משלוח הודעות שירות (כגון עדכונים במערכת או הפקת דוחות) – לא יישלח תוכן שיווקי אלא אם ניתנה הסכמה מפורשת."
                ]
            },
            {
                "id": "sharing",
                "title": "4. שיתוף מידע עם צדדים שלישיים",
                "content": "איננו מוכרים, סוחרים או מעבירים מידע מזהה אישי לצורכי שיווק לצדדים שלישיים. אנו עשויים לשתף מידע עם ספקי שירות שעוזרים לנו לתפעל את המערכת שלנו (למשל, Amazon Web Services וספקי סליקה) ובלבד שספקים אלה מתחייבים לשמור על סודיות ואבטחת המידע בהתאם לאותם סטנדרטים מחמירים שלנו."
            },
            {
                "id": "ai-processing",
                "title": "5. עיבוד בבינה מלאכותית",
                "content": "ההסכמים שתעלה למערכת מועברים לעיבוד במנועי בינה מלאכותית (LLMs). אנו נוקטים באמצעים טכנולוגיים ליישום הסתרת נתונים אישיים (השחרה) בטרם הניתוח, במטרה למנוע סריקה של פרטים כגון תעודת זהות ומספרי טלפון, למען ההגנה על פרטיותך."
            },
            {
                "id": "data-retention",
                "title": "6. שמירת מידע ומחיקתו",
                "content": "מסמכים שהועלו לסריקה נשמרים תחת הצפנה קפדנית, ומוחזקים בחשבונך. תוכל באזור האישי (או דרך פנייה לתמיכה) למחוק את המסמכים ואף למחוק את החשבון במלואו, תוך מחיקה מלאה של המידע מהשרתים, בהתאם לדרישות החוק."
            },
            {
                "id": "cookies",
                "title": "7. Cookies (\"עוגיות\")",
                "content": "האתר משתמש בטכנולוגיות מעקב מסוג \"עוגיות\" (Cookies) בכדי להבטיח את תפקודו התקין של האתר וניהול מצב התחברות (Sessions). תוכל לבטל את האפשרות בדפדפן, אך לא תוכל להשתמש בשירותי המערכת הדורשים התחברות."
            },
            {
                "id": "contact",
                "title": "8. פניות",
                "content": "בכל שאלה בנושא פרטיות או במקרה של בקשה לעיון, תיקון או מחיקה של המידע האישי שברשותנו, ניתן לפנות אלינו לפי פרטי הקשר שמופיעים באתר."
            }
        ]
    }
};
