/**
 * ============================================
 *  LanguageContext
 *  i18n Provider with Hebrew/English Support
 * ============================================
 * 
 * STRUCTURE:
 * - translations object (Hebrew & English dictionaries)
 * - LanguageContext creation
 * - LanguageProvider component with localStorage persistence
 * - useLanguage hook for consuming context
 * 
 * DEPENDENCIES:
 * - React Context API
 * - localStorage for language preference persistence
 * 
 * NOTES:
 * - Default language is Hebrew ('he')
 * - RTL direction is set automatically on document
 * - Use t('key.path') to get translated strings
 * 
 * ============================================
 */
/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useState, useEffect } from 'react';

// ============================================
// TRANSLATIONS
// ============================================

const translations = {
    he: {
        // Navigation
        nav: {
            home: 'דף הבית',
            brand: 'RentGuard 360',
            openMenu: 'פתח תפריט',
            closeMenu: 'סגור תפריט',
            openProfile: 'פתח פרופיל',
            closeProfile: 'סגור פרופיל',
            dashboard: 'לוח בקרה',
            upload: 'העלאה',
            contracts: 'חוזים',
            settings: 'הגדרות',
            contact: 'צור קשר',
            pricing: 'תוכניות',
            logout: 'התנתקות',
            admin: 'ניהול',
            dark: 'כהה',
            light: 'בהיר',
            backToDashboard: 'חזרה לדף הבית',
            scansLeft: 'סריקות',
            unlimited: 'ללא הגבלה',
        },
        // Auth (Login/Register)
        auth: {
            login: 'התחברות',
            register: 'הרשמה',
            email: 'אימייל',
            password: 'סיסמה',
            fullName: 'שם מלא',
            passwordHint: 'לפחות 8 תווים, אות גדולה ומספר',
            loginButton: 'התחברות',
            registerButton: 'יצירת חשבון',
            noAccount: 'אין לך חשבון?',
            hasAccount: 'יש לך כבר חשבון?',
            confirmTitle: 'אימות אימייל',
            confirmMessage: 'שלחנו קוד לכתובת',
            confirmCode: 'קוד אימות',
            confirmButton: 'אימות',
            verificationSuccess: 'אימות הצליח!',
            verificationSuccessMessage: 'אל תשכח לאמת את האימייל שלך כדי להשתמש באתר',
            continueToLogin: 'המשך להתחברות',
            forgotPassword: 'שכחת סיסמה?',
            forgotPasswordTitle: 'איפוס סיסמה',
            forgotPasswordMessage: 'הזן את כתובת האימייל שלך ונשלח לך קוד איפוס',
            sendCodeButton: 'שלח קוד',
            resetPasswordTitle: 'הגדרת סיסמה חדשה',
            resetPasswordMessage: 'שלחנו קוד איפוס לכתובת',
            newPassword: 'סיסמה חדשה',
            resetCodePlaceholder: 'קוד איפוס',
            resetPasswordButton: 'אפס סיסמה',
            backToLogin: 'חזרה להתחברות',
            // Landing page content
            heroTitle: 'ניתוח חוזי שכירות בבינה מלאכותית',
            heroSubtitle: 'העלו את חוזה השכירות שלכם וקבלו ניתוח מפורט של:',
            heroBenefit1: 'סעיפים בעייתיים וסיכונים משפטיים',
            heroBenefit2: 'ציון סיכון כולל (0-100)',
            heroBenefit3: 'טיפים למשא ומתן',
            heroFeatures: 'עברית מלאה 🇮🇱 | ניתוח תוך 60 שניות ⚡ | פרטיות מלאה 🔒',
            // Benefits carousel
            benefitCloud: 'מבוסס ענן AWS',
            benefitCloudDesc: 'תשתית ברמה ארגונית עם זמינות של 99.99%. המסמכים שלך מעובדים בבטחה בענן.',
            benefitAI: 'בינה מלאכותית מתקדמת',
            benefitAIDesc: 'מופעל על ידי Amazon Bedrock - אחת ממערכות ה-AI החכמות ביותר הקיימות היום.',
            benefitSecurity: 'אבטחה ברמת בנק',
            benefitSecurityDesc: 'הצפנה מקצה לקצה. המידע האישי שלך מוסתר אוטומטית לפני ניתוח ה-AI. אפס שמירת מידע.',
            benefitFast: 'ניתוח AI מהיר',
            benefitFastDesc: 'חוזים פשוטים? תוך פחות מדקה. חוזים מורכבים? מספר דקות. הבינה המלאכותית שלנו סורקת כל סעיף לעומק.',
            // Demo steps
            demoTitle: 'איך זה עובד?',
            demoStep1: 'העלאת PDF',
            demoStep1Desc: 'העלו את חוזה השכירות שלכם בפורמט PDF. אנחנו תומכים בעברית ואנגלית.',
            demoStep2: 'ניתוח AI',
            demoStep2Desc: 'ה-AI שלנו סורק סיכונים, תנאים לא הוגנים ובעיות משפטיות.',
            demoStep3: 'קבלת תוצאות',
            demoStep3Desc: 'צפו בציון הסיכון, הסברים לבעיות וטיפים למשא ומתן.',
            // Features
            featureAI: '🤖 ניתוח AI',
            featureAIDesc: 'מופעל על ידי Amazon Bedrock לניתוח חוזים כמו מומחה משפטי',
            featurePrivacy: '🔒 פרטיות במקום ראשון',
            featurePrivacyDesc: 'מידע אישי (ת.ז., טלפון, אימייל) מוסתר אוטומטית לפני הניתוח',
            featureTips: '💡 טיפים חכמים',
            featureTipsDesc: 'קבלו עצות ספציפיות למשא ומתן על כל סעיף בעייתי',
            // Footer
            footerTagline: 'הגנה על החוזה שלך עם בינה מלאכותית מתקדמת',
            footerSupport: 'צריכים עזרה? שלחו לנו מייל:',
            footerEmail: 'rentguard360@gmail.com',
            footerResponse: 'תגובה תוך 24 שעות | הצוות שלנו מוכנים להגן עליכם כמו שאנחנו מגנים על החוזה שלכם',
            projectName: '💻 פרויקט סיום מחשוב ענן',
        },
        // Dashboard
        dashboard: {
            welcomeSubtitle: 'ברוכים הבאים ל-RentGuard 360. העלו ונתחו חוזי שכירות עם בינה מלאכותית.',
            quickActions: 'פעולות מהירות',
            greeting: {
                morning: 'בוקר טוב',
                afternoon: 'צהריים טובים',
                evening: 'ערב טוב',
                night: 'לילה טוב',
            },
            totalContracts: 'סה"כ חוזים',
            analyzed: 'נותחו',
            pending: 'ממתינים',
            highRisk: 'סיכון גבוה',
            uploadContract: 'העלאת חוזה',
            uploadDescription: 'העלו חוזה שכירות חדש לניתוח AI',
            uploadPDF: 'העלאת PDF',
            viewContracts: 'צפייה בחוזים',
            viewDescription: 'עיינו בכל החוזים שהעליתם',
            viewAll: 'צפייה בכולם',
            howToStart: 'איך מתחילים',
            step1Title: 'העלאת חוזה',
            step1Desc: 'גררו ושחררו את חוזה השכירות בפורמט PDF',
            step2Title: 'ניתוח AI',
            step2Desc: 'חוזים פשוטים? תוך פחות מדקה. חוזים מורכבים? מספר דקות. הבינה המלאכותית שלנו סורקת כל סעיף לעומק.',
            step3Title: 'קבלת תובנות',
            step3Desc: 'צפו בסיכונים והצעות למשא ומתן',
            whyUs: 'למה דווקא RentGuard 360?',
            whyUsSubtitle: 'לא סתם עוד צ\'אט בוט - מערכת מקצועית שנבנתה במיוחד לניתוח חוזי שכירות',
            featurePrivacy: 'הגנה על הפרטיות',
            featurePrivacyDesc: 'המערכת מזהה ומצנזרת אוטומטית מידע אישי (ת.ז., טלפון, כתובת) לפני שליחה ל-AI. הפרטים שלכם נשארים פרטיים.',
            featurePrompt: 'פרומפט מקצועי מותאם',
            featurePromptDesc: 'בניגוד לשליחה לצ\'אט רגיל, המערכת שלנו משתמשת בפרומפט מיוחד שמנתח 70+ גורמי סיכון על פי חוק השכירות הישראלי.',
            featureScore: 'ציון סיכון מבוסס נתונים',
            featureScoreDesc: 'מקבלים ציון אובייקטיבי 0-100 עם פירוט לפי קטגוריות: תנאים כספיים, זכויות הדייר, אחריות ותיקונים ועוד.',
            featureTips: 'טיפים למשא ומתן',
            featureTipsDesc: 'לא רק מזהים בעיות - מקבלים הצעות קונקרטיות לתיקון סעיפים בעייתיים שתוכלו להציג לבעל הדירה.',
            featureAws: 'תשתית ענן מאובטחת',
            featureAwsDesc: 'רץ על AWS עם הצפנה מקצה לקצה. החוזים שלכם לא נשמרים ונמחקים אוטומטית לאחר הניתוח.',
        },
        // Contracts Page
        contracts: {
            title: 'החוזים שלי',
            subtitle: 'ניהול וצפייה בכל חוזי השכירות שלך',
            refresh: 'רענון',
            refreshing: 'מרענן...',
            uploadContract: 'העלאת חוזה',
            noContracts: 'אין חוזים עדיין',
            noContractsDesc: 'העלו את חוזה השכירות הראשון שלכם לניתוח',
            uploadFirst: 'העלאת חוזה ראשון',
            deleteTitle: 'מחיקת חוזה',
            deleteConfirm: 'האם אתה בטוח שברצונך למחוק חוזה זה? פעולה זו לא ניתנת לביטול.',
            cancel: 'ביטול',
            delete: 'מחיקה',
            deleting: 'מוחק...',
            editTitle: 'עריכת פרטים',
            fileName: 'שם קובץ',
            propertyAddress: 'כתובת הנכס',
            landlordName: 'שם המשכיר',
            save: 'שמירה',
            saving: 'שומר...',
            loading: 'טוען חוזים...',
            lowRisk: 'סיכון נמוך',
            lowMediumRisk: 'סיכון נמוך-בינוני',
            mediumRisk: 'סיכון בינוני',
            highRisk: 'סיכון גבוה',
            analyzed: 'הושלם',
            pendingAnalysis: 'ממתין',
            notSpecified: 'לא צוין',
            exportWord: 'ייצוא Word',
            exportPDF: 'ייצוא PDF',
            viewAnalysis: 'צפייה בניתוח',
            sortBy: 'מיון לפי:',
            sortDate: 'תאריך',
            sortScore: 'ציון סיכון',
            uploadDate: 'תאריך העלאה',
            untitledContract: 'חוזה ללא שם',
            analyzedPrefix: 'נותח:',
            statusTimedOutRetry: 'תם הזמן - נסה שוב',
            statusAnalysisFailed: 'שגיאה בניתוח',
            statusFailedShort: 'ניתוח נכשל',
            statusPendingShort: 'ממתין...',
            menuExportTrigger: 'ייצוא',
            menuExportTitle: 'ייצוא דוח הניתוח',
            menuDownloadTitle: 'הורדה',
            menuExportWordTitle: 'ייצוא ל-Word - דוח ניתוח',
            menuExportWordNote: 'ייצוא כקובץ docx (Word), עריך ומומלץ לעברית',
            menuExportPdfTitle: 'PDF - דוח ניתוח',
            menuExportPdfNote: 'סיכום מהיר, אנגלית בלבד',
            menuShareTrigger: 'שיתוף',
            menuShareTitle: 'שיתוף דוח הניתוח',
            menuSharePdfTitle: 'שיתוף קובץ PDF',
            menuSharePdfNote: 'מצרף את הדוח כקובץ לשיתוף',
            editButtonTitle: 'עריכה',
            deleteButtonTitle: 'מחיקה',
            deleteFailed: 'מחיקה נכשלה',
            saveFailed: 'שמירה נכשלה',
            exportFailed: 'ייצוא נכשל',
            shareFailed: 'השיתוף נכשל',
            exportPdfStarted: 'קובץ PDF ירד למחשב (סיכום באנגלית)',
            exportWordStarted: 'קובץ docx (Word) ירד למחשב (עריך)',
            shareSheetOpened: 'חלון השיתוף נפתח עבור PDF',
            fileNamePlaceholder: 'שם הקובץ',
            propertyAddressPlaceholder: 'כתובת',
            landlordNamePlaceholder: 'משכיר',
            pageOf: 'עמוד {current} מתוך {total}',
        },
        // Upload Page
        upload: {
            title: 'העלאת חוזה',
            subtitle: 'העלו את חוזה השכירות שלכם לניתוח AI',
            dragDrop: 'שחררו את ה-PDF כאן',
            or: 'או לחצו לבחירת קובץ',
            selectFile: 'בחירת קבצים',
            maxSize: 'גודל מקסימלי: 5MB | PDF בלבד',
            termsLabel: 'אני מאשר/ת שקראתי והבנתי את',
            termsLink: 'תנאי השימוש ומדיניות הפרטיות',
            uploadBtn: 'העלאת חוזה לניתוח',
            uploading: 'מעלה...',
            complete: 'הושלם!',
            uploadSuccess: 'ההעלאה הצליחה!',
            analyzing: 'ה-AI מנתח את החוזה שלכם (30-60 שניות)...',
            uploadedToServer: '✓ החוזה הועלה לשרת',
            analysisStarted: '✓ הניתוח התחיל',
            viewMyContracts: 'צפייה בחוזים שלי',
            uploadAnother: 'העלאת חוזה נוסף',
            uploadSuccessTitle: 'החוזה הועלה בהצלחה!',
            uploadSuccessMessage: 'תוצאות הניתוח של החוזה שלך ישלחו לאימייל שלך',
            goToContracts: 'עבור לחוזים שלי',
            contractDetails: 'פרטי החוזה (אופציונלי)',
            propertyAddress: 'כתובת הנכס',
            addressPlaceholder: 'רחוב ראשי 123, עיר',
            landlordName: 'שם המשכיר',
            landlordPlaceholder: 'ישראל ישראלי',
            contractName: 'שם החוזה',
            termsTitle: 'תנאי שימוש ומדיניות פרטיות',
            terms1Title: '1. הסכמה לתנאים',
            terms1Content: 'בהעלאת מסמכים למערכת RentGuard 360, אתם מסכימים לתנאי השימוש הבאים:',
            terms2Title: '2. שימוש במידע',
            terms2Content: 'המסמכים שתעלו יעובדו באמצעות טכנולוגיית AI לצורך ניתוח חוזי שכירות. המידע ישמש אך ורק לצורך מתן השירות המבוקש.',
            terms3Title: '3. אבטחת מידע',
            terms3Content: 'אנו מתחייבים לשמור על המידע שלכם בהתאם לתקני אבטחה מחמירים. המסמכים מאוחסנים בצורה מוצפנת בשרתי AWS.',
            terms4Title: '4. שמירת מידע',
            terms4Content: 'המידע יישמר למשך הזמן הנדרש לספק את השירות ובהתאם לדרישות החוק.',
            terms5Title: '5. הגבלת אחריות',
            terms5Content: 'הניתוח המוצע על ידי המערכת הינו לצורכי מידע בלבד ואינו מהווה ייעוץ משפטי. מומלץ להתייעץ עם עורך דין לפני חתימה על חוזה.',
            terms6Title: '6. זכויות המשתמש',
            terms6Content: 'באפשרותכם לבקש מחיקת המידע שלכם בכל עת באמצעות פנייה לתמיכה.',
            iAgree: 'קראתי ואני מסכים/ה',
            close: 'סגור',
            pdfOnly: 'רק קבצי PDF מותרים',
            fileTooLarge: 'גודל הקובץ חייב להיות פחות מ-5MB',
            fileTooSmall: 'הקובץ קטן מדי - ייתכן שהוא ריק או פגום',
            fileNameTooLong: 'שם הקובץ ארוך מדי (מקסימום 100 תווים)',
            uploadFailed: 'ההעלאה נכשלה. נסו שוב.',
        },
        // Analysis Page
        analysis: {
            title: 'ניתוח חוזה',
            backToContracts: 'חזרה לחוזים',
            summary: 'סיכום',
            scoreBreakdown: 'פירוט הציון',
            aggregateIntelligence: 'אינטליגנציה משוקללת',
            overallHealth: 'בריאות החוזה',
            overallRiskScore: 'ציון סיכון כולל',
            refresh: 'רענון',
            export: 'ייצוא',
            quickActions: 'פעולות מהירות',
            actionRequired: 'דורש התייחסות',
            contractMetadata: 'פרטי החוזה',
            deepAnalysisAndClauses: 'ניתוח מעמיק וסעיפים',
            theIssue: 'הבעיה',
            negotiationStrategy: 'אסטרטגיית משא ומתן',
            issues: 'בעיות שזוהו',
            noIssues: 'לא נמצאו בעיות בחוזה זה',
            original: 'מקור',
            problem: 'הבעיה',
            recommendation: 'המלצה',
            copyFix: 'העתק תיקון',
            copied: 'הועתק!',
            askAI: 'שאל את ה-AI',
            loading: 'טוען ניתוח...',
            analyzing: 'מנתח את החוזה...',
            notContract: 'מסמך זה לא נראה כחוזה שכירות',
            shareButtonCreating: 'יוצר קישור...',
            shareButtonHide: 'הסתר קישור שיתוף',
            shareButtonShow: 'הצג קישור שיתוף פעיל',
            shareButtonCreate: 'יצירת לינק שיתוף',
            toastSavingTitle: 'שומר שינויים',
            toastSavingMessage: 'המערכת שומרת את העריכות שלך כעת.',
            toastSavedTitle: 'השינויים נשמרו',
            toastSavedMessage: 'השינויים נשמרו אוטומטית בענן.',
            toastSaveFailedTitle: 'שמירה נכשלה',
            toastSaveFailedMessage: 'לא הצלחנו לשמור את העריכות. נסה שוב בעוד רגע.',
            defaultReportName: 'דוח_ניתוח',
            exportWordStarted: 'קובץ docx (Word) ירד למחשב',
            exportPdfStarted: 'קובץ PDF ירד למחשב',
            missingShareContractId: 'לא נמצא מזהה חוזה לשיתוף',
            sharePanelHidden: 'פאנל השיתוף הוסתר',
            sharePanelShown: 'קישור שיתוף פעיל מוצג',
            shareCreated: 'קישור שיתוף נוצר. אפשר להעתיק או לשתף מהפאנל.',
            shareCreateFailed: 'שגיאה ביצירת קישור שיתוף',
            shareCopiedTitle: 'הקישור הועתק בהצלחה',
            shareCopiedMessage: 'אפשר להדביק ולשתף בכל אפליקציה.',
            shareCopyFailed: 'שגיאה בהעתקת הקישור',
            shareNativeTitle: 'חוזה משותף מ-RentGuard 360',
            shareNativeText: 'צפייה בחוזה (קריאה בלבד):',
            shareFailed: 'שגיאה בשיתוף הקישור',
            shareRevokedTitle: 'קישור השיתוף בוטל',
            shareRevokedMessage: 'הקישור הישן כבר לא פעיל.',
            shareRevokeFailed: 'שגיאה בביטול קישור שיתוף',
            errors: {
                notReadyTitle: 'הניתוח עדיין לא מוכן',
                notReadyMessage: 'החוזה שלך עדיין בתהליך. בודקים שוב אוטומטית...',
                failedTitle: 'הניתוח נכשל',
                failedMessage: 'אירעה שגיאה בניתוח החוזה. הצוות עודכן. אפשר לנסות להעלות מחדש.',
                timeoutTitle: 'זמן הניתוח הסתיים',
                timeoutMessage: 'הניתוח לוקח יותר מהרגיל. נסו שוב בעוד כמה דקות.',
                genericTitle: 'משהו השתבש',
                genericMessage: 'לא הצלחנו לטעון את תוצאות הניתוח. נסו שוב.',
            },
            shareExpiryDefault: 'בתוקף ל-7 ימים',
            shareExpiryExpired: 'פג תוקף',
            shareExpiryDays: 'בתוקף לעוד {days} ימים',
            technicalDetails: 'פרטים טכניים',
            tryAgain: 'נסה שוב',
            contractDocument: 'מסמך חוזה',
            analysisComplete: 'הניתוח הושלם.',
            exportMenuTitle: 'ייצוא דוח הניתוח',
            exportMenuDownload: 'הורדה',
            exportMenuWordTitle: 'ייצוא ל-Word - דוח ניתוח',
            exportMenuWordNote: '(ייצוא כקובץ docx (Word), ניתן לעריכה מלאה)',
            exportMenuPdfTitle: 'הורדה PDF - דוח ניתוח',
            exportMenuPdfNote: '(תצוגה ושיתוף מהיר, אנגלית בלבד)',
            exportMenuShare: 'שיתוף',
            fullContractTab: 'החוזה המלא',
            points: 'נקודות',
            legalBasis: 'בסיס משפטי',
            whyItMatters: 'למה זה חשוב?',
            negotiationTip: 'טיפ למשא ומתן',
            notRentalTitle: 'זה לא חוזה שכירות',
            notRentalDescription: 'המסמך שהועלה אינו נראה כחוזה שכירות תקין. אנא העלו חוזה שכירות למגורים בפורמט PDF.',
            noIssuesDescription: 'חוזה זה נראה תקין ללא דגלים אדומים משמעותיים.',
            notRentalContentDescription: 'המסמך שהועלה אינו נראה כחוזה שכירות תקין. לא ניתן להציג את תוכן החוזה.',
            originalClause: 'הסעיף המקורי',
            recommendedClause: 'הנוסח המומלץ',
            exportEditedWord: 'ייצוא כקובץ docx (Word)',
            resetEditsTitle: 'איפוס כל העריכות שביצעת',
            resetEdits: 'איפוס עריכות',
            secureShareLink: 'קישור שיתוף מאובטח',
            shareLinkAria: 'קישור שיתוף',
            copyLink: 'העתק קישור',
            sharing: 'משתף...',
            shareViaApps: 'שתף באפליקציות',
            openLink: 'פתח קישור',
            revoking: 'מבטל קישור...',
            revokeLink: 'ביטול קישור',
        },
        contractView: {
            consultError: 'שגיאה בקבלת הסבר. נסה שוב.',
            editedContractFileName: 'חוזה_שכירות_ערוך',
            expand: 'הרחב חוזה',
            collapse: 'כווץ מסמך',
            contractTitle: 'חוזה שכירות בלתי מוגנת',
            contractSubtitle: 'נערך ונחתם ביום ________________',
            showOnlyProblemClauses: 'הצג רק סעיפים בעייתיים',
            clausesCountSuffix: 'סעיפים',
            issuesCountSuffix: 'בעיות',
            editedCountSuffix: 'נערכו',
            noIssuesFound: 'לא נמצאו בעיות!',
            noTextFound: 'לא נמצא טקסט.',
            getClauseExplanation: 'קבל הסבר על הסעיף',
            edit: 'עריכה',
            aiExplanation: 'הסבר AI',
            fixSuggestion: 'הצעה לתיקון',
            signaturesTitle: 'חתימות',
            landlord: 'המשכיר',
            tenant: 'השוכר',
            namePlaceholder: 'שם: ________________',
            idPlaceholder: 'ת.ז.: ________________',
            datePlaceholder: 'תאריך: ________________',
            scrollUp: 'גלול למעלה',
            scrollToSignatures: 'גלול לחתימות',
            up: 'למעלה',
            toSignatures: 'לחתימות',
            editClause: 'עריכת סעיף',
            originalClauseLabel: 'סעיף מקורי:',
            aiFixSuggestionLabel: 'הצעת תיקון AI',
            applySuggestion: 'החל הצעה',
            editLabel: 'עריכה:',
            editPlaceholder: 'ערוך את הסעיף כאן...',
            finishEditing: 'סיום עריכה',
            revertToOriginal: 'חזור למקור',
            cancel: 'ביטול',
            confirmRevertTitle: 'אישור ביטול',
            confirmRevertMessage: 'האם אתה בטוח שברצונך לבטל את העריכה ולחזור לטקסט המקורי?',
            confirmRevertYes: 'כן, בטל עריכה',
            confirmRevertNo: 'לא, השאר',
            clearAllTitle: 'מחיקת כל העריכות',
            clearAllMessage: 'האם אתה בטוח שברצונך למחוק את כל העריכות שביצעת בחוזה זה?',
            irreversibleWarning: 'פעולה זו אינה הפיכה.',
            clearAllYes: 'כן, מחק הכל',
        },
        // Score Breakdown
        score: {
            lowRisk: 'סיכון נמוך',
            lowMediumRisk: 'סיכון נמוך-בינוני',
            mediumRisk: 'סיכון בינוני',
            mediumHighRisk: 'סיכון בינוני-גבוה',
            highRisk: 'סיכון גבוה',
            financialTerms: 'תנאים כספיים',
            tenantRights: 'זכויות הדייר',
            terminationClauses: 'סיום ויציאה',
            liabilityRepairs: 'אחריות ותיקונים',
            legalCompliance: 'עמידה בחוק',
        },
        // Contact Page
        contact: {
            title: 'אנחנו כאן בשבילך',
            subtitle: 'יש לך שאלות לגבי ניהול השכירות שלך? הצוות המקצועי של RentGuard זמין לסייע לך בכל נושא משפטי או טכני.',
            successTitle: 'ההודעה נשלחה בהצלחה!',
            successMessage: 'נחזור אליכם בהקדם האפשרי.',
            sendAnother: 'שליחת הודעה נוספת',
            fullName: 'שם מלא',
            fullNamePlaceholder: 'ישראל ישראלי',
            phone: 'טלפון',
            phonePlaceholder: '054-7820346',
            email: 'אימייל',
            emailPlaceholder: 'name@company.com',
            message: 'הודעה',
            messagePlaceholder: 'איך נוכל לעזור לך היום?',
            sending: 'שולח...',
            sendMessage: 'שלח הודעה',
            contactDetails: 'פרטי התקשרות',
            address: 'כתובתנו',
            addressValue: 'אור עקיבא, המרכז המשפטי, ישראל',
            emailLabel: 'דואר אלקטרוני',
            emailValue: 'rentguard360@gmail.com',
            phoneLabel: 'טלפון',
            phoneValue: '050-0000000',
            joinText: 'הצטרפו לאלפי בעלי נכסים שבוחרים בשקט נפשי עם RentGuard.',
            defaultSubject: 'פנייה חדשה מדף צור קשר',
            errorMessage: 'שליחת ההודעה נכשלה. נסו שוב.',
            secureCommunication: 'תקשורת מאובטחת',
            fastResponse: 'מענה תוך 24 שעות',
            notCustomerYet: 'עדיין לא מנויים?',
            registerNowFree: 'הירשמו עכשיו בחינם',
            registerFreePlan: 'הרשמה לקבלת גרסה חינמית',
            orOption: 'או',
            toStartAnalyzing: 'כדי להתחיל לנתח חוזים',
        },
        methodology: {
            title: 'איך מחושב הציון?',
            intro1: 'הציון הוא 5 קטגוריות × 20 נק׳ (סה״כ 100). מורידים נקודות לפי חומרה.',
            intro2: 'תקרה: קטגוריה לא יורדת מתחת ל-0 ⇒ מקסימום 20 נק׳ ירידה לכל קטגוריה (לכן סכום הקנסות יכול להיות גבוה יותר מהירידה בפועל בציון).',
            high: 'גבוה',
            medium: 'בינוני',
            low: 'נמוך',
            pts: 'נקודות',
            categoriesHeader: '5 קטגוריות × 20 נקודות = 100',
            catFinancial: 'תנאים פיננסיים',
            catFinancialDesc: 'ערבות, קנסות איחור, ביטוח',
            catRights: 'זכויות השוכר',
            catRightsDesc: 'כניסה לדירה, סאבלט, פרטיות',
            catTermination: 'סיום חוזה',
            catTerminationDesc: 'תקופת הודעה, יציאה מוקדמת',
            catLiability: 'אחריות ותיקונים',
            catLiabilityDesc: 'תיקונים, בלאי סביר',
            catLegal: 'תאימות חוקית',
            catLegalDesc: 'התאמה לחוק השכירות 2017',
            legalSource: 'מבוסס על חוק השכירות והשאילה (תיקון 2017) - סעיפים 25א-25טו'
        },
        // Footer
        footer: {
            tagline: 'פלטפורמת ניתוח חוזי שכירות מבוססת AI',
            benefits: 'פרטיות מלאה | ניתוח מהיר ומאובטח | טיפים למשא ומתן | תשתית ענן מאובטחת',
            project: 'פרויקט סיום מחשוב ענן',
            copyright: '© RentGuard 360 {year} . כל הזכויות שמורות.',
            legalTagline: 'הגנה משפטית חכמה לכל חוזה שכירות.',
            termsLink: 'תנאי שימוש',
            privacyLink: 'מדיניות פרטיות',
            contactLink: 'צור קשר',
            builtBy: 'נבנה ע"י',
        },
        // Contract Chat Widget
        chat: {
            title: 'RentGuard 360 Chat',
            open: 'פתיחת צ׳אט חוזה',
            close: 'סגירת צ׳אט',
            contractLabel: 'חוזה',
            selectContract: 'בחרו חוזה',
            loadingContracts: 'טוען חוזים...',
            emptySelectContract: 'בחרו חוזה כדי להתחיל לשאול שאלות.',
            emptyStart: 'אין עדיין הודעות. שאלו את השאלה הראשונה.',
            scope: 'עונה לפי החוזה הנבחר בלבד. לא מהווה ייעוץ משפטי.',
            quickPromptsLabel: 'הצעות מהירות לשאלות',
            promptHighRisk: 'מה 3 הסיכונים הכי גבוהים בחוזה?',
            promptPets: 'האם מותר להכניס כלב או חיית מחמד?',
            promptTermination: 'מה תנאי סיום החוזה והאם יש קנסות?',
            inputPlaceholder: '...שאלו על סעיפים, תשלומים, חיות מחמד, סיום חוזה',
            send: 'שלח שאלה',
            clear: 'נקה היסטוריה',
            clearShort: 'נקה',
            clearConfirm: 'למחוק את כל היסטוריית הצ׳אט של החוזה שנבחר? לא ניתן לשחזר את ההודעות.',
            clearSuccessTitle: 'היסטוריית הצ׳אט נוקתה',
            clearSuccessMessage: 'נמחקו {count} הודעות מההיסטוריה.',
            clearSuccessMessageGeneric: 'היסטוריית הצ׳אט נוקתה בהצלחה.',
            copy: 'העתק',
            copied: 'הועתק',
            you: 'אתם',
            assistant: 'עוזר AI',
            thinking: 'ה-AI מנתח את החוזה',
            tip: 'טיפ: שאלו על סעיפים, תשלומים או סיום חוזה.',
            disclaimer: 'ה-AI יכול לטעות. בדקו פרטים חשובים בחוזה.',
            showNotice: 'הצג מידע',
            hideNotice: 'הסתר מידע',
            noAnswer: 'לא נוצרה תשובה.',
            dismissHint: 'סגור הודעה',
            hints: {
                rateLimit: 'הגעתם כרגע למגבלת שאלות זמנית בגלל עומס. חכו כדקה ונסו שוב.'
            },
            rateLimitRetryIn: 'נסו שוב בעוד {seconds} שניות.',
            errors: {
                loadContracts: 'טעינת החוזים נכשלה. נסו שוב.',
                loadHistory: 'טעינת היסטוריית הצ׳אט נכשלה. נסו שוב.',
                selectContract: 'בחרו חוזה לפני שליחת שאלה.',
                askFailed: 'לא הצלחתי לקבל תשובה כרגע. נסו שוב.',
                clearFailed: 'ניקוי ההיסטוריה נכשל. נסו שוב.'
            }
        },
        // Common
        common: {
            loading: 'טוען...',
            error: 'שגיאה',
            success: 'הצלחה',
            user: 'משתמש',
            cancel: 'ביטול',
            confirm: 'אישור',
            ok: 'אישור',
            comingSoon: 'בקרוב',
        },
        errorBoundary: {
            title: 'משהו השתבש',
            message: 'משהו השתבש. אנא נסו לרענן את העמוד.',
            reload: 'רענון העמוד',
            details: 'פרטי שגיאה',
        },
        languageToggle: {
            switchToEnglish: 'Switch to English',
            switchToHebrew: 'עבור לעברית',
            heLabel: 'עב',
            enLabel: 'EN',
        },
        recommendationCard: {
            defaultTitle: 'הצעה לתיקון',
            applied: 'הוחל',
            revertTitle: 'בטל שינויים וחזור למקור',
            revert: 'בטל',
            applyFix: 'החל תיקון',
        },
        notifications: {
            bundleRequiredTitle: 'יש לבחור חבילה תחילה',
            bundleRequiredMessage: 'כדי להמשיך, בחרו חבילה בעמוד התוכניות.',
            contactSentTitle: 'ההודעה נשלחה',
            contactSentMessage: 'קיבלנו את פנייתכם ונחזור אליכם בקרוב.',
            contactFailedTitle: 'שליחת ההודעה נכשלה',
            contactFailedMessage: 'לא הצלחנו לשלוח את ההודעה כרגע. נסו שוב.',
            uploadFailedTitle: 'העלאת החוזה נכשלה',
            analysisReadyTitle: 'הניתוח הושלם',
            analysisReadyMessage: 'החוזה נותח בהצלחה ואפשר לצפות בתוצאות.',
            adminUserEnabledTitle: 'המשתמש הופעל',
            adminUserEnabledMessage: 'המשתמש {user} הופעל בהצלחה.',
            adminUserEnableFailedTitle: 'הפעלת משתמש נכשלה',
            adminUserEnableFailedMessage: 'לא הצלחנו להפעיל את המשתמש {user}.',
            adminUserDisabledTitle: 'המשתמש הושעה',
            adminUserDisabledMessage: 'המשתמש {user} הושעה.',
            adminUserDisableFailedTitle: 'השעיית משתמש נכשלה',
            adminUserDisableFailedMessage: 'לא הצלחנו להשעות את המשתמש {user}.',
            adminUserDeletedTitle: 'המשתמש נמחק',
            adminUserDeletedMessage: 'המשתמש {user} נמחק לצמיתות.',
            adminUserDeleteFailedTitle: 'מחיקת משתמש נכשלה',
            adminUserDeleteFailedMessage: 'לא הצלחנו למחוק את המשתמש {user}.',
        },
        // Account Settings
        account: {
            deleteAccount: 'מחק חשבון',
            deleteAccountDescription: 'מחיקת החשבון שלך לצמיתות כולל כל החוזים שלך',
            deleteConfirmTitle: 'האם אתה בטוח?',
            deleteConfirmMessage: 'פעולה זו תמחק את החשבון שלך לצמיתות, כולל:',
            deleteConfirmItem1: '• כל החוזים שלך',
            deleteConfirmItem2: '• כל הניתוחים שלך',
            deleteConfirmItem3: '• נתוני הפרופיל שלך',
            deleteConfirmWarning: 'פעולה זו לא ניתנת לביטול!',
            typeDeleteToConfirm: 'הקלד DELETE כדי לאשר:',
            deleteAccountSuccess: 'החשבון נמחק בהצלחה',
            deleteAccountError: 'שגיאה במחיקת החשבון',
            deletingAccount: 'מוחק חשבון...',
            deletingContracts: 'מוחק חוזים...',
        },
        // Admin Dashboard
        admin: {
            title: 'לוח בקרה למנהל',
            accessDenied: 'גישה נדחתה',
            noPermission: 'אין לך הרשאות מנהל',
            statsTab: 'סטטיסטיקות',
            usersTab: 'משתמשים',
            stripeTab: 'תובנות Stripe',
            tryAgain: 'נסה שוב',
            // Stats
            contractsSection: 'חוזים',
            totalContracts: 'סה״כ חוזים',
            analyzed: 'נותחו',
            pending: 'ממתינים',
            failed: 'נכשלו',
            analysisSection: 'ניתוח',
            avgRiskScore: 'ציון סיכון ממוצע',
            avgAnalysisTime: 'זמן ניתוח ממוצע',
            usersSection: 'משתמשים',
            totalUsers: 'סה״כ משתמשים',
            activeUsers30: 'פעילים (30 יום)',
            updatedAt: 'עודכן',
            seconds: 'שניות',
            minutes: 'דקות',
            days: 'ימים',
            thisMonth: 'החודש',
            thisYear: 'השנה',
            analyzedOverTime: 'חוזים שנותחו לאורך זמן',
            userRegistrations: 'רישום משתמשים לאורך זמן',
            allTime: 'הכל',
            noData: 'אין נתונים להצגה',
            // Users
            searchPlaceholder: 'חפש לפי אימייל או שם...',
            search: 'חפש',
            email: 'אימייל',
            name: 'שם',
            status: 'סטטוס',
            joined: 'הצטרף',
            actions: 'פעולות',
            noUsers: 'לא נמצאו משתמשים',
            active: 'פעיל',
            pendingVerification: 'ממתין לאימות',
            suspended: 'מושעה',
            disable: 'השעה',
            enable: 'הפעל',
            delete: 'מחק',
            copyEmail: 'העתק אימייל',
            copied: 'הועתק',
            copyFailed: 'לא ניתן להעתיק אימייל. אפשר לסמן ולהעתיק ידנית.',
            allUsers: 'כל המשתמשים',
            activeOnly: 'פעילים בלבד',
            disabledOnly: 'מושעים בלבד',
            showingUsers: 'מציג {count} משתמשים',
            confirmDisable: 'האם אתה בטוח שברצונך להשעות משתמש זה?',
            confirmDisableTitle: 'השעיית משתמש',
            confirmDelete: 'האם אתה בטוח שברצונך למחוק משתמש זה?',
            confirmDeleteTitle: 'מחיקת משתמש',
            confirmDeleteFinal: 'פעולה זו אינה ניתנת לביטול! המשתמש יימחק לצמיתות. האם להמשיך?',
            confirmDeleteFinalTitle: '⚠️ אישור סופי',
            confirmDeleteBtn: 'כן, מחק לצמיתות',
            selectYear: 'בחר שנה',
            userDeleted: 'המשתמש נמחק בהצלחה',
            // Admin Sidebar
            dashboard: 'לוח בקרה',
            analytics: 'אנליטיקות',
            settings: 'הגדרות',
            administrator: 'מנהל',
            // Analytics Page
            analyticsDescription: 'ניתוח חוזים מפורט ותובנות סיכון',
            radarChart: 'רדאר סיכונים',
            radarChartDesc: 'ניתוח סיכונים ב-5 צירים בקרוב',
            sparklines: 'גרפי מגמות',
            sparklinesDesc: 'גרפי מגמות מיני בקרוב',
            riskBreakdown: 'פירוט סיכונים',
            riskBreakdownDesc: 'ניתוח קטגוריות מפורט',
            riskDistribution: 'התפלגות סיכונים',
            commonIssues: 'בעיות נפוצות בחוזים',
            code: 'קוד',
            issue: 'בעיה',
            count: 'כמות',
            stripeInsightsTitle: 'תובנות Stripe וחיובים',
            stripeInsightsSubtitle: 'תמונה מלאה של חיובים, המרות, הכנסות ונתוני חבילות מהמערכת',
            generatedAt: 'עודכן בתאריך',
            availableBalance: 'יתרה זמינה',
            pendingBalance: 'יתרה בהמתנה',
            charges30Days: 'חיובים ב-30 יום',
            disputes30Days: 'מחלוקות (30 יום)',
            intents30Days: 'Payment Intents ב-30 יום',
            successRate: 'שיעור הצלחה',
            refundedCharges: 'חיובים שהוחזרו',
            revenue: 'הכנסות',
            avgOrderValue: 'ממוצע עסקה',
            activeSubscribers: 'מנויים פעילים',
            transactions: 'עסקאות',
            bundleDistribution: 'התפלגות חבילות',
            recentTransactions: 'עסקאות אחרונות',
            bundle: 'חבילה',
            amount: 'סכום',
            currency: 'מטבע',
            country: 'מדינה',
            stripeFeatures: 'יכולות Stripe',
            chargesEnabled: 'חיובים פעילים',
            payoutsEnabled: 'העברות פעילות',
            enabled: 'פעיל',
            disabled: 'כבוי',
            refundAmount30Days: 'סכום החזרים (30 יום)',
            intentToChargeConversion: 'יחס המרה מכוונה לחיוב',
            paymentMethodMix: 'פירוט אמצעי תשלום',
            noPaymentSignals: 'עדיין אין נתוני אמצעי תשלום.',
            failedCharges30Days: 'חיובים שנכשלו (30 יום)',
            disputeRate: 'שיעור מחלוקות',
            refundRate: 'שיעור החזרים',
            chargesToIntents: 'חיובים / כוונות חיוב',
            topCurrencies: 'מטבעות מובילים',
            noCurrencyAmounts: 'עדיין אין נתוני מטבעות.',
            stripeStatusError: 'לא ניתן למשוך נתוני Stripe כרגע',
            // Settings Page
            settingsDescription: 'הגדרות מערכת והעדפות',
            notifications: 'התראות',
            notificationsDesc: 'הגדרת התראות אימייל ופוש',
            security: 'אבטחה',
            securityDesc: 'אימות ובקרת גישה',
            dataRetention: 'שמירת מידע',
            dataRetentionDesc: 'הגדרות אחסון וגיבוי חוזים',
            emailTemplates: 'תבניות אימייל',
            emailTemplatesDesc: 'התאמה אישית של אימיילים',
            comingSoon: 'בקרוב',
        },
        // Pricing Page
        pricing: {
            title: 'בחרו את החבילה שלכם',
            subtitle: 'בחרו את החבילה המתאימה ביותר לצרכים שלכם והתחילו לנתח חוזי שכירות עם בינה מלאכותית',
            currentPlan: 'החבילה הנוכחית:',
            scansLeft: 'סריקות נותרו',
            unlimited: 'ללא הגבלה',
            mostPopular: 'הפופולרית ביותר',
            yourPlan: 'החבילה שלך',
            currentPlanBtn: 'החבילה הנוכחית',
            getStarted: 'התחילו בחינם',
            subscribe: 'רכישה',
            buyMoreScans: 'קנה עוד סריקות',
            free: 'חינם',
            single: 'חד פעמית',
            basic: 'בסיס',
            pro: 'פרו',
            month: 'חודש',
            scans: 'סריקות',
            unlimitedScans: '15 סריקות',
            freeDesc: 'נסו את המערכת ללא התחייבות',
            singleDesc: 'בדקו חוזה בודד בצורה מעמיקה',
            basicDesc: 'מושלם לשימוש מזדמן',
            proDesc: 'המשתלמת ביותר למשתמשים קבועים',
            featuresFree: ['סריקת חוזה אחת', 'ניתוח AI מלא', 'ציון סיכון מפורט', 'ניסיון ללא התחייבות'],
            featuresSingle: ['סריקת חוזה אחת', 'ניתוח AI מלא', 'ציון סיכון מפורט', 'ייצוא PDF ו-Word'],
            featuresBasic: ['5 סריקות חוזים', 'ניתוח AI מלא', 'ציון סיכון מפורט', 'טיפים למשא ומתן', 'ייצוא PDF ו-Word'],
            featuresPro: ['15 סריקות חוזים', 'ניתוח AI מלא', 'ציון סיכון מפורט', 'טיפים למשא ומתן', 'ייצוא PDF ו-Word', 'תמיכה בעדיפות'],
        },
        // Checkout Page
        checkout: {
            title: 'השלמת רכישה',
            backToPricing: 'חזרה לחבילות',
            orderSummary: 'סיכום הזמנה',
            plan: 'חבילה',
            scans: 'סריקות',
            total: 'סה״כ לתשלום',
            paymentMethod: 'אמצעי תשלום',
            cardDetails: 'פרטי כרטיס אשראי',
            pay: 'שלם',
            processing: 'מעבד תשלום...',
            securedByStripe: 'תשלום מאובטח באמצעות Stripe',
            testMode: 'מצב בדיקה — השתמש בכרטיס',
            termsLabel: 'אני מאשר/ת את ',
            termsLinkTerms: 'תנאי השירות',
            termsJoin: ' ו',
            termsLinkPrivacy: 'מדיניות הפרטיות',
            termsLinkText: 'תנאי השירות ומדיניות הפרטיות',
            termsDisclaimer: '. אני מבין/ה שמדובר ברכישה חד-פעמית של חבילת סריקות ושלא יתבצע חיוב חוזר.',
            termsRequired: 'יש לאשר את תנאי השירות כדי להמשיך',
        },
        // Payment Success Page
        paymentSuccess: {
            title: 'התשלום הושלם בהצלחה',
            freeActivated: 'החבילה החינמית שלך הופעלה. תוכלו להתחיל לסרוק חוזים עכשיו.',
            paymentCompleted: 'התשלום עבר בהצלחה והחבילה שלך עודכנה.',
            plan: 'חבילה',
            amount: 'סכום',
            hint: 'תוכלו להתחיל מיד לסרוק חוזי שכירות.',
            goToDashboard: 'לוח בקרה',
            uploadContract: 'העלאת חוזה',
        },
        // Subscription
        subscription: {
            myPlan: 'החבילה שלי',
            scansRemaining: 'סריקות נותרו',
            unlimited: 'ללא הגבלה',
            noPlan: 'אין חבילה',
            upgrade: 'שדרוג',
            choosePlan: 'בחרו חבילה',
            noActivePlan: 'אין חבילה פעילה',
            noActivePlanMessage: 'כדי להעלות ולסרוק חוזה, צריך להפעיל חבילה תחילה.',
            noScansLeft: 'אין סריקות נותרות',
            noScansMessage: 'שדרגו את החבילה שלכם כדי להמשיך לסרוק חוזים.',
            upgradePlan: 'שדרוג חבילה',
        },
        // Billing Page
        billing: {
            title: 'ניהול חיובים ותשלומים',
            subtitle: 'נהלו את אמצעי התשלום, צפו בחשבוניות והיסטוריית חיובים במקום אחד מאובטח.',
            currentPlan: 'החבילה הנוכחית',
            scansRemaining: 'סריקות נותרו',
            unlimited: 'ללא הגבלה',
            noPlan: 'אין חבילה פעילה',
            upgradePlan: 'שדרוג חבילה',
            portalTitle: 'ניהול אמצעי תשלום וחשבוניות',
            portalDesc: 'עדכנו כרטיס אשראי, הורידו חשבוניות PDF וצפו בהיסטוריית התשלומים שלכם.',
            portalButton: 'ניהול אמצעי תשלום והיסטוריית חיובים',
            portalLoading: 'מכין קישור מאובטח...',
            portalError: 'לא הצלחנו לפתוח את פורטל התשלומים. נסו שוב.',
            feature1Title: 'עדכון אמצעי תשלום',
            feature1Desc: 'הוסיפו או החליפו כרטיס אשראי בצורה מאובטחת.',
            feature2Title: 'הורדת חשבוניות',
            feature2Desc: 'הורידו חשבוניות מפורטות בפורמט PDF.',
            feature3Title: 'היסטוריית תשלומים',
            feature3Desc: 'צפו בכל העסקאות והתשלומים שביצעתם.',
            poweredByStripe: 'מאובטח ע"י Stripe',
            securityNote: 'כל הנתונים שלכם מוצפנים ומאובטחים ברמת התעשייה.',
            backToSettings: 'חזרה להגדרות',
        },
        // Terms of Service
        terms: {
            title: 'תנאי שירות',
            updated: 'עודכן לאחרונה: מרץ 2026',
            tocTitle: 'תוכן עניינים',
            contactPrefix: 'לשאלות נוספות, פנו אלינו דרך',
            contactLinkText: 'עמוד צור קשר',
            contactMiddle: 'או במייל ל-',
            sections: [
                {
                    id: 'acceptance',
                    title: '1. הסכמה לתנאים',
                    content: 'בשימוש באתר ובשירותי RentGuard 360, אתה מסכים לתנאי שימוש אלה. אם אינך מסכים לתנאים, אנא הימנע משימוש בשירותים.',
                },
                {
                    id: 'service',
                    title: '2. תיאור השירות',
                    content: 'RentGuard 360 מספקת שירות ניתוח חוזי שכירות באמצעות בינה מלאכותית. השירות כולל:',
                    list: [
                        'סריקה אוטומטית של חוזי שכירות בפורמט PDF',
                        'זיהוי סעיפים בעייתיים וניגודי אינטרסים',
                        'דירוג סיכון מפורט לכל סעיף',
                        'המלצות ותיקונים מוצעים',
                        'יצוא דוחות בפורמט PDF ו-Word',
                    ],
                },
                {
                    id: 'purchases',
                    title: '3. רכישות ותשלומים',
                    content: 'כל הרכישות באתר הן רכישות חד-פעמיות של חבילות סריקה. לא מתבצע חיוב חוזר או מנוי מתחדש אוטומטית. התשלומים מעובדים באמצעות Stripe ומאובטחים בהתאם לתקני PCI DSS. RentGuard 360 אינה שומרת את פרטי כרטיס האשראי שלך — כל המידע הרגיש מנוהל ישירות על ידי Stripe.',
                },
                {
                    id: 'refund',
                    title: '4. מדיניות החזרים',
                    content: 'מאחר שהשירות מספק ניתוח מיידי לאחר רכישה, החזרים יינתנו רק במקרים יוצאי דופן (למשל כשל טכני שמנע מהמערכת להשלים את הניתוח). לבקשות החזר, פנו אלינו דרך עמוד צור קשר.',
                },
                {
                    id: 'data',
                    title: '5. שמירת מידע ופרטיות',
                    content: 'אנו מחויבים להגנה על פרטיותך. הנקודות העיקריות:',
                    list: [
                        'חוזים שהועלו מאוחסנים מוצפנים בשרתי AWS',
                        'המידע משמש אך ורק לצורך מתן השירות המבוקש',
                        'אנו לא מוכרים או משתפים מידע אישי עם צדדים שלישיים',
                        'תוכלו לבקש מחיקת המידע שלכם בכל עת',
                        'אנו משתמשים ב-cookies הכרחיים בלבד לתפעול האתר',
                    ],
                },
                {
                    id: 'security',
                    title: '6. אבטחת מידע',
                    content: 'אנו מיישמים אמצעי אבטחה מתקדמים כדי להגן על המידע שלכם, כולל הצפנת SSL/TLS, אחסון מוצפן, אימות רב-שלבי (MFA) וניטור אבטחה שוטף. השרתים שלנו מתארחים ב-AWS ועומדים בתקני אבטחה בינלאומיים.',
                },
                {
                    id: 'disclaimer',
                    title: '7. הגבלת אחריות',
                    content: 'הניתוח המסופק על ידי RentGuard 360 הוא בגדר מידע כללי בלבד ואינו מהווה ייעוץ משפטי. מומלץ בחום להתייעץ עם עורך דין לפני חתימה על כל חוזה. RentGuard 360 אינה אחראית להחלטות שהתקבלו על בסיס הניתוח בלבד.',
                },
                {
                    id: 'ip',
                    title: '8. קניין רוחני',
                    content: 'כל הזכויות בשירות, כולל עיצוב, קוד, אלגוריתמים ותוכן, שייכות ל-RentGuard 360. אין להעתיק, להפיץ או לשכפל כל חלק מהשירות ללא אישור בכתב.',
                },
                {
                    id: 'changes',
                    title: '9. שינויים בתנאים',
                    content: 'אנו שומרים לעצמנו את הזכות לעדכן תנאים אלה מעת לעת. שינויים מהותיים יפורסמו באתר ו/או ישלחו בדוא"ל. המשך השימוש בשירות לאחר עדכון התנאים מהווה הסכמה לתנאים המעודכנים.',
                },
                {
                    id: 'contact',
                    title: '10. יצירת קשר',
                    content: 'לשאלות בנוגע לתנאי שימוש אלה או לכל נושא אחר, ניתן לפנות אלינו דרך עמוד צור קשר באתר או במייל.',
                },
            ]
        },
        // Privacy Policy
        privacy: {
            title: 'מדיניות פרטיות',
            updated: 'עודכן לאחרונה: מרץ 2026',
            tocTitle: 'תוכן עניינים',
            contactPrefix: 'לשאלות נוספות בנושא פרטיות, פנו אלינו דרך',
            contactLinkText: 'עמוד צור קשר',
            contactMiddle: 'או במייל ל-',
            sections: [
                {
                    id: 'general',
                    title: '1. כללי',
                    content: 'אנו ב-RentGuard 360 ("החברה", "אנו", "שלנו") מכבדים את פרטיותך ומחויבים להגן עליה. מדיניות פרטיות זו מתארת באילו אופנים אנו אוספים, משתמשים ומגנים על המידע האישי שלך בעת השימוש באתר ובשירותים שלנו.'
                },
                {
                    id: 'collection',
                    title: '2. איסוף מידע',
                    content: 'אנו אוספים סוגי מידע שונים לשם אספקת השירות:',
                    list: [
                        'פרטי התקשרות והרשמה (כתובת דוא"ל, שם מלא).',
                        'מידע פיננסי מעובד בצורה מאובטחת על ידי חברות סליקה צד שלישי המורשות לכך (Stripe); אנו לא שומרים את פרטי כרטיס האשראי שלך בשרתינו.',
                        'מסמכים והסכמי שכירות שאתה בוחר להעלות (לשם ניתוח באמצעות מערכות הבינה המלאכותית שלנו).'
                    ]
                },
                {
                    id: 'usage',
                    title: '3. שימוש במידע',
                    content: 'שימוש במידע שנאסף נעשה אך ורק לשם המטרות הבאות:',
                    list: [
                        'מתן שירות ניתוח מסמכים (הממוחשב והאוטומטי) ושיפור חוויית המשתמש והשירות.',
                        'ניהול חשבונות המשתמשים שלנו ואספקת תמיכה טכנית.',
                        'משלוח הודעות שירות (כגון עדכונים במערכת או הפקת דוחות) – לא יישלח תוכן שיווקי אלא אם ניתנה הסכמה מפורשת.'
                    ]
                },
                {
                    id: 'sharing',
                    title: '4. שיתוף מידע עם צדדים שלישיים',
                    content: 'איננו מוכרים, סוחרים או מעבירים מידע מזהה אישי לצורכי שיווק לצדדים שלישיים. אנו עשויים לשתף מידע עם ספקי שירות שעוזרים לנו לתפעל את המערכת שלנו (למשל, Amazon Web Services וספקי סליקה) ובלבד שספקים אלה מתחייבים לשמור על סודיות ואבטחת המידע בהתאם לאותם סטנדרטים מחמירים שלנו.'
                },
                {
                    id: 'ai-processing',
                    title: '5. עיבוד בבינה מלאכותית',
                    content: 'ההסכמים שתעלה למערכת מועברים לעיבוד במנועי בינה מלאכותית (LLMs). אנו נוקטים באמצעים טכנולוגיים ליישום הסתרת נתונים אישיים (השחרה) בטרם הניתוח, במטרה למנוע סריקה של פרטים כגון תעודת זהות ומספרי טלפון, למען ההגנה על פרטיותך.'
                },
                {
                    id: 'data-retention',
                    title: '6. שמירת מידע ומחיקתו',
                    content: 'מסמכים שהועלו לסריקה נשמרים תחת הצפנה קפדנית, ומוחזקים בחשבונך. תוכל באזור האישי (או דרך פנייה לתמיכה) למחוק את המסמכים ואף למחוק את החשבון במלואו, תוך מחיקה מלאה של המידע מהשרתים, בהתאם לדרישות החוק.'
                },
                {
                    id: 'cookies',
                    title: '7. Cookies ("עוגיות")',
                    content: 'האתר משתמש בטכנולוגיות מעקב מסוג "עוגיות" (Cookies) בכדי להבטיח את תפקודו התקין של האתר וניהול מצב התחברות (Sessions). תוכל לבטל את האפשרות בדפדפן, אך לא תוכל להשתמש בשירותי המערכת הדורשים התחברות.'
                },
                {
                    id: 'contact',
                    title: '8. פניות',
                    content: 'בכל שאלה בנושא פרטיות או במקרה של בקשה לעיון, תיקון או מחיקה של המידע האישי שברשותנו, ניתן לפנות אלינו לפי פרטי הקשר שמופיעים באתר.'
                }
            ]
        },
    },
    en: {
        // Navigation
        nav: {
            home: 'Home',
            brand: 'RentGuard 360',
            openMenu: 'Open menu',
            closeMenu: 'Close menu',
            openProfile: 'Open profile',
            closeProfile: 'Close profile',
            dashboard: 'Dashboard',
            upload: 'Upload',
            contracts: 'Contracts',
            settings: 'Settings',
            contact: 'Contact',
            pricing: 'Pricing',
            logout: 'Logout',
            admin: 'Admin',
            dark: 'Dark',
            light: 'Light',
            backToDashboard: 'Back to Dashboard',
            scansLeft: 'scans',
            unlimited: 'Unlimited',
        },
        // Auth (Login/Register)
        auth: {
            login: 'Login',
            register: 'Sign Up',
            email: 'Email',
            password: 'Password',
            fullName: 'Full Name',
            passwordHint: 'At least 8 characters, uppercase and number',
            loginButton: 'Login',
            registerButton: 'Create Account',
            noAccount: "Don't have an account?",
            hasAccount: 'Already have an account?',
            confirmTitle: 'Email Verification',
            confirmMessage: 'We sent a code to',
            confirmCode: 'Verification Code',
            confirmButton: 'Verify',
            verificationSuccess: 'Verification Successful!',
            verificationSuccessMessage: "Don't forget to verify your email to use the website",
            continueToLogin: 'Continue to Login',
            forgotPassword: 'Forgot password?',
            forgotPasswordTitle: 'Reset Password',
            forgotPasswordMessage: 'Enter your email address and we will send you a reset code',
            sendCodeButton: 'Send Code',
            resetPasswordTitle: 'Set New Password',
            resetPasswordMessage: 'We sent a reset code to',
            newPassword: 'New Password',
            resetCodePlaceholder: 'Reset Code',
            resetPasswordButton: 'Reset Password',
            backToLogin: 'Back to Login',
            // Landing page content
            heroTitle: 'AI-Powered Rental Contract Analysis',
            heroSubtitle: 'Upload your rental contract and get a detailed analysis of:',
            heroBenefit1: 'Problematic clauses and legal risks',
            heroBenefit2: 'Overall risk score (0-100)',
            heroBenefit3: 'Negotiation tips',
            heroFeatures: 'Full Hebrew Support 🇮🇱 | Analysis in 60 seconds ⚡ | Full Privacy 🔒',
            // Benefits carousel
            benefitCloud: 'AWS Cloud-Based',
            benefitCloudDesc: 'Enterprise-grade infrastructure with 99.99% availability. Your documents are processed securely in the cloud.',
            benefitAI: 'Advanced AI',
            benefitAIDesc: 'Powered by Amazon Bedrock - one of the most intelligent AI systems available today.',
            benefitSecurity: 'Bank-Level Security',
            benefitSecurityDesc: 'End-to-end encryption. Your personal data is automatically masked before AI analysis. Zero data retention.',
            benefitFast: 'Lightning-Fast AI Analysis',
            benefitFastDesc: 'Simple contracts? Under 60 seconds. Complex ones? Just a few minutes. Our advanced AI scans every clause for your protection.',
            // Demo steps
            demoTitle: 'How it Works',
            demoStep1: 'Upload PDF',
            demoStep1Desc: 'Upload your rental contract in PDF format. We support Hebrew and English.',
            demoStep2: 'AI Analysis',
            demoStep2Desc: 'Our AI scans for risks, unfair terms, and legal issues.',
            demoStep3: 'Get Results',
            demoStep3Desc: 'View risk score, issue explanations, and negotiation tips.',
            // Features
            featureAI: '🤖 AI Analysis',
            featureAIDesc: 'Powered by Amazon Bedrock for contract analysis like a legal expert',
            featurePrivacy: '🔒 Privacy First',
            featurePrivacyDesc: 'Personal info (ID, phone, email) is automatically masked before analysis',
            featureTips: '💡 Smart Tips',
            featureTipsDesc: 'Get specific negotiation advice for each problematic clause',
            // Footer
            footerTagline: 'Protecting your lease with cutting-edge AI',
            footerSupport: 'Need help? Drop us a line:',
            footerEmail: 'rentguard360@gmail.com',
            footerResponse: 'Response within 24 hours | Our team is as dedicated to helping you as we are to analyzing your contracts',
            projectName: '💻 Cloud Computing Final Project',
        },
        // Dashboard
        dashboard: {
            welcomeSubtitle: 'Welcome to RentGuard 360. Upload and analyze rental contracts with AI.',
            quickActions: 'Quick Actions',
            greeting: {
                morning: 'Good morning',
                afternoon: 'Good afternoon',
                evening: 'Good evening',
                night: 'Good night',
            },
            totalContracts: 'Total Contracts',
            analyzed: 'Analyzed',
            pending: 'Pending',
            highRisk: 'High Risk',
            uploadContract: 'Upload Contract',
            uploadDescription: 'Upload a new rental contract for AI analysis',
            uploadPDF: 'Upload PDF',
            viewContracts: 'View Contracts',
            viewDescription: 'Review all your uploaded contracts',
            viewAll: 'View All',
            howToStart: 'How to Start',
            step1Title: 'Upload Contract',
            step1Desc: 'Drag and drop your rental contract in PDF format',
            step2Title: 'AI Analysis',
            step2Desc: 'Simple contracts? Under 60 seconds. Complex ones? Just a few minutes. Our advanced AI scans every clause for your protection.',
            step3Title: 'Get Insights',
            step3Desc: 'View risks and negotiation suggestions',
            whyUs: 'Why RentGuard 360?',
            whyUsSubtitle: 'Not just another chatbot - a professional system built specifically for rental contract analysis',
            featurePrivacy: 'Privacy Protection',
            featurePrivacyDesc: 'The system automatically detects and redacts personal information (ID, phone, address) before sending to AI. Your details stay private.',
            featurePrompt: 'Custom Professional Prompt',
            featurePromptDesc: 'Unlike sending to a regular chat, our system uses a specialized prompt that analyzes 70+ risk factors according to Israeli rental law.',
            featureScore: 'Data-Driven Risk Score',
            featureScoreDesc: 'Get an objective score 0-100 with breakdown by categories: financial terms, tenant rights, liability and repairs, and more.',
            featureTips: 'Negotiation Tips',
            featureTipsDesc: 'Not just identifying issues - get concrete suggestions for fixing problematic clauses that you can present to the landlord.',
            featureAws: 'Secure Cloud Infrastructure',
            featureAwsDesc: 'Runs on AWS with end-to-end encryption. Your contracts are not stored and are automatically deleted after analysis.',
        },
        // Contracts Page
        contracts: {
            title: 'My Contracts',
            subtitle: 'Manage and view all your rental contracts',
            refresh: 'Refresh',
            refreshing: 'Refreshing...',
            uploadContract: 'Upload Contract',
            noContracts: 'No contracts yet',
            noContractsDesc: 'Upload your first rental contract for analysis',
            uploadFirst: 'Upload First Contract',
            deleteTitle: 'Delete Contract',
            deleteConfirm: 'Are you sure you want to delete this contract? This action cannot be undone.',
            cancel: 'Cancel',
            delete: 'Delete',
            deleting: 'Deleting...',
            editTitle: 'Edit Details',
            fileName: 'File Name',
            propertyAddress: 'Property Address',
            landlordName: 'Landlord Name',
            save: 'Save',
            saving: 'Saving...',
            loading: 'Loading contracts...',
            lowRisk: 'Low Risk',
            lowMediumRisk: 'Low-Medium Risk',
            mediumRisk: 'Medium Risk',
            highRisk: 'High Risk',
            analyzed: 'Completed',
            pendingAnalysis: 'Pending',
            notSpecified: 'Not specified',
            exportWord: 'Export Word',
            exportPDF: 'Export PDF',
            viewAnalysis: 'View Analysis',
            sortBy: 'Sort by:',
            sortDate: 'Date',
            sortScore: 'Risk Score',
            uploadDate: 'Upload Date',
            untitledContract: 'Untitled Contract',
            analyzedPrefix: 'Analyzed:',
            statusTimedOutRetry: 'Timed Out - Retry',
            statusAnalysisFailed: 'Analysis Failed',
            statusFailedShort: 'Analysis Failed',
            statusPendingShort: 'Pending...',
            menuExportTrigger: 'Export',
            menuExportTitle: 'Export Analysis Report',
            menuDownloadTitle: 'Download',
            menuExportWordTitle: 'Export to Word - Analysis Report',
            menuExportWordNote: '.docx editable, best Hebrew support',
            menuExportPdfTitle: 'PDF - Analysis Report',
            menuExportPdfNote: 'quick summary, English only',
            menuShareTrigger: 'Share',
            menuShareTitle: 'Share Analysis Report',
            menuSharePdfTitle: 'Share PDF File',
            menuSharePdfNote: 'attach the report as a file',
            editButtonTitle: 'Edit',
            deleteButtonTitle: 'Delete',
            deleteFailed: 'Delete failed',
            saveFailed: 'Save failed',
            exportFailed: 'Export failed',
            shareFailed: 'Share failed',
            exportPdfStarted: 'PDF download started (English summary)',
            exportWordStarted: 'Word (.docx) download started',
            shareSheetOpened: 'Share sheet opened for PDF',
            fileNamePlaceholder: 'File name',
            propertyAddressPlaceholder: 'Property address',
            landlordNamePlaceholder: 'Landlord',
            pageOf: 'Page {current} of {total}',
        },
        // Upload Page
        upload: {
            title: 'Upload Contract',
            subtitle: 'Upload your rental contract for AI analysis',
            dragDrop: 'Drop PDF here',
            or: 'or click to select file',
            selectFile: 'Select Files',
            maxSize: 'Max size: 5MB | PDF only',
            termsLabel: 'I confirm that I have read and understood the',
            termsLink: 'Terms of Service and Privacy Policy',
            uploadBtn: 'Upload Contract for Analysis',
            uploading: 'Uploading...',
            complete: 'Complete!',
            uploadSuccess: 'Upload Successful!',
            analyzing: 'AI is analyzing your contract (30-60 seconds)...',
            uploadedToServer: '✓ Contract uploaded to server',
            analysisStarted: '✓ Analysis started',
            viewMyContracts: 'View My Contracts',
            uploadAnother: 'Upload Another Contract',
            uploadSuccessTitle: 'Contract Uploaded Successfully!',
            uploadSuccessMessage: 'Your contract analysis results will be sent to your email',
            goToContracts: 'Go to My Contracts',
            contractDetails: 'Contract Details (Optional)',
            propertyAddress: 'Property Address',
            addressPlaceholder: '123 Main Street, City',
            landlordName: 'Landlord Name',
            landlordPlaceholder: 'John Smith',
            contractName: 'Contract Name',
            termsTitle: 'Terms of Service and Privacy Policy',
            terms1Title: '1. Agreement to Terms',
            terms1Content: 'By uploading documents to RentGuard 360, you agree to the following terms of use:',
            terms2Title: '2. Use of Information',
            terms2Content: 'Documents you upload will be processed using AI technology for rental contract analysis. The information will be used solely to provide the requested service.',
            terms3Title: '3. Data Security',
            terms3Content: 'We are committed to protecting your information according to strict security standards. Documents are stored encrypted on AWS servers.',
            terms4Title: '4. Data Retention',
            terms4Content: 'Information will be retained for the time necessary to provide the service and in accordance with legal requirements.',
            terms5Title: '5. Limitation of Liability',
            terms5Content: 'The analysis provided by the system is for informational purposes only and does not constitute legal advice. It is recommended to consult with a lawyer before signing any contract.',
            terms6Title: '6. User Rights',
            terms6Content: 'You may request deletion of your data at any time by contacting support.',
            iAgree: 'I have read and agree',
            close: 'Close',
            pdfOnly: 'Only PDF files are allowed',
            fileTooLarge: 'File size must be less than 5MB',
            fileTooSmall: 'File is too small - may be empty or corrupted',
            fileNameTooLong: 'Filename is too long (max 100 characters)',
            uploadFailed: 'Upload failed. Please try again.',
        },
        // Analysis Page
        analysis: {
            title: 'Contract Analysis',
            backToContracts: 'Back to Contracts',
            summary: 'Summary',
            scoreBreakdown: 'Score Breakdown',
            aggregateIntelligence: 'Aggregate Intelligence',
            overallHealth: 'Contract Health',
            overallRiskScore: 'Overall Risk Score',
            refresh: 'Refresh',
            export: 'Export',
            quickActions: 'Quick Actions',
            actionRequired: 'Action Required',
            contractMetadata: 'Contract Metadata',
            deepAnalysisAndClauses: 'Deep Analysis & Clauses',
            theIssue: 'The Issue',
            negotiationStrategy: 'Negotiation Strategy',
            issues: 'Issues Found',
            noIssues: 'No issues found in this contract',
            original: 'Original',
            problem: 'Problem',
            recommendation: 'Recommendation',
            copyFix: 'Copy Fix',
            copied: 'Copied!',
            askAI: 'Ask AI',
            loading: 'Loading analysis...',
            analyzing: 'Analyzing contract...',
            notContract: 'This document does not appear to be a rental contract',
            shareButtonCreating: 'Creating link...',
            shareButtonHide: 'Hide shared link',
            shareButtonShow: 'Show shared link',
            shareButtonCreate: 'Create share link',
            toastSavingTitle: 'Saving changes',
            toastSavingMessage: 'Your edits are being saved now.',
            toastSavedTitle: 'Edits saved',
            toastSavedMessage: 'Your edits were autosaved to the cloud.',
            toastSaveFailedTitle: 'Save failed',
            toastSaveFailedMessage: 'Could not save your edits. Please try again in a moment.',
            defaultReportName: 'Analysis_Report',
            exportWordStarted: 'Word (.docx) download started',
            exportPdfStarted: 'PDF file download started',
            missingShareContractId: 'Missing contract id for sharing',
            sharePanelHidden: 'Share panel hidden',
            sharePanelShown: 'Active share link is shown',
            shareCreated: 'Share link created. Copy or share it from the panel.',
            shareCreateFailed: 'Failed to create share link',
            shareCopiedTitle: 'Link copied successfully',
            shareCopiedMessage: 'You can now paste and share it anywhere.',
            shareCopyFailed: 'Failed to copy link',
            shareNativeTitle: 'Shared contract from RentGuard 360',
            shareNativeText: 'View the contract (read-only):',
            shareFailed: 'Failed to share link',
            shareRevokedTitle: 'Share link revoked',
            shareRevokedMessage: 'The old link is no longer active.',
            shareRevokeFailed: 'Failed to revoke share link',
            errors: {
                notReadyTitle: 'Analysis Not Ready',
                notReadyMessage: 'Your contract is still being processed. Auto-checking...',
                failedTitle: 'Analysis Failed',
                failedMessage: 'There was an error analyzing your contract. Our team has been notified. Please try uploading again.',
                timeoutTitle: 'Analysis Timed Out',
                timeoutMessage: 'The analysis is taking longer than expected. Please check back in a few minutes.',
                genericTitle: 'Something Went Wrong',
                genericMessage: 'Failed to load analysis results. Please try again.',
            },
            shareExpiryDefault: 'Valid for 7 days',
            shareExpiryExpired: 'Expired',
            shareExpiryDaysOne: 'Valid for 1 more day',
            shareExpiryDaysMany: 'Valid for {days} more days',
            technicalDetails: 'Technical Details',
            tryAgain: 'Try Again',
            contractDocument: 'Contract Document',
            analysisComplete: 'Analysis complete.',
            exportMenuTitle: 'Export Analysis Report',
            exportMenuDownload: 'Download',
            exportMenuWordTitle: 'Export to Word - Analysis Report',
            exportMenuWordNote: '(.docx editable, best Hebrew support)',
            exportMenuPdfTitle: 'Download PDF - Analysis Report',
            exportMenuPdfNote: '(best for quick viewing/sharing, English only)',
            exportMenuShare: 'Share',
            fullContractTab: 'Full Contract',
            points: 'points',
            legalBasis: 'Legal Basis',
            whyItMatters: 'Why It Matters',
            negotiationTip: 'Negotiation Tip',
            notRentalTitle: 'Not a Rental Contract',
            notRentalDescription: 'The uploaded document does not appear to be a valid rental contract. Please upload a residential rental contract in PDF format.',
            noIssuesDescription: 'This contract appears to be in good standing with no significant red flags.',
            notRentalContentDescription: 'The uploaded document does not appear to be a valid rental contract. Cannot display contract content.',
            originalClause: 'Original Clause',
            recommendedClause: 'Recommended Wording',
            exportEditedWord: 'Export to Word (.docx)',
            resetEditsTitle: 'Reset all edited clauses',
            resetEdits: 'Reset edits',
            secureShareLink: 'Secure share link',
            shareLinkAria: 'Share link',
            copyLink: 'Copy link',
            sharing: 'Sharing...',
            shareViaApps: 'Share via apps',
            openLink: 'Open link',
            revoking: 'Revoking...',
            revokeLink: 'Revoke link',
        },
        contractView: {
            consultError: 'Could not fetch explanation. Please try again.',
            editedContractFileName: 'Edited_Rental_Contract',
            expand: 'Expand',
            collapse: 'Collapse',
            contractTitle: 'Unprotected Rental Agreement',
            contractSubtitle: 'Prepared and signed on ________________',
            showOnlyProblemClauses: 'Show only problematic clauses',
            clausesCountSuffix: 'clauses',
            issuesCountSuffix: 'issues',
            editedCountSuffix: 'edited',
            noIssuesFound: 'No issues found!',
            noTextFound: 'No text found.',
            getClauseExplanation: 'Get clause explanation',
            edit: 'Edit',
            aiExplanation: 'AI Explanation',
            fixSuggestion: 'Suggested fix',
            signaturesTitle: 'Signatures',
            landlord: 'Landlord',
            tenant: 'Tenant',
            namePlaceholder: 'Name: ________________',
            idPlaceholder: 'ID: ________________',
            datePlaceholder: 'Date: ________________',
            scrollUp: 'Scroll up',
            scrollToSignatures: 'Scroll to signatures',
            up: 'Up',
            toSignatures: 'To signatures',
            editClause: 'Edit Clause',
            originalClauseLabel: 'Original clause:',
            aiFixSuggestionLabel: 'AI fix suggestion',
            applySuggestion: 'Apply suggestion',
            editLabel: 'Edit:',
            editPlaceholder: 'Edit the clause here...',
            finishEditing: 'Finish editing',
            revertToOriginal: 'Revert to original',
            cancel: 'Cancel',
            confirmRevertTitle: 'Confirm revert',
            confirmRevertMessage: 'Are you sure you want to cancel this edit and restore the original text?',
            confirmRevertYes: 'Yes, revert edit',
            confirmRevertNo: 'No, keep it',
            clearAllTitle: 'Delete all edits',
            clearAllMessage: 'Are you sure you want to delete all edits you made in this contract?',
            irreversibleWarning: 'This action cannot be undone.',
            clearAllYes: 'Yes, delete all',
        },
        // Score Breakdown
        score: {
            lowRisk: 'Low Risk',
            lowMediumRisk: 'Low-Medium Risk',
            mediumRisk: 'Medium Risk',
            mediumHighRisk: 'Medium-High Risk',
            highRisk: 'High Risk',
            financialTerms: 'Financial Terms',
            tenantRights: 'Tenant Rights',
            terminationClauses: 'Termination & Exit',
            liabilityRepairs: 'Liability & Repairs',
            legalCompliance: 'Legal Compliance',
        },
        // Contact Page
        contact: {
            title: 'We are here for you',
            subtitle: 'Have questions about your rental management? The RentGuard professional team is available to assist you with any legal or technical issue.',
            successTitle: 'Message Sent Successfully!',
            successMessage: 'We\'ll get back to you as soon as possible.',
            sendAnother: 'Send Another Message',
            fullName: 'Full Name',
            fullNamePlaceholder: 'John Smith',
            phone: 'Phone',
            phonePlaceholder: '054-7820346',
            email: 'Email',
            emailPlaceholder: 'name@company.com',
            message: 'Message',
            messagePlaceholder: 'How can we help you today?',
            sending: 'Sending...',
            sendMessage: 'Send Message',
            contactDetails: 'Contact Details',
            address: 'Address',
            addressValue: 'Or Akiva, The Legal Center, Israel',
            emailLabel: 'Email',
            emailValue: 'rentguard360@gmail.com',
            phoneLabel: 'Phone',
            phoneValue: '050-0000000',
            joinText: 'Join thousands of property owners who choose peace of mind with RentGuard.',
            defaultSubject: 'New Contact Page Inquiry',
            errorMessage: 'Failed to send message. Please try again.',
            secureCommunication: 'Secure Communication',
            fastResponse: 'Response within 24 hours',
            notCustomerYet: 'Not a customer yet?',
            registerNowFree: 'Register now for free',
            registerFreePlan: 'Register to get the free plan',
            orOption: 'Or',
            toStartAnalyzing: 'to start analyzing contracts',
        },
        methodology: {
            title: 'How is the score calculated?',
            intro1: 'The score is 5 categories x 20 pts each (total 100). Points are deducted by severity.',
            intro2: 'Cap rule: a category cannot drop below 0, so the maximum drop per category is 20 points (therefore total penalties can be higher than the actual score decrease).',
            high: 'High',
            medium: 'Medium',
            low: 'Low',
            pts: 'pts',
            categoriesHeader: '5 categories x 20 points = 100',
            catFinancial: 'Financial Terms',
            catFinancialDesc: 'Deposit, late fees, insurance',
            catRights: 'Tenant Rights',
            catRightsDesc: 'Entry rights, sublet, privacy',
            catTermination: 'Contract Termination',
            catTerminationDesc: 'Notice period, early exit',
            catLiability: 'Liability & Repairs',
            catLiabilityDesc: 'Repairs, reasonable wear and tear',
            catLegal: 'Legal Compliance',
            catLegalDesc: 'Compliance with Israeli Rental Law (2017)',
            legalSource: 'Based on the Rental and Lending Law (2017 amendment), sections 25A-25O'
        },
        // Footer
        footer: {
            tagline: 'AI-Powered Rental Contract Analysis Platform',
            benefits: 'Full Privacy | Fast & Secure Analysis | Negotiation Tips | Secure Cloud Infrastructure',
            project: 'Cloud Computing Final Project',
            copyright: '© {year} RentGuard 360. All rights reserved.',
            legalTagline: 'Smart legal protection for every rental agreement.',
            termsLink: 'Terms of Service',
            privacyLink: 'Privacy Policy',
            contactLink: 'Contact Us',
            builtBy: 'Built by',
        },
        // Contract Chat Widget
        chat: {
            title: 'RentGuard 360 Chat',
            open: 'Open contract chat',
            close: 'Close chat',
            contractLabel: 'Contract',
            selectContract: 'Select contract',
            loadingContracts: 'Loading contracts...',
            emptySelectContract: 'Choose a contract to start asking questions.',
            emptyStart: 'No messages yet. Ask your first question.',
            scope: 'Answers are based on the selected contract only. Not legal advice.',
            quickPromptsLabel: 'Quick prompt suggestions',
            promptHighRisk: 'What are the top 3 highest risks in this contract?',
            promptPets: 'Does this contract allow pets or a dog?',
            promptTermination: 'What are the termination terms and penalties?',
            inputPlaceholder: 'Ask about clauses, fees, pets, termination...',
            send: 'Send question',
            clear: 'Clear history',
            clearShort: 'Clear',
            clearConfirm: 'Clear all chat history for the selected contract? This action cannot be undone.',
            clearSuccessTitle: 'Chat history cleared',
            clearSuccessMessage: 'Removed {count} message(s) from history.',
            clearSuccessMessageGeneric: 'Chat history was cleared successfully.',
            copy: 'Copy',
            copied: 'Copied',
            you: 'You',
            assistant: 'AI Assistant',
            thinking: 'AI is analyzing the contract',
            tip: 'Tip: Ask about clauses, fees, or termination.',
            disclaimer: 'AI can be wrong. Verify key contract details.',
            showNotice: 'Show info',
            hideNotice: 'Hide info',
            noAnswer: 'No answer generated.',
            dismissHint: 'Dismiss message',
            hints: {
                rateLimit: 'You hit a temporary question limit due to load. Please wait about a minute and try again.'
            },
            rateLimitRetryIn: 'Try again in {seconds}s.',
            errors: {
                loadContracts: 'Failed to load contracts. Please retry.',
                loadHistory: 'Failed to load chat history. Please retry.',
                selectContract: 'Select a contract first.',
                askFailed: 'Could not get an answer. Please try again.',
                clearFailed: 'Failed to clear history. Please try again.'
            }
        },
        // Common
        common: {
            loading: 'Loading...',
            error: 'Error',
            success: 'Success',
            user: 'User',
            cancel: 'Cancel',
            confirm: 'Confirm',
            ok: 'OK',
            comingSoon: 'Coming Soon',
        },
        errorBoundary: {
            title: 'Something went wrong',
            message: 'Something went wrong. Please try refreshing the page.',
            reload: 'Reload Page',
            details: 'Error Details',
        },
        languageToggle: {
            switchToEnglish: 'Switch to English',
            switchToHebrew: 'Switch to Hebrew',
            heLabel: 'HE',
            enLabel: 'EN',
        },
        recommendationCard: {
            defaultTitle: 'Suggested fix',
            applied: 'Applied',
            revertTitle: 'Undo changes and restore original',
            revert: 'Revert',
            applyFix: 'Apply fix',
        },
        notifications: {
            bundleRequiredTitle: 'Select a bundle first',
            bundleRequiredMessage: 'To continue, please choose a bundle from the pricing page.',
            contactSentTitle: 'Message sent',
            contactSentMessage: 'Your message was received. We will reply soon.',
            contactFailedTitle: 'Message failed to send',
            contactFailedMessage: 'We could not send your message right now. Please try again.',
            uploadFailedTitle: 'Upload failed',
            analysisReadyTitle: 'Analysis is ready',
            analysisReadyMessage: 'Your contract has been analyzed and results are available.',
            adminUserEnabledTitle: 'User enabled',
            adminUserEnabledMessage: 'User {user} was enabled successfully.',
            adminUserEnableFailedTitle: 'Enable user failed',
            adminUserEnableFailedMessage: 'Could not enable user {user}.',
            adminUserDisabledTitle: 'User disabled',
            adminUserDisabledMessage: 'User {user} was disabled.',
            adminUserDisableFailedTitle: 'Disable user failed',
            adminUserDisableFailedMessage: 'Could not disable user {user}.',
            adminUserDeletedTitle: 'User deleted',
            adminUserDeletedMessage: 'User {user} was deleted permanently.',
            adminUserDeleteFailedTitle: 'Delete user failed',
            adminUserDeleteFailedMessage: 'Could not delete user {user}.',
        },
        // Account Settings
        account: {
            deleteAccount: 'Delete Account',
            deleteAccountDescription: 'Permanently delete your account and all your contracts',
            deleteConfirmTitle: 'Are you sure?',
            deleteConfirmMessage: 'This action will permanently delete your account, including:',
            deleteConfirmItem1: '• All your contracts',
            deleteConfirmItem2: '• All your analyses',
            deleteConfirmItem3: '• Your profile data',
            deleteConfirmWarning: 'This action cannot be undone!',
            typeDeleteToConfirm: 'Type DELETE to confirm:',
            deleteAccountSuccess: 'Account deleted successfully',
            deleteAccountError: 'Error deleting account',
            deletingAccount: 'Deleting account...',
            deletingContracts: 'Deleting contracts...',
        },
        // Admin Dashboard
        admin: {
            title: 'Admin Dashboard',
            accessDenied: 'Access Denied',
            noPermission: 'You do not have admin permissions',
            statsTab: 'Statistics',
            usersTab: 'Users',
            stripeTab: 'Stripe Insights',
            tryAgain: 'Try Again',
            // Stats
            contractsSection: 'Contracts',
            totalContracts: 'Total Contracts',
            analyzed: 'Analyzed',
            pending: 'Pending',
            failed: 'Failed',
            analysisSection: 'Analysis',
            avgRiskScore: 'Avg Risk Score',
            avgAnalysisTime: 'Avg Analysis Time',
            usersSection: 'Users',
            totalUsers: 'Total Users',
            activeUsers30: 'Active (30 days)',
            updatedAt: 'Updated',
            seconds: 'seconds',
            minutes: 'minutes',
            days: 'days',
            thisMonth: 'This Month',
            thisYear: 'This Year',
            analyzedOverTime: 'Analyzed Contracts Over Time',
            userRegistrations: 'User Registrations Over Time',
            allTime: 'All Time',
            noData: 'No data to display',
            // Users
            searchPlaceholder: 'Search by email or name...',
            search: 'Search',
            email: 'Email',
            name: 'Name',
            status: 'Status',
            joined: 'Joined',
            actions: 'Actions',
            noUsers: 'No users found',
            active: 'Active',
            pendingVerification: 'Pending verification',
            suspended: 'Suspended',
            disable: 'Disable',
            enable: 'Enable',
            delete: 'Delete',
            copyEmail: 'Copy Email',
            copied: 'Copied',
            copyFailed: 'Unable to copy email. Please select and copy manually.',
            allUsers: 'All Users',
            activeOnly: 'Active Only',
            disabledOnly: 'Disabled Only',
            showingUsers: 'Showing {count} users',
            confirmDisable: 'Are you sure you want to disable this user?',
            confirmDisableTitle: 'Disable User',
            confirmDelete: 'Are you sure you want to delete this user?',
            confirmDeleteTitle: 'Delete User',
            confirmDeleteFinal: 'This action cannot be undone! The user will be permanently deleted. Continue?',
            confirmDeleteFinalTitle: '⚠️ Final Confirmation',
            confirmDeleteBtn: 'Yes, Delete Permanently',
            selectYear: 'Select Year',
            userDeleted: 'User deleted successfully',
            // Admin Sidebar
            dashboard: 'Dashboard',
            analytics: 'Analytics',
            settings: 'Settings',
            administrator: 'Administrator',
            // Analytics Page
            analyticsDescription: 'Detailed contract analysis and risk insights',
            radarChart: 'Risk Radar',
            radarChartDesc: '5-axis risk analysis coming soon',
            sparklines: 'Trend Sparklines',
            sparklinesDesc: 'Mini trend charts coming soon',
            riskBreakdown: 'Risk Breakdown',
            riskBreakdownDesc: 'Detailed category analysis',
            riskDistribution: 'Risk Distribution',
            commonIssues: 'Common Issues in Contracts',
            code: 'Code',
            issue: 'Issue',
            count: 'Count',
            stripeInsightsTitle: 'Stripe & Billing Insights',
            stripeInsightsSubtitle: 'A full view of charges, conversion quality, revenue, and bundle data',
            generatedAt: 'Updated at',
            availableBalance: 'Available Balance',
            pendingBalance: 'Pending Balance',
            charges30Days: 'Charges (30 days)',
            disputes30Days: 'Disputes (30d)',
            intents30Days: 'Payment Intents (30 days)',
            successRate: 'Success Rate',
            refundedCharges: 'Refunded Charges',
            revenue: 'Revenue',
            avgOrderValue: 'Average Order Value',
            activeSubscribers: 'Active Subscribers',
            transactions: 'Transactions',
            bundleDistribution: 'Bundle Distribution',
            recentTransactions: 'Recent Transactions',
            bundle: 'Bundle',
            amount: 'Amount',
            currency: 'Currency',
            country: 'Country',
            stripeFeatures: 'Stripe Features',
            chargesEnabled: 'Charges Enabled',
            payoutsEnabled: 'Payouts Enabled',
            enabled: 'ON',
            disabled: 'OFF',
            refundAmount30Days: 'Refund Amount (30d)',
            intentToChargeConversion: 'Intent to Charge Conversion',
            paymentMethodMix: 'Payment Method Mix',
            noPaymentSignals: 'No payment method data yet.',
            failedCharges30Days: 'Failed Charges (30d)',
            disputeRate: 'Dispute Rate',
            refundRate: 'Refund Rate',
            chargesToIntents: 'Charges / Intents',
            topCurrencies: 'Top Currencies',
            noCurrencyAmounts: 'No currency amounts found yet.',
            stripeStatusError: 'Unable to fetch Stripe runtime details right now',
            // Settings Page
            settingsDescription: 'System configuration and preferences',
            notifications: 'Notifications',
            notificationsDesc: 'Configure email and push notifications',
            security: 'Security',
            securityDesc: 'Authentication and access control',
            dataRetention: 'Data Retention',
            dataRetentionDesc: 'Contract storage and backup settings',
            emailTemplates: 'Email Templates',
            emailTemplatesDesc: 'Customize notification emails',
            comingSoon: 'Coming Soon',
        },
        // Pricing Page
        pricing: {
            title: 'Choose Your Bundle',
            subtitle: 'Select the bundle that best fits your needs and start analyzing rental contracts with AI',
            currentPlan: 'Current Bundle:',
            scansLeft: 'scans left',
            unlimited: 'Unlimited',
            mostPopular: 'Most Popular',
            yourPlan: 'Your Bundle',
            currentPlanBtn: 'Current Bundle',
            getStarted: 'Get Started Free',
            subscribe: 'Purchase',
            buyMoreScans: 'Buy more scans',
            free: 'Free',
            single: 'Single',
            basic: 'Basic',
            pro: 'Pro',
            month: 'month',
            scans: 'scans',
            unlimitedScans: '15 scans',
            freeDesc: 'Try RentGuard for free',
            singleDesc: 'Analyze one contract in depth',
            basicDesc: 'Perfect for occasional use',
            proDesc: 'Best value for frequent users',
            featuresFree: ['1 contract scan', 'Full AI analysis', 'Detailed risk score', 'No commitment trial'],
            featuresSingle: ['1 contract scan', 'Full AI analysis', 'Detailed risk score', 'PDF & Word export'],
            featuresBasic: ['5 contract scans', 'Full AI analysis', 'Detailed risk score', 'Negotiation tips', 'PDF & Word export'],
            featuresPro: ['15 contract scans', 'Full AI analysis', 'Detailed risk score', 'Negotiation tips', 'PDF & Word export', 'Priority support'],
        },
        // Checkout Page
        checkout: {
            title: 'Complete Purchase',
            backToPricing: 'Back to Bundles',
            orderSummary: 'Order Summary',
            plan: 'Bundle',
            scans: 'Scans',
            total: 'Total',
            paymentMethod: 'Payment Method',
            cardDetails: 'Card details',
            pay: 'Pay',
            processing: 'Processing...',
            securedByStripe: 'Secured by Stripe',
            testMode: 'Test mode — use card',
            termsLabel: 'I agree to the ',
            termsLinkTerms: 'Terms of Service',
            termsJoin: ' and ',
            termsLinkPrivacy: 'Privacy Policy',
            termsLinkText: 'Terms of Service and Privacy Policy',
            termsDisclaimer: '. I understand this is a one-time purchase of a scan bundle and no recurring charges will apply.',
            termsRequired: 'You must agree to the Terms of Service to proceed',
        },
        // Payment Success Page
        paymentSuccess: {
            title: 'Payment Successful',
            freeActivated: 'Your free bundle has been activated. You can start scanning contracts now.',
            paymentCompleted: 'Your payment was processed successfully and your bundle has been updated.',
            plan: 'Bundle',
            amount: 'Amount',
            hint: 'You can start scanning rental contracts right away.',
            goToDashboard: 'Go to Dashboard',
            uploadContract: 'Upload Contract',
        },
        // Subscription
        subscription: {
            myPlan: 'My Bundle',
            scansRemaining: 'scans remaining',
            unlimited: 'Unlimited',
            noPlan: 'No Bundle',
            upgrade: 'Upgrade',
            choosePlan: 'Choose a Bundle',
            noActivePlan: 'No Active Bundle',
            noActivePlanMessage: 'To upload and scan a contract, activate a bundle first.',
            noScansLeft: 'No Scans Remaining',
            noScansMessage: 'Upgrade your bundle to continue scanning contracts.',
            upgradePlan: 'Upgrade Bundle',
        },
        // Billing Page
        billing: {
            title: 'Billing & Payments',
            subtitle: 'Manage your payment methods, view invoices and billing history in one secure place.',
            currentPlan: 'Current Plan',
            scansRemaining: 'scans remaining',
            unlimited: 'Unlimited',
            noPlan: 'No active plan',
            upgradePlan: 'Upgrade Plan',
            portalTitle: 'Manage Payment Methods & Invoices',
            portalDesc: 'Update your credit card, download PDF invoices and view your complete payment history.',
            portalButton: 'Manage Payment Methods & Billing History',
            portalLoading: 'Preparing secure link...',
            portalError: 'Could not open the billing portal. Please try again.',
            feature1Title: 'Update Payment Methods',
            feature1Desc: 'Add or replace your credit card securely.',
            feature2Title: 'Download Invoices',
            feature2Desc: 'Download detailed invoices in PDF format.',
            feature3Title: 'Payment History',
            feature3Desc: 'View all your transactions and payments.',
            poweredByStripe: 'Powered by Stripe',
            securityNote: 'All your data is encrypted and secured at industry level.',
            backToSettings: 'Back to Settings',
        },
        // Terms of Service
        terms: {
            title: 'Terms of Service',
            updated: 'Last updated: March 2026',
            tocTitle: 'Table of Contents',
            contactPrefix: 'For additional questions, reach us via the',
            contactLinkText: 'Contact page',
            contactMiddle: 'or email us at',
            sections: [
                {
                    id: 'acceptance',
                    title: '1. Acceptance of Terms',
                    content: 'By using the RentGuard 360 website and services, you agree to these Terms of Service. If you do not agree, please refrain from using our services.',
                },
                {
                    id: 'service',
                    title: '2. Service Description',
                    content: 'RentGuard 360 provides AI-powered rental contract analysis. The service includes:',
                    list: [
                        'Automated scanning of rental contracts in PDF format',
                        'Identification of problematic clauses and conflicts of interest',
                        'Detailed risk scoring for each clause',
                        'Recommendations and suggested amendments',
                        'Report export in PDF and Word formats',
                    ],
                },
                {
                    id: 'purchases',
                    title: '3. Purchases & Payments',
                    content: 'All purchases on the site are one-time purchases of scan bundles. There is no recurring billing or auto-renewing subscriptions. Payments are processed through Stripe and are secured according to PCI DSS standards. RentGuard 360 does not store your credit card details — all sensitive information is handled directly by Stripe.',
                },
                {
                    id: 'refund',
                    title: '4. Refund Policy',
                    content: 'Since the service provides instant analysis upon purchase, refunds are only issued in exceptional circumstances (e.g., a technical failure that prevented the system from completing the analysis). For refund requests, please contact us through the Contact page.',
                },
                {
                    id: 'data',
                    title: '5. Data Storage & Privacy',
                    content: 'We are committed to protecting your privacy. Key points:',
                    list: [
                        'Uploaded contracts are stored encrypted on AWS servers',
                        'Information is used solely to provide the requested service',
                        'We do not sell or share personal data with third parties',
                        'You may request deletion of your data at any time',
                        'We use only essential cookies for site operation',
                    ],
                },
                {
                    id: 'security',
                    title: '6. Data Security',
                    content: 'We implement advanced security measures to protect your information, including SSL/TLS encryption, encrypted storage, multi-factor authentication (MFA), and continuous security monitoring. Our servers are hosted on AWS and comply with international security standards.',
                },
                {
                    id: 'disclaimer',
                    title: '7. Limitation of Liability',
                    content: 'The analysis provided by RentGuard 360 is for informational purposes only and does not constitute legal advice. It is strongly recommended to consult with a lawyer before signing any contract. RentGuard 360 is not liable for decisions made based solely on the analysis.',
                },
                {
                    id: 'ip',
                    title: '8. Intellectual Property',
                    content: 'All rights in the service, including design, code, algorithms, and content, belong to RentGuard 360. No part of the service may be copied, distributed, or reproduced without written permission.',
                },
                {
                    id: 'changes',
                    title: '9. Changes to Terms',
                    content: 'We reserve the right to update these terms from time to time. Material changes will be published on the site and/or sent by email. Continued use of the service after terms are updated constitutes acceptance of the updated terms.',
                },
                {
                    id: 'contact',
                    title: '10. Contact Us',
                    content: 'For questions regarding these Terms of Service or any other matter, please contact us through the Contact page on the site or by email.',
                },
            ]
        },
        // Privacy Policy
        privacy: {
            title: 'Privacy Policy',
            updated: 'Last updated: March 2026',
            tocTitle: 'Table of Contents',
            contactPrefix: 'For privacy-related questions, reach us via the',
            contactLinkText: 'Contact page',
            contactMiddle: 'or email us at',
            sections: [
                {
                    id: 'general',
                    title: '1. General Overview',
                    content: 'At RentGuard 360 ("Company", "we", or "our"), we respect your privacy and are committed to protecting it. This Privacy Policy outlines how we collect, use, and safeguard your personal information when you use our website and services.'
                },
                {
                    id: 'collection',
                    title: '2. Information Collection',
                    content: 'We collect various types of information to provide our services:',
                    list: [
                        'Registration and contact details (email address, full name).',
                        'Financial information is processed securely by authorized third-party payment gateways (e.g., Stripe); we do not store your credit card information on our servers.',
                        'Agreements and documents you choose to upload (for analysis through our AI systems).'
                    ]
                },
                {
                    id: 'usage',
                    title: '3. Use of Information',
                    content: 'The collected information is used solely for the following purposes:',
                    list: [
                        'Providing automated document analysis services and improving your user experience.',
                        'Managing user accounts and providing customer or technical support.',
                        'Sending service notifications (such as system updates or report completions) – no marketing content will be sent without explicit consent.'
                    ]
                },
                {
                    id: 'sharing',
                    title: '4. Sharing Information with Third Parties',
                    content: 'We do not sell, trade, or transfer Personally Identifiable Information to outside parties for marketing purposes. We may share information with trusted third-party service providers (e.g., AWS, payment processors) acting on our behalf, provided that they agree to keep this information confidential and comply with our stringent privacy standards.'
                },
                {
                    id: 'ai-processing',
                    title: '5. AI Data Processing',
                    content: 'Agreements you upload to the system are processed by Large Language Models (LLMs). Before the analysis, we employ text extraction and data masking mechanisms designed to redact potentially sensitive personal data (such as national IDs or phone numbers), to better safeguard your privacy.'
                },
                {
                    id: 'data-retention',
                    title: '6. Data Retention and Deletion',
                    content: 'The documents uploaded for scanning are securely encrypted and retained in your account. You can request the deletion of your documents or even delete your entire account through the settings dashboard or by contacting support. Once requested, your data will be permanently removed from our active servers in compliance with applicable laws.'
                },
                {
                    id: 'cookies',
                    title: '7. Cookies',
                    content: 'We use cookies strictly for managing your authenticated sessions and ensuring the proper functioning of the site. While you may disable cookies in your browser settings, doing so will impact the functionality of areas requiring user login.'
                },
                {
                    id: 'contact',
                    title: '8. Contacting Us',
                    content: 'If you have any questions regarding this Privacy Policy or wish to review, update, or remove your personal data, please reach out to us using the contact details provided on our site.'
                }
            ]
        },
    },
};

const translateFromLanguage = (language, key) => {
    const keys = String(key || '').split('.');
    let value = translations[language] || translations.he;
    for (const k of keys) {
        value = value?.[k];
    }
    return value || key;
};

const defaultLanguageContext = {
    language: 'he',
    setLanguage: () => {},
    t: (key) => translateFromLanguage('he', key),
    toggleLanguage: () => {},
    isRTL: true,
    translations: translations.he,
};

// Create context
const LanguageContext = createContext(defaultLanguageContext);

// Provider component
export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        // Get saved language or default to Hebrew
        const saved = localStorage.getItem('rentguard-language');
        return saved || 'he';
    });

    useEffect(() => {
        // Save language preference
        localStorage.setItem('rentguard-language', language);
        // Update document direction
        document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    const t = (key) => translateFromLanguage(language, key);

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'he' ? 'en' : 'he');
    };

    const isRTL = language === 'he';

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage,
            t,
            toggleLanguage,
            isRTL,
            translations: translations[language]
        }}>
            {children}
        </LanguageContext.Provider>
    );
};

// Custom hook
export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === defaultLanguageContext && import.meta.env.DEV) {
        console.warn('useLanguage fallback is active. Wrap components with LanguageProvider to avoid missing translations.');
    }
    return context;
};

export default LanguageContext;
