import React, { createContext, useContext, useState, useEffect } from 'react';

// Translations object
const translations = {
    he: {
        // Navigation
        nav: {
            dashboard: 'לוח בקרה',
            upload: 'העלאה',
            contracts: 'חוזים',
            settings: 'הגדרות',
            contact: 'צור קשר',
            logout: 'התנתקות',
            admin: '⚙️ ניהול',
            dark: 'כהה',
            light: 'בהיר',
            backToDashboard: 'חזרה לדף הבית',
        },
        // Auth (Login/Register)
        auth: {
            login: 'התחברות',
            register: 'הרשמה',
            email: 'אימייל',
            password: 'סיסמה',
            fullName: 'שם מלא',
            passwordHint: 'לפחות 8 תווים, אות גדולה ומספר',
            loginButton: 'התחברות',
            registerButton: 'יצירת חשבון',
            noAccount: 'אין לך חשבון?',
            hasAccount: 'יש לך כבר חשבון?',
            confirmTitle: 'אימות אימייל',
            confirmMessage: 'שלחנו קוד לכתובת',
            confirmCode: 'קוד אימות',
            confirmButton: 'אימות',
            // DAN DID IT - Added verification success message
            verificationSuccess: 'אימות הצליח!',
            verificationSuccessMessage: 'אל תשכח לאמת את האימייל שלך כדי להשתמש באתר',
            continueToLogin: 'המשך להתחברות',
            // DAN DID IT - Added Hebrew translations for forgot password feature
            forgotPassword: 'שכחת סיסמה?',
            forgotPasswordTitle: 'איפוס סיסמה',
            forgotPasswordMessage: 'הזן את כתובת האימייל שלך ונשלח לך קוד איפוס',
            sendCodeButton: 'שלח קוד',
            resetPasswordTitle: 'הגדרת סיסמה חדשה',
            resetPasswordMessage: 'שלחנו קוד איפוס לכתובת',
            newPassword: 'סיסמה חדשה',
            resetCodePlaceholder: 'קוד איפוס',
            resetPasswordButton: 'אפס סיסמה',
            backToLogin: 'חזרה להתחברות',
            // Landing page content
            heroTitle: 'ניתוח חוזי שכירות בבינה מלאכותית',
            heroSubtitle: 'העלו את חוזה השכירות שלכם וקבלו ניתוח מפורט של:',
            heroBenefit1: 'סעיפים בעייתיים וסיכונים משפטיים',
            heroBenefit2: 'ציון סיכון כולל (0-100)',
            heroBenefit3: 'טיפים למשא ומתן',
            heroFeatures: 'עברית מלאה 🇮🇱 | ניתוח תוך 60 שניות ⚡ | פרטיות מלאה 🔒',
            // Benefits carousel
            benefitCloud: 'מבוסס ענן AWS',
            benefitCloudDesc: 'תשתית ברמה ארגונית עם זמינות של 99.99%. המסמכים שלך מעובדים בבטחה בענן.',
            benefitAI: 'בינה מלאכותית מתקדמת',
            benefitAIDesc: 'מופעל על ידי Amazon Bedrock - אחת ממערכות ה-AI החכמות ביותר הקיימות היום.',
            benefitSecurity: 'אבטחה ברמת בנק',
            benefitSecurityDesc: 'הצפנה מקצה לקצה. המידע האישי שלך מוסתר אוטומטית לפני ניתוח ה-AI. אפס שמירת מידע.',
            benefitFast: 'ניתוח AI מהיר',
            benefitFastDesc: 'חוזים פשוטים? תוך פחות מדקה. חוזים מורכבים? מספר דקות. הבינה המלאכותית שלנו סורקת כל סעיף לעומק.',
            // Demo steps
            demoTitle: 'איך זה עובד?',
            demoStep1: 'העלאת PDF',
            demoStep1Desc: 'העלו את חוזה השכירות שלכם בפורמט PDF. אנחנו תומכים בעברית ואנגלית.',
            demoStep2: 'ניתוח AI',
            demoStep2Desc: 'ה-AI שלנו סורק סיכונים, תנאים לא הוגנים ובעיות משפטיות.',
            demoStep3: 'קבלת תוצאות',
            demoStep3Desc: 'צפו בציון הסיכון, הסברים לבעיות וטיפים למשא ומתן.',
            // Features
            featureAI: '🤖 ניתוח AI',
            featureAIDesc: 'מופעל על ידי Amazon Bedrock לניתוח חוזים כמו מומחה משפטי',
            featurePrivacy: '🔒 פרטיות במקום ראשון',
            featurePrivacyDesc: 'מידע אישי (ת.ז., טלפון, אימייל) מוסתר אוטומטית לפני הניתוח',
            featureTips: '💡 טיפים חכמים',
            featureTipsDesc: 'קבלו עצות ספציפיות למשא ומתן על כל סעיף בעייתי',
            // Footer
            footerTagline: 'הגנה על החוזה שלך עם בינה מלאכותית מתקדמת',
            footerSupport: 'צריכים עזרה? שלחו לנו מייל:',
            footerEmail: 'projForruppin@gmail.com',
            footerResponse: 'תגובה תוך 24 שעות | הצוות שלנו מוכנים להגן עליכם כמו שאנחנו מגנים על החוזה שלכם',
            projectName: '💻 פרויקט סיום מחשוב ענן',
        },
        // Dashboard
        dashboard: {
            greeting: {
                morning: 'בוקר טוב',
                afternoon: 'צהריים טובים',
                evening: 'ערב טוב',
            },
            totalContracts: 'סה"כ חוזים',
            analyzed: 'נותחו',
            pending: 'ממתינים',
            highRisk: 'סיכון גבוה',
            uploadContract: 'העלאת חוזה',
            uploadDescription: 'העלו חוזה שכירות חדש לניתוח AI',
            uploadPDF: 'העלאת PDF',
            viewContracts: 'צפייה בחוזים',
            viewDescription: 'עיינו בכל החוזים שהעליתם',
            viewAll: 'צפייה בכולם',
            howToStart: 'איך מתחילים',
            step1Title: 'העלאת חוזה',
            step1Desc: 'גררו ושחררו את חוזה השכירות בפורמט PDF',
            step2Title: 'ניתוח AI',
            step2Desc: 'חוזים פשוטים? תוך פחות מדקה. חוזים מורכבים? מספר דקות. הבינה המלאכותית שלנו סורקת כל סעיף לעומק.',
            step3Title: 'קבלת תובנות',
            step3Desc: 'צפו בסיכונים והצעות למשא ומתן',
            whyUs: 'למה דווקא RentGuard 360?',
            whyUsSubtitle: 'לא סתם עוד צ\'אט בוט - מערכת מקצועית שנבנתה במיוחד לניתוח חוזי שכירות',
            featurePrivacy: 'הגנה על הפרטיות',
            featurePrivacyDesc: 'המערכת מזהה ומצנזרת אוטומטית מידע אישי (ת.ז., טלפון, כתובת) לפני שליחה ל-AI. הפרטים שלכם נשארים פרטיים.',
            featurePrompt: 'פרומפט מקצועי מותאם',
            featurePromptDesc: 'בניגוד לשליחה לצ\'אט רגיל, המערכת שלנו משתמשת בפרומפט מיוחד שמנתח 70+ גורמי סיכון על פי חוק השכירות הישראלי.',
            featureScore: 'ציון סיכון מבוסס נתונים',
            featureScoreDesc: 'מקבלים ציון אובייקטיבי 0-100 עם פירוט לפי קטגוריות: תנאים כספיים, זכויות הדייר, אחריות ותיקונים ועוד.',
            featureTips: 'טיפים למשא ומתן',
            featureTipsDesc: 'לא רק מזהים בעיות - מקבלים הצעות קונקרטיות לתיקון סעיפים בעייתיים שתוכלו להציג לבעל הדירה.',
            featureAws: 'תשתית ענן מאובטחת',
            featureAwsDesc: 'רץ על AWS עם הצפנה מקצה לקצה. החוזים שלכם לא נשמרים ונמחקים אוטומטית לאחר הניתוח.',
        },
        // Contracts Page
        contracts: {
            title: 'החוזים שלי',
            subtitle: 'ניהול וצפייה בכל חוזי השכירות שלך',
            refresh: 'רענון',
            uploadContract: 'העלאת חוזה',
            noContracts: 'אין חוזים עדיין',
            noContractsDesc: 'העלו את חוזה השכירות הראשון שלכם לניתוח',
            uploadFirst: 'העלאת חוזה ראשון',
            deleteTitle: 'מחיקת חוזה',
            deleteConfirm: 'האם אתה בטוח שברצונך למחוק חוזה זה? פעולה זו לא ניתנת לביטול.',
            cancel: 'ביטול',
            delete: 'מחיקה',
            deleting: 'מוחק...',
            editTitle: 'עריכת פרטים',
            fileName: 'שם קובץ',
            propertyAddress: 'כתובת הנכס',
            landlordName: 'שם המשכיר',
            save: 'שמירה',
            saving: 'שומר...',
            loading: 'טוען חוזים...',
            lowRisk: 'סיכון נמוך',
            lowMediumRisk: 'סיכון נמוך-בינוני',
            mediumRisk: 'סיכון בינוני',
            highRisk: 'סיכון גבוה',
            analyzed: 'הושלם',
            pendingAnalysis: 'ממתין',
            notSpecified: 'לא צוין',
            exportWord: 'ייצוא Word',
            exportPDF: 'ייצוא PDF',
            viewAnalysis: 'צפייה בניתוח',
            sortBy: 'מיון לפי:',
            sortDate: 'תאריך',
            sortScore: 'ציון סיכון',
            uploadDate: 'תאריך העלאה',
        },
        // Upload Page
        upload: {
            title: 'העלאת חוזה',
            subtitle: 'העלו את חוזה השכירות שלכם לניתוח AI',
            dragDrop: 'שחררו את ה-PDF כאן',
            or: 'או לחצו לבחירת קובץ',
            selectFile: 'בחירת קבצים',
            maxSize: 'גודל מקסימלי: 5MB | PDF בלבד',
            termsLabel: 'אני מאשר/ת שקראתי והבנתי את',
            termsLink: 'תנאי השימוש ומדיניות הפרטיות',
            uploadBtn: 'העלאת חוזה לניתוח',
            uploading: 'מעלה...',
            complete: 'הושלם!',
            uploadSuccess: 'ההעלאה הצליחה!',
            analyzing: 'ה-AI מנתח את החוזה שלכם (30-60 שניות)...',
            uploadedToServer: '✓ החוזה הועלה לשרת',
            analysisStarted: '✓ הניתוח התחיל',
            viewMyContracts: 'צפייה בחוזים שלי',
            uploadAnother: 'העלאת חוזה נוסף',
            // DAN DID IT - Added email notification message
            uploadSuccessTitle: 'החוזה הועלה בהצלחה!',
            uploadSuccessMessage: 'תוצאות הניתוח של החוזה שלך ישלחו לאימייל שלך',
            goToContracts: 'עבור לחוזים שלי',
            contractDetails: 'פרטי החוזה (אופציונלי)',
            propertyAddress: 'כתובת הנכס',
            addressPlaceholder: 'רחוב ראשי 123, עיר',
            landlordName: 'שם המשכיר',
            landlordPlaceholder: 'ישראל ישראלי',
            contractName: 'שם החוזה',
            termsTitle: 'תנאי שימוש ומדיניות פרטיות',
            terms1Title: '1. הסכמה לתנאים',
            terms1Content: 'בהעלאת מסמכים למערכת RentGuard 360, אתם מסכימים לתנאי השימוש הבאים:',
            terms2Title: '2. שימוש במידע',
            terms2Content: 'המסמכים שתעלו יעובדו באמצעות טכנולוגיית AI לצורך ניתוח חוזי שכירות. המידע ישמש אך ורק לצורך מתן השירות המבוקש.',
            terms3Title: '3. אבטחת מידע',
            terms3Content: 'אנו מתחייבים לשמור על המידע שלכם בהתאם לתקני אבטחה מחמירים. המסמכים מאוחסנים בצורה מוצפנת בשרתי AWS.',
            terms4Title: '4. שמירת מידע',
            terms4Content: 'המידע יישמר למשך הזמן הנדרש לספק את השירות ובהתאם לדרישות החוק.',
            terms5Title: '5. הגבלת אחריות',
            terms5Content: 'הניתוח המוצע על ידי המערכת הינו לצורכי מידע בלבד ואינו מהווה ייעוץ משפטי. מומלץ להתייעץ עם עורך דין לפני חתימה על חוזה.',
            terms6Title: '6. זכויות המשתמש',
            terms6Content: 'באפשרותכם לבקש מחיקת המידע שלכם בכל עת באמצעות פנייה לתמיכה.',
            iAgree: 'קראתי ואני מסכים/ה',
            close: 'סגור',
            pdfOnly: 'רק קבצי PDF מותרים',
            fileTooLarge: 'גודל הקובץ חייב להיות פחות מ-5MB',
            fileTooSmall: 'הקובץ קטן מדי - ייתכן שהוא ריק או פגום',
            fileNameTooLong: 'שם הקובץ ארוך מדי (מקסימום 100 תווים)',
            uploadFailed: 'ההעלאה נכשלה. נסו שוב.',
        },
        // Analysis Page
        analysis: {
            title: 'ניתוח חוזה',
            backToContracts: 'חזרה לחוזים',
            summary: 'סיכום',
            scoreBreakdown: 'פירוט הציון',
            refresh: 'רענון',
            export: 'ייצוא',
            issues: 'בעיות שזוהו',
            noIssues: 'לא נמצאו בעיות בחוזה זה',
            original: 'מקור',
            problem: 'הבעיה',
            recommendation: 'המלצה',
            copyFix: 'העתק תיקון',
            copied: 'הועתק!',
            askAI: 'שאל את ה-AI',
            loading: 'טוען ניתוח...',
            analyzing: 'מנתח את החוזה...',
            notContract: 'מסמך זה לא נראה כחוזה שכירות',
        },
        // Score Breakdown
        score: {
            lowRisk: 'סיכון נמוך',
            lowMediumRisk: 'סיכון נמוך-בינוני',
            mediumRisk: 'סיכון בינוני',
            mediumHighRisk: 'סיכון בינוני-גבוה',
            highRisk: 'סיכון גבוה',
            financialTerms: 'תנאים כספיים',
            tenantRights: 'זכויות הדייר',
            terminationClauses: 'סיום ויציאה',
            liabilityRepairs: 'אחריות ותיקונים',
            legalCompliance: 'עמידה בחוק',
        },
        // Footer
        footer: {
            tagline: 'פלטפורמת ניתוח חוזי שכירות מבוססת AI',
            benefits: 'פרטיות מלאה | ניתוח מהיר ומאובטח | טיפים למשא ומתן | תשתית ענן מאובטחת',
            project: 'פרויקט סיום מחשוב ענן',
            copyright: '© RentGuard 360 {year} . כל הזכויות שמורות.',
        },
        // Common
        common: {
            loading: 'טוען...',
            error: 'שגיאה',
            success: 'הצלחה',
            user: 'משתמש',
            cancel: 'ביטול',
            confirm: 'אישור',
            ok: 'אישור',
            comingSoon: 'בקרוב',
        },
        // DAN DID IT - Added account deletion translations
        // Account Settings
        account: {
            deleteAccount: 'מחק חשבון',
            deleteAccountDescription: 'מחיקת החשבון שלך לצמיתות כולל כל החוזים שלך',
            deleteConfirmTitle: 'האם אתה בטוח?',
            deleteConfirmMessage: 'פעולה זו תמחק את החשבון שלך לצמיתות, כולל:',
            deleteConfirmItem1: '• כל החוזים שלך',
            deleteConfirmItem2: '• כל הניתוחים שלך',
            deleteConfirmItem3: '• נתוני הפרופיל שלך',
            deleteConfirmWarning: 'פעולה זו לא ניתנת לביטול!',
            typeDeleteToConfirm: 'הקלד DELETE כדי לאשר:',
            deleteAccountSuccess: 'החשבון נמחק בהצלחה',
            deleteAccountError: 'שגיאה במחיקת החשבון',
            deletingAccount: 'מוחק חשבון...',
            deletingContracts: 'מוחק חוזים...',
        },
        // Admin Dashboard
        admin: {
            title: 'לוח בקרה למנהל',
            accessDenied: 'גישה נדחתה',
            noPermission: 'אין לך הרשאות מנהל',
            statsTab: 'סטטיסטיקות',
            usersTab: 'משתמשים',
            tryAgain: 'נסה שוב',
            // Stats
            contractsSection: 'חוזים',
            totalContracts: 'סה״כ חוזים',
            analyzed: 'נותחו',
            pending: 'ממתינים',
            failed: 'נכשלו',
            analysisSection: 'ניתוח',
            avgRiskScore: 'ציון סיכון ממוצע',
            avgAnalysisTime: 'זמן ניתוח ממוצע',
            usersSection: 'משתמשים',
            totalUsers: 'סה״כ משתמשים',
            activeUsers30: 'פעילים (30 יום)',
            updatedAt: 'עודכן',
            seconds: 'שניות',
            minutes: 'דקות',
            days: 'ימים',
            thisMonth: 'החודש',
            thisYear: 'השנה',
            analyzedOverTime: 'חוזים שנותחו לאורך זמן',
            userRegistrations: 'רישום משתמשים לאורך זמן',
            noData: 'אין נתונים להצגה',
            // Users
            searchPlaceholder: 'חפש לפי אימייל או שם...',
            search: 'חפש',
            email: 'אימייל',
            name: 'שם',
            status: 'סטטוס',
            joined: 'הצטרף',
            actions: 'פעולות',
            noUsers: 'לא נמצאו משתמשים',
            active: 'פעיל',
            suspended: 'מושעה',
            disable: 'השעה',
            enable: 'הפעל',
            delete: 'מחק',
            allUsers: 'כל המשתמשים',
            activeOnly: 'פעילים בלבד',
            disabledOnly: 'מושעים בלבד',
            showingUsers: 'מציג {count} משתמשים',
            confirmDisable: 'האם אתה בטוח שברצונך להשעות משתמש זה?',
            confirmDisableTitle: 'השעיית משתמש',
            confirmDelete: 'האם אתה בטוח שברצונך למחוק משתמש זה?',
            confirmDeleteTitle: 'מחיקת משתמש',
            confirmDeleteFinal: 'פעולה זו אינה ניתנת לביטול! המשתמש יימחק לצמיתות. האם להמשיך?',
            confirmDeleteFinalTitle: '⚠️ אישור סופי',
            confirmDeleteBtn: 'כן, מחק לצמיתות',
            selectYear: 'בחר שנה',
            userDeleted: 'המשתמש נמחק בהצלחה',
            // Admin Sidebar
            dashboard: 'לוח בקרה',
            analytics: 'אנליטיקות',
            settings: 'הגדרות',
            administrator: 'מנהל',
            // Analytics Page
            analyticsDescription: 'ניתוח חוזים מפורט ותובנות סיכון',
            radarChart: 'רדאר סיכונים',
            radarChartDesc: 'ניתוח סיכונים ב-5 צירים בקרוב',
            sparklines: 'גרפי מגמות',
            sparklinesDesc: 'גרפי מגמות מיני בקרוב',
            riskBreakdown: 'פירוט סיכונים',
            riskBreakdownDesc: 'ניתוח קטגוריות מפורט',
            riskDistribution: 'התפלגות סיכונים',
            commonIssues: 'בעיות נפוצות בחוזים',
            code: 'קוד',
            issue: 'בעיה',
            count: 'כמות',
            // Settings Page
            settingsDescription: 'הגדרות מערכת והעדפות',
            notifications: 'התראות',
            notificationsDesc: 'הגדרת התראות אימייל ופוש',
            security: 'אבטחה',
            securityDesc: 'אימות ובקרת גישה',
            dataRetention: 'שמירת מידע',
            dataRetentionDesc: 'הגדרות אחסון וגיבוי חוזים',
            emailTemplates: 'תבניות אימייל',
            emailTemplatesDesc: 'התאמה אישית של אימיילים',
            comingSoon: 'בקרוב',
        },
    },
    en: {
        // Navigation
        nav: {
            dashboard: 'Dashboard',
            upload: 'Upload',
            contracts: 'Contracts',
            settings: 'Settings',
            contact: 'Contact',
            logout: 'Logout',
            admin: '⚙️ Admin',
            dark: 'Dark',
            light: 'Light',
            backToDashboard: 'Back to Dashboard',
        },
        // Auth (Login/Register)
        auth: {
            login: 'Login',
            register: 'Sign Up',
            email: 'Email',
            password: 'Password',
            fullName: 'Full Name',
            passwordHint: 'At least 8 characters, uppercase and number',
            loginButton: 'Login',
            registerButton: 'Create Account',
            noAccount: "Don't have an account?",
            hasAccount: 'Already have an account?',
            confirmTitle: 'Email Verification',
            confirmMessage: 'We sent a code to',
            confirmCode: 'Verification Code',
            confirmButton: 'Verify',
            // DAN DID IT - Added verification success message (English)
            verificationSuccess: 'Verification Successful!',
            verificationSuccessMessage: "Don't forget to verify your email to use the website",
            continueToLogin: 'Continue to Login',
            // DAN DID IT - Added English translations for forgot password feature
            forgotPassword: 'Forgot password?',
            forgotPasswordTitle: 'Reset Password',
            forgotPasswordMessage: 'Enter your email address and we will send you a reset code',
            sendCodeButton: 'Send Code',
            resetPasswordTitle: 'Set New Password',
            resetPasswordMessage: 'We sent a reset code to',
            newPassword: 'New Password',
            resetCodePlaceholder: 'Reset Code',
            resetPasswordButton: 'Reset Password',
            backToLogin: 'Back to Login',
            // Landing page content
            heroTitle: 'AI-Powered Rental Contract Analysis',
            heroSubtitle: 'Upload your rental contract and get a detailed analysis of:',
            heroBenefit1: 'Problematic clauses and legal risks',
            heroBenefit2: 'Overall risk score (0-100)',
            heroBenefit3: 'Negotiation tips',
            heroFeatures: 'Full Hebrew Support 🇮🇱 | Analysis in 60 seconds ⚡ | Full Privacy 🔒',
            // Benefits carousel
            benefitCloud: 'AWS Cloud-Based',
            benefitCloudDesc: 'Enterprise-grade infrastructure with 99.99% availability. Your documents are processed securely in the cloud.',
            benefitAI: 'Advanced AI',
            benefitAIDesc: 'Powered by Amazon Bedrock - one of the most intelligent AI systems available today.',
            benefitSecurity: 'Bank-Level Security',
            benefitSecurityDesc: 'End-to-end encryption. Your personal data is automatically masked before AI analysis. Zero data retention.',
            benefitFast: 'Lightning-Fast AI Analysis',
            benefitFastDesc: 'Simple contracts? Under 60 seconds. Complex ones? Just a few minutes. Our advanced AI scans every clause for your protection.',
            // Demo steps
            demoTitle: 'How it Works',
            demoStep1: 'Upload PDF',
            demoStep1Desc: 'Upload your rental contract in PDF format. We support Hebrew and English.',
            demoStep2: 'AI Analysis',
            demoStep2Desc: 'Our AI scans for risks, unfair terms, and legal issues.',
            demoStep3: 'Get Results',
            demoStep3Desc: 'View risk score, issue explanations, and negotiation tips.',
            // Features
            featureAI: '🤖 AI Analysis',
            featureAIDesc: 'Powered by Amazon Bedrock for contract analysis like a legal expert',
            featurePrivacy: '🔒 Privacy First',
            featurePrivacyDesc: 'Personal info (ID, phone, email) is automatically masked before analysis',
            featureTips: '💡 Smart Tips',
            featureTipsDesc: 'Get specific negotiation advice for each problematic clause',
            // Footer
            footerTagline: 'Protecting your lease with cutting-edge AI',
            footerSupport: 'Need help? Drop us a line:',
            footerEmail: 'projForruppin@gmail.com',
            footerResponse: 'Response within 24 hours | Our team is as dedicated to helping you as we are to analyzing your contracts',
            projectName: '💻 Cloud Computing Final Project',
        },
        // Dashboard
        dashboard: {
            greeting: {
                morning: 'Good morning',
                afternoon: 'Good afternoon',
                evening: 'Good evening',
            },
            totalContracts: 'Total Contracts',
            analyzed: 'Analyzed',
            pending: 'Pending',
            highRisk: 'High Risk',
            uploadContract: 'Upload Contract',
            uploadDescription: 'Upload a new rental contract for AI analysis',
            uploadPDF: 'Upload PDF',
            viewContracts: 'View Contracts',
            viewDescription: 'Review all your uploaded contracts',
            viewAll: 'View All',
            howToStart: 'How to Start',
            step1Title: 'Upload Contract',
            step1Desc: 'Drag and drop your rental contract in PDF format',
            step2Title: 'AI Analysis',
            step2Desc: 'Simple contracts? Under 60 seconds. Complex ones? Just a few minutes. Our advanced AI scans every clause for your protection.',
            step3Title: 'Get Insights',
            step3Desc: 'View risks and negotiation suggestions',
            whyUs: 'Why RentGuard 360?',
            whyUsSubtitle: 'Not just another chatbot - a professional system built specifically for rental contract analysis',
            featurePrivacy: 'Privacy Protection',
            featurePrivacyDesc: 'The system automatically detects and redacts personal information (ID, phone, address) before sending to AI. Your details stay private.',
            featurePrompt: 'Custom Professional Prompt',
            featurePromptDesc: 'Unlike sending to a regular chat, our system uses a specialized prompt that analyzes 70+ risk factors according to Israeli rental law.',
            featureScore: 'Data-Driven Risk Score',
            featureScoreDesc: 'Get an objective score 0-100 with breakdown by categories: financial terms, tenant rights, liability and repairs, and more.',
            featureTips: 'Negotiation Tips',
            featureTipsDesc: 'Not just identifying issues - get concrete suggestions for fixing problematic clauses that you can present to the landlord.',
            featureAws: 'Secure Cloud Infrastructure',
            featureAwsDesc: 'Runs on AWS with end-to-end encryption. Your contracts are not stored and are automatically deleted after analysis.',
        },
        // Contracts Page
        contracts: {
            title: 'My Contracts',
            subtitle: 'Manage and view all your rental contracts',
            refresh: 'Refresh',
            uploadContract: 'Upload Contract',
            noContracts: 'No contracts yet',
            noContractsDesc: 'Upload your first rental contract for analysis',
            uploadFirst: 'Upload First Contract',
            deleteTitle: 'Delete Contract',
            deleteConfirm: 'Are you sure you want to delete this contract? This action cannot be undone.',
            cancel: 'Cancel',
            delete: 'Delete',
            deleting: 'Deleting...',
            editTitle: 'Edit Details',
            fileName: 'File Name',
            propertyAddress: 'Property Address',
            landlordName: 'Landlord Name',
            save: 'Save',
            saving: 'Saving...',
            loading: 'Loading contracts...',
            lowRisk: 'Low Risk',
            lowMediumRisk: 'Low-Medium Risk',
            mediumRisk: 'Medium Risk',
            highRisk: 'High Risk',
            analyzed: 'Completed',
            pendingAnalysis: 'Pending',
            notSpecified: 'Not specified',
            exportWord: 'Export Word',
            exportPDF: 'Export PDF',
            viewAnalysis: 'View Analysis',
            sortBy: 'Sort by:',
            sortDate: 'Date',
            sortScore: 'Risk Score',
            uploadDate: 'Upload Date',
        },
        // Upload Page
        upload: {
            title: 'Upload Contract',
            subtitle: 'Upload your rental contract for AI analysis',
            dragDrop: 'Drop PDF here',
            or: 'or click to select file',
            selectFile: 'Select Files',
            maxSize: 'Max size: 5MB | PDF only',
            termsLabel: 'I confirm that I have read and understood the',
            termsLink: 'Terms of Service and Privacy Policy',
            uploadBtn: 'Upload Contract for Analysis',
            uploading: 'Uploading...',
            complete: 'Complete!',
            uploadSuccess: 'Upload Successful!',
            analyzing: 'AI is analyzing your contract (30-60 seconds)...',
            uploadedToServer: '✓ Contract uploaded to server',
            analysisStarted: '✓ Analysis started',
            viewMyContracts: 'View My Contracts',
            uploadAnother: 'Upload Another Contract',
            // DAN DID IT - Added email notification message (English)
            uploadSuccessTitle: 'Contract Uploaded Successfully!',
            uploadSuccessMessage: 'Your contract analysis results will be sent to your email',
            goToContracts: 'Go to My Contracts',
            contractDetails: 'Contract Details (Optional)',
            propertyAddress: 'Property Address',
            addressPlaceholder: '123 Main Street, City',
            landlordName: 'Landlord Name',
            landlordPlaceholder: 'John Smith',
            contractName: 'Contract Name',
            termsTitle: 'Terms of Service and Privacy Policy',
            terms1Title: '1. Agreement to Terms',
            terms1Content: 'By uploading documents to RentGuard 360, you agree to the following terms of use:',
            terms2Title: '2. Use of Information',
            terms2Content: 'Documents you upload will be processed using AI technology for rental contract analysis. The information will be used solely to provide the requested service.',
            terms3Title: '3. Data Security',
            terms3Content: 'We are committed to protecting your information according to strict security standards. Documents are stored encrypted on AWS servers.',
            terms4Title: '4. Data Retention',
            terms4Content: 'Information will be retained for the time necessary to provide the service and in accordance with legal requirements.',
            terms5Title: '5. Limitation of Liability',
            terms5Content: 'The analysis provided by the system is for informational purposes only and does not constitute legal advice. It is recommended to consult with a lawyer before signing any contract.',
            terms6Title: '6. User Rights',
            terms6Content: 'You may request deletion of your data at any time by contacting support.',
            iAgree: 'I have read and agree',
            close: 'Close',
            pdfOnly: 'Only PDF files are allowed',
            fileTooLarge: 'File size must be less than 5MB',
            fileTooSmall: 'File is too small - may be empty or corrupted',
            fileNameTooLong: 'Filename is too long (max 100 characters)',
            uploadFailed: 'Upload failed. Please try again.',
        },
        // Analysis Page
        analysis: {
            title: 'Contract Analysis',
            backToContracts: 'Back to Contracts',
            summary: 'Summary',
            scoreBreakdown: 'Score Breakdown',
            refresh: 'Refresh',
            export: 'Export',
            issues: 'Issues Found',
            noIssues: 'No issues found in this contract',
            original: 'Original',
            problem: 'Problem',
            recommendation: 'Recommendation',
            copyFix: 'Copy Fix',
            copied: 'Copied!',
            askAI: 'Ask AI',
            loading: 'Loading analysis...',
            analyzing: 'Analyzing contract...',
            notContract: 'This document does not appear to be a rental contract',
        },
        // Score Breakdown
        score: {
            lowRisk: 'Low Risk',
            lowMediumRisk: 'Low-Medium Risk',
            mediumRisk: 'Medium Risk',
            mediumHighRisk: 'Medium-High Risk',
            highRisk: 'High Risk',
            financialTerms: 'Financial Terms',
            tenantRights: 'Tenant Rights',
            terminationClauses: 'Termination & Exit',
            liabilityRepairs: 'Liability & Repairs',
            legalCompliance: 'Legal Compliance',
        },
        // Footer
        footer: {
            tagline: 'AI-Powered Rental Contract Analysis Platform',
            benefits: 'Full Privacy | Fast & Secure Analysis | Negotiation Tips | Secure Cloud Infrastructure',
            project: 'Cloud Computing Final Project',
            copyright: '© {year} RentGuard 360. All rights reserved.',
        },
        // Common
        common: {
            loading: 'Loading...',
            error: 'Error',
            success: 'Success',
            user: 'User',
            cancel: 'Cancel',
            confirm: 'Confirm',
            ok: 'OK',
            comingSoon: 'Coming Soon',
        },
        // DAN DID IT - Added account deletion translations (English)
        // Account Settings
        account: {
            deleteAccount: 'Delete Account',
            deleteAccountDescription: 'Permanently delete your account and all your contracts',
            deleteConfirmTitle: 'Are you sure?',
            deleteConfirmMessage: 'This action will permanently delete your account, including:',
            deleteConfirmItem1: '• All your contracts',
            deleteConfirmItem2: '• All your analyses',
            deleteConfirmItem3: '• Your profile data',
            deleteConfirmWarning: 'This action cannot be undone!',
            typeDeleteToConfirm: 'Type DELETE to confirm:',
            deleteAccountSuccess: 'Account deleted successfully',
            deleteAccountError: 'Error deleting account',
            deletingAccount: 'Deleting account...',
            deletingContracts: 'Deleting contracts...',
        },
        // Admin Dashboard
        admin: {
            title: 'Admin Dashboard',
            accessDenied: 'Access Denied',
            noPermission: 'You do not have admin permissions',
            statsTab: 'Statistics',
            usersTab: 'Users',
            tryAgain: 'Try Again',
            // Stats
            contractsSection: 'Contracts',
            totalContracts: 'Total Contracts',
            analyzed: 'Analyzed',
            pending: 'Pending',
            failed: 'Failed',
            analysisSection: 'Analysis',
            avgRiskScore: 'Avg Risk Score',
            avgAnalysisTime: 'Avg Analysis Time',
            usersSection: 'Users',
            totalUsers: 'Total Users',
            activeUsers30: 'Active (30 days)',
            updatedAt: 'Updated',
            seconds: 'seconds',
            minutes: 'minutes',
            days: 'days',
            thisMonth: 'This Month',
            thisYear: 'This Year',
            analyzedOverTime: 'Analyzed Contracts Over Time',
            userRegistrations: 'User Registrations Over Time',
            noData: 'No data to display',
            // Users
            searchPlaceholder: 'Search by email or name...',
            search: 'Search',
            email: 'Email',
            name: 'Name',
            status: 'Status',
            joined: 'Joined',
            actions: 'Actions',
            noUsers: 'No users found',
            active: 'Active',
            suspended: 'Suspended',
            disable: 'Disable',
            enable: 'Enable',
            delete: 'Delete',
            allUsers: 'All Users',
            activeOnly: 'Active Only',
            disabledOnly: 'Disabled Only',
            showingUsers: 'Showing {count} users',
            confirmDisable: 'Are you sure you want to disable this user?',
            confirmDisableTitle: 'Disable User',
            confirmDelete: 'Are you sure you want to delete this user?',
            confirmDeleteTitle: 'Delete User',
            confirmDeleteFinal: 'This action cannot be undone! The user will be permanently deleted. Continue?',
            confirmDeleteFinalTitle: '⚠️ Final Confirmation',
            confirmDeleteBtn: 'Yes, Delete Permanently',
            selectYear: 'Select Year',
            userDeleted: 'User deleted successfully',
            // Admin Sidebar
            dashboard: 'Dashboard',
            analytics: 'Analytics',
            settings: 'Settings',
            administrator: 'Administrator',
            // Analytics Page
            analyticsDescription: 'Detailed contract analysis and risk insights',
            radarChart: 'Risk Radar',
            radarChartDesc: '5-axis risk analysis coming soon',
            sparklines: 'Trend Sparklines',
            sparklinesDesc: 'Mini trend charts coming soon',
            riskBreakdown: 'Risk Breakdown',
            riskBreakdownDesc: 'Detailed category analysis',
            riskDistribution: 'Risk Distribution',
            commonIssues: 'Common Issues in Contracts',
            code: 'Code',
            issue: 'Issue',
            count: 'Count',
            // Settings Page
            settingsDescription: 'System configuration and preferences',
            notifications: 'Notifications',
            notificationsDesc: 'Configure email and push notifications',
            security: 'Security',
            securityDesc: 'Authentication and access control',
            dataRetention: 'Data Retention',
            dataRetentionDesc: 'Contract storage and backup settings',
            emailTemplates: 'Email Templates',
            emailTemplatesDesc: 'Customize notification emails',
            comingSoon: 'Coming Soon',
        },
    },
};

// Create context
const LanguageContext = createContext();

// Provider component
export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        // Get saved language or default to Hebrew
        const saved = localStorage.getItem('rentguard-language');
        return saved || 'he';
    });

    useEffect(() => {
        // Save language preference
        localStorage.setItem('rentguard-language', language);
        // Update document direction
        document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
        document.documentElement.lang = language;
    }, [language]);

    const t = (key) => {
        const keys = key.split('.');
        let value = translations[language];
        for (const k of keys) {
            value = value?.[k];
        }
        return value || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'he' ? 'en' : 'he');
    };

    const isRTL = language === 'he';

    return (
        <LanguageContext.Provider value={{
            language,
            setLanguage,
            t,
            toggleLanguage,
            isRTL,
            translations: translations[language]
        }}>
            {children}
        </LanguageContext.Provider>
    );
};

// Custom hook
export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};

export default LanguageContext;
